import { BenzeneSubstituent, BenzeneDerivative } from './types';

// Real, named benzene-ring compounds -- hand-researched like everything
// else in Chem Lab, never AI-generated. Positions are 0-5 around the ring,
// used only to draw a sensible diagram; because the ring is symmetric,
// what actually distinguishes compounds is WHICH groups are present and
// their relative spacing (ortho/meta/para), not the absolute numbers -- see
// the Builder's gap-based matching logic.
export const BENZENE_SUBSTITUENTS: BenzeneSubstituent[] = [
  { id: 'methyl', formula: '-CH3', name: 'Methyl' },
  { id: 'hydroxyl', formula: '-OH', name: 'Hydroxyl' },
  { id: 'amino', formula: '-NH2', name: 'Amino' },
  { id: 'carboxyl', formula: '-COOH', name: 'Carboxyl' },
  { id: 'nitro', formula: '-NO2', name: 'Nitro' },
  { id: 'chloro', formula: '-Cl', name: 'Chloro' },
  { id: 'formyl', formula: '-CHO', name: 'Formyl' },
  { id: 'sulfonic', formula: '-SO3H', name: 'Sulfonic' },
  { id: 'vinyl', formula: '-CH=CH2', name: 'Vinyl' },
];

export const BENZENE_DERIVATIVES: BenzeneDerivative[] = [
  {
    id: 'toluene',
    name: 'Toluene (Methylbenzene)',
    molecularFormula: 'C7H8',
    substituents: [{ substituentId: 'methyl', position: 0 }],
    category: 'Industrial solvent',
    description: 'Benzene with one hydrogen replaced by a methyl group. A clear, sweet-smelling liquid, one of the most widely used industrial solvents in the world.',
    commonUses: ['A solvent in paints, glues, and nail polish', 'A raw material for making TNT and other chemicals', 'A component of gasoline that boosts octane rating'],
    safetyNotes: ['Flammable, and breathing large amounts of the vapor can cause dizziness -- always used with good ventilation.'],
    funFact: 'Toluene is generally considered a safer substitute for benzene in labs and industry, since it is not classified as a carcinogen the way benzene is.',
  },
  {
    id: 'phenol',
    name: 'Phenol (Hydroxybenzene)',
    molecularFormula: 'C6H5OH',
    substituents: [{ substituentId: 'hydroxyl', position: 0 }],
    category: 'Industrial chemical / historic antiseptic',
    description: 'Benzene with one hydrogen replaced by a hydroxyl (-OH) group. A white crystalline solid with a distinctive medicinal smell.',
    commonUses: ['A starting material for making plastics (Bakelite) and resins', 'Historically the first widely used surgical antiseptic (by Joseph Lister, 1867)', 'Used to make aspirin and other pharmaceuticals'],
    safetyNotes: ['Corrosive and toxic on skin contact even in fairly dilute solutions -- real handling needs gloves and care.'],
    funFact: "Phenol's antiseptic use in the 1800s is credited with dramatically reducing deaths from infection after surgery.",
  },
  {
    id: 'aniline',
    name: 'Aniline (Aminobenzene)',
    molecularFormula: 'C6H5NH2',
    substituents: [{ substituentId: 'amino', position: 0 }],
    category: 'Dye industry raw material',
    description: 'Benzene with one hydrogen replaced by an amino (-NH2) group. An oily liquid that darkens on exposure to air and light.',
    commonUses: ['The starting material for a huge range of synthetic dyes (the "aniline dyes" that founded the modern dye industry)', 'Used to make some rubber-processing chemicals and pharmaceuticals'],
    safetyNotes: ['Toxic and absorbed readily through skin -- real handling needs gloves and a fume hood.'],
    funFact: "The world's first synthetic dye, mauveine, was accidentally discovered in 1856 by 18-year-old William Perkin while trying to synthesize a malaria drug from aniline.",
  },
  {
    id: 'benzoic-acid',
    name: 'Benzoic Acid',
    molecularFormula: 'C6H5COOH',
    substituents: [{ substituentId: 'carboxyl', position: 0 }],
    category: 'Food preservative',
    description: 'Benzene with one hydrogen replaced by a carboxyl (-COOH) group. A white crystalline solid.',
    commonUses: ['A common food preservative (E210), used in soft drinks, pickles, and sauces', 'A starting material for making other chemicals'],
    funFact: 'Benzoic acid occurs naturally in cranberries, prunes, and cinnamon -- it was first extracted from gum benzoin resin, which is where its name comes from.',
  },
  {
    id: 'nitrobenzene',
    name: 'Nitrobenzene',
    molecularFormula: 'C6H5NO2',
    substituents: [{ substituentId: 'nitro', position: 0 }],
    category: 'Industrial intermediate',
    description: 'Benzene with one hydrogen replaced by a nitro (-NO2) group -- the direct product of the nitration reaction. A pale yellow, oily liquid with an almond-like smell.',
    commonUses: ['Almost entirely used as the starting material to manufacture aniline', 'A minor use as a solvent for some waxes and shoe polishes'],
    safetyNotes: ['Toxic if absorbed through skin or inhaled -- real handling needs a fume hood.'],
    funFact: "Despite its pleasant almond smell, nitrobenzene is genuinely toxic -- a reminder that a chemical's smell says nothing about whether it's safe.",
  },
  {
    id: 'chlorobenzene',
    name: 'Chlorobenzene',
    molecularFormula: 'C6H5Cl',
    substituents: [{ substituentId: 'chloro', position: 0 }],
    category: 'Industrial solvent / intermediate',
    description: 'Benzene with one hydrogen replaced by a chlorine atom -- the direct product of the halogenation reaction. A colorless liquid.',
    commonUses: ['A solvent and starting material for making other chemicals, dyes, and pesticides', 'Historically a starting material for DDT (now banned in most countries)'],
    funFact: 'Chlorobenzene production was central to how DDT was manufactured -- once celebrated for controlling malaria-carrying mosquitoes, later banned once its environmental harm became clear.',
  },
  {
    id: 'benzaldehyde',
    name: 'Benzaldehyde',
    molecularFormula: 'C6H5CHO',
    substituents: [{ substituentId: 'formyl', position: 0 }],
    category: 'Flavoring / fragrance',
    description: 'Benzene with one hydrogen replaced by a formyl (-CHO) group. A colorless liquid with a strong almond smell.',
    commonUses: ['The primary flavor compound behind artificial "almond" flavoring', 'Used in perfumes and as a starting material for other chemicals'],
    funFact: 'Benzaldehyde occurs naturally in almonds, cherry pits, and apricot kernels -- the same almond smell people associate with cyanide poisoning, because both happen to smell similar (though the two are otherwise unrelated).',
  },
  {
    id: 'benzenesulphonic-acid',
    name: 'Benzenesulphonic Acid',
    molecularFormula: 'C6H5SO3H',
    substituents: [{ substituentId: 'sulfonic', position: 0 }],
    category: 'Detergent industry raw material',
    description: 'Benzene with one hydrogen replaced by a sulfonic (-SO3H) group -- the direct product of the sulphonation reaction.',
    commonUses: ['A key building block for manufacturing synthetic detergents', 'Used to make some dyes'],
    funFact: 'Most modern laundry and dish detergents rely on a close relative of this exact molecule as their main cleaning ingredient.',
  },
  {
    id: 'styrene',
    name: 'Styrene (Vinylbenzene)',
    molecularFormula: 'C6H5CH=CH2',
    substituents: [{ substituentId: 'vinyl', position: 0 }],
    category: 'Plastics raw material',
    description: 'Benzene with one hydrogen replaced by a vinyl (-CH=CH2) group. A colorless, sweetish-smelling liquid that readily links up with itself.',
    commonUses: ['The building block for polystyrene -- one of the most common plastics in the world, used in packaging, disposable cutlery, and foam (Styrofoam)', 'Used to make synthetic rubber'],
    funFact: 'Every styrene molecule can link end-to-end with thousands of others to form one giant polystyrene chain -- the same cross-linking idea explored (more simply) in the slime experiment elsewhere in Chem Lab.',
  },
  {
    id: 'ortho-xylene',
    name: 'ortho-Xylene (1,2-Dimethylbenzene)',
    molecularFormula: 'C6H4(CH3)2',
    substituents: [{ substituentId: 'methyl', position: 0 }, { substituentId: 'methyl', position: 1 }],
    category: 'Positional isomer of xylene',
    description: 'Benzene with two methyl groups on adjacent ring positions ("ortho", right next to each other).',
    commonUses: ['An industrial solvent and a starting material for making phthalic anhydride, used in plastics.'],
    funFact: 'Ortho-, meta-, and para-xylene are all made of exactly the same atoms in the same formula (C8H10) -- only the positions of the two methyl groups differ, which is enough to make them three genuinely different substances with different boiling points and uses.',
  },
  {
    id: 'meta-xylene',
    name: 'meta-Xylene (1,3-Dimethylbenzene)',
    molecularFormula: 'C6H4(CH3)2',
    substituents: [{ substituentId: 'methyl', position: 0 }, { substituentId: 'methyl', position: 2 }],
    category: 'Positional isomer of xylene',
    description: 'Benzene with two methyl groups one position apart ("meta", with one carbon between them).',
    commonUses: ['The most commonly produced xylene isomer industrially -- a solvent and a starting material for making isophthalic acid, used in some plastics and resins.'],
    funFact: 'Meta-xylene is usually the major product when benzene is industrially methylated, simply because of how the reaction statistically favors that spacing.',
  },
  {
    id: 'para-xylene',
    name: 'para-Xylene (1,4-Dimethylbenzene)',
    molecularFormula: 'C6H4(CH3)2',
    substituents: [{ substituentId: 'methyl', position: 0 }, { substituentId: 'methyl', position: 3 }],
    category: 'Positional isomer of xylene',
    description: 'Benzene with two methyl groups directly opposite each other ("para", furthest apart on the ring).',
    commonUses: ['The starting material for making PET plastic -- the material used in most plastic drink bottles and polyester fabric.'],
    funFact: 'Almost every plastic water bottle and polyester shirt traces back to para-xylene as a starting ingredient.',
  },
  {
    id: 'tnt',
    name: 'TNT (2,4,6-Trinitrotoluene)',
    molecularFormula: 'C6H2(NO2)3CH3',
    substituents: [
      { substituentId: 'methyl', position: 0 },
      { substituentId: 'nitro', position: 1 },
      { substituentId: 'nitro', position: 3 },
      { substituentId: 'nitro', position: 5 },
    ],
    category: 'Explosive (historical and military)',
    description: 'Toluene with three of its remaining ring hydrogens each replaced by a nitro group, evenly spaced around the ring. A pale yellow solid.',
    commonUses: ['One of the most well-known explosives, historically used in mining, demolition, and munitions.', 'A reference compound -- explosive power is often measured in "TNT equivalent" even for other explosives entirely.'],
    safetyNotes: ['Genuinely explosive under shock, friction, or flame -- obviously never handled by students, and shown here purely as structural theory, exactly like the rest of this page.'],
    funFact: "TNT's structure is a great real-world example of why nitro groups matter so much in explosives: each -NO2 group carries its own built-in oxygen supply, letting the molecule combust extremely fast without needing outside air.",
    builderExcluded: true,
  },
];
