import { BiologyExperiment } from './biologyTypes';

// First Biology Lab pass -- 9 experiments spanning Class 4 through Class 12,
// across Nutrition/Human Biology, Cell Biology, Ecology, and Genetics. Every
// predict-question has exactly one verifiably correct answer, every food-
// test color and every genetics ratio is the real, standard result -- see
// biologyEquipment.ts for the apparatus referenced here. Botany (beyond the
// plant cell) and Zoology are a deliberate next pass, not shipped
// half-finished here -- same scoping discipline as Physics Lab's Optics/
// Electricity/Waves rollout.
export const BIOLOGY_EXPERIMENTS: BiologyExperiment[] = [
  {
    id: 'exp-starch-test',
    title: 'Testing Food for Starch (Iodine Test)',
    branch: 'human-biology',
    gradeBand: 'junior',
    board: 'both',
    chapterTags: ['Components of Food', 'Nutrients', 'Food Tests'],
    simType: 'foodtest',
    defaultParams: { foodSample: 0 },
    paramConfig: [
      { key: 'foodSample', label: 'Food Sample', unit: '', min: 0, max: 3, step: 1, choices: [
        { value: 0, label: 'Boiled Potato' }, { value: 1, label: 'Rice' }, { value: 2, label: 'Egg White' }, { value: 3, label: 'Cooking Oil' },
      ] },
    ],
    apparatusIds: ['test-tube-food', 'iodine-solution-bio'],
    purpose: 'To test different foods for the presence of starch using iodine solution.',
    predictPrompt: 'You add a drop of iodine solution to a piece of boiled potato. What color change indicates starch is present?',
    predictOptions: ['Turns blue-black', 'Turns bright red', 'No change at all', 'Turns bright green'],
    correctPredictIndex: 0,
    keyIdea: 'Iodine solution turns blue-black in the presence of starch.',
    keyIdeaVars: ['foodSample'],
    steps: [
      { number: 1, instruction: 'Add a drop of iodine solution to the boiled potato sample.', action: 'release' },
      { number: 2, instruction: 'Note the color change.', action: 'observe' },
      { number: 3, instruction: 'Now try testing rice instead.', paramChanges: { foodSample: 1 }, action: 'observe' },
      { number: 4, instruction: 'Now try egg white -- predict whether it contains starch first.', paramChanges: { foodSample: 2 }, action: 'observe', hint: 'Egg white is almost entirely protein, not starch.' },
    ],
    observationPrompts: [
      'Which foods turned blue-black with iodine?',
      'Why do you think egg white and cooking oil did NOT react with iodine?',
    ],
    explanation: 'Starch is a long, coiled molecule made of many glucose units joined together. Iodine molecules fit precisely inside that coiled shape, and this specific fit is what produces the blue-black color. Foods without starch -- like egg white (mostly protein) or cooking oil (pure fat) -- have no coiled starch molecules for iodine to bind to, so they show no color change.',
    realWorldApplications: [
      'Food manufacturers use starch tests to check ingredient labels and detect adulteration.',
      'This is the same basic chemistry used to test whether a leaf has been photosynthesizing -- a destarched leaf shows no blue-black color.',
    ],
    safetyNotes: ['Iodine solution can stain skin and clothing -- handle carefully.'],
    extensions: [
      'Would a slice of bread test positive or negative for starch? Why?',
      'What foods in your kitchen do you predict would test positive for starch?',
    ],
    realLifeNote: 'This exact test is used in school biology labs worldwide to prove that leaves only produce starch in sunlight -- a destarched leaf kept in the dark shows no color change, while one kept in light does.',
  },
  {
    id: 'exp-fat-test',
    title: 'Testing Food for Fat (Grease Spot Test)',
    branch: 'human-biology',
    gradeBand: 'junior',
    board: 'both',
    chapterTags: ['Components of Food', 'Nutrients', 'Food Tests'],
    simType: 'foodtest',
    defaultParams: { foodSample: 0 },
    paramConfig: [
      { key: 'foodSample', label: 'Food Sample', unit: '', min: 0, max: 3, step: 1, choices: [
        { value: 0, label: 'Cooking Oil' }, { value: 1, label: 'Butter' }, { value: 2, label: 'Boiled Potato' }, { value: 3, label: 'Egg White' },
      ] },
    ],
    apparatusIds: ['test-tube-food', 'sudan-iii-reagent'],
    purpose: 'To test different foods for the presence of fat using the grease spot method.',
    predictPrompt: 'You rub a drop of cooking oil onto plain paper and let it dry. What do you observe?',
    predictOptions: ['A translucent spot that does not disappear', 'The paper turns blue-black', 'The paper dissolves', 'Nothing happens at all'],
    correctPredictIndex: 0,
    keyIdea: 'Fats leave a permanent translucent grease spot on paper; water marks dry up and disappear.',
    keyIdeaVars: ['foodSample'],
    steps: [
      { number: 1, instruction: 'Rub a drop of cooking oil onto the paper.', action: 'release' },
      { number: 2, instruction: 'Let it dry and check the spot.', action: 'observe' },
      { number: 3, instruction: 'Now try butter instead.', paramChanges: { foodSample: 1 }, action: 'observe' },
      { number: 4, instruction: 'Now try boiled potato -- predict the result first.', paramChanges: { foodSample: 2 }, action: 'observe' },
    ],
    observationPrompts: [
      'Which foods left a translucent, permanent spot?',
      'How is a grease spot different from a plain water mark on paper?',
    ],
    explanation: "Fats are non-polar molecules that don't evaporate the way water does, and they scatter light differently than paper fibers alone -- which is what makes a fat-soaked patch of paper look translucent (letting light through) rather than opaque. A water spot, by contrast, evaporates within minutes and leaves no lasting mark.",
    realWorldApplications: [
      'This simple test is still used informally to check how much fat is in packaged snacks.',
      'Sudan III staining (a red-dye version of this same test) is used in real biology labs to see fat droplets under a microscope.',
    ],
    safetyNotes: [],
    extensions: [
      'Would you expect skimmed milk to leave a grease spot? Why or why not?',
      'Why is testing on paper better than testing on cloth?',
    ],
    realLifeNote: 'Nutrition labels list fat content in grams precisely because of tests like this -- Sudan III staining and similar fat-detection methods are still used in food science labs today, just with more precise instruments.',
  },
  {
    id: 'exp-digestive-system',
    title: 'Explore the Human Digestive System',
    branch: 'human-biology',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Nutrition in Animals', 'Digestive System'],
    simType: 'explorer',
    defaultParams: {},
    paramConfig: [],
    apparatusIds: ['digestive-system-diagram'],
    diagramId: 'digestive-system',
    explorerParts: [
      { id: 'mouth', label: 'Mouth', info: 'Chewing breaks food into smaller pieces, and saliva begins digesting starch.', deepDive: 'Saliva contains an enzyme called amylase that starts breaking down starch into simpler sugars right in the mouth -- which is why bread can start to taste faintly sweet if you chew it for a long time.' },
      { id: 'esophagus', label: 'Esophagus', info: 'A muscular tube that pushes food down to the stomach using wave-like muscle contractions.', deepDive: 'These wave-like contractions (called peristalsis) are strong enough that you could actually swallow while upside down -- food doesn\'t rely on gravity to reach your stomach.' },
      { id: 'stomach', label: 'Stomach', info: 'Churns food and mixes it with acid and enzymes, starting protein digestion.', deepDive: "Stomach acid is strong enough to dissolve metal, but a thick mucus lining constantly protects the stomach's own walls from being digested by its own acid." },
      { id: 'small-intestine', label: 'Small Intestine', info: 'Most digestion finishes here, and almost all nutrients are absorbed into the blood.', deepDive: 'The small intestine is lined with millions of tiny finger-like projections called villi -- if flattened out, its total absorbing surface area would be roughly the size of a tennis court.' },
      { id: 'large-intestine', label: 'Large Intestine', info: 'Absorbs leftover water from the undigested waste before it leaves the body.', deepDive: 'Billions of harmless bacteria live in the large intestine and help break down material human enzymes can\'t digest alone -- they also produce some vitamins the body absorbs and uses.' },
      { id: 'liver', label: 'Liver', info: 'Produces bile, which helps break down fats in the small intestine.', deepDive: "The liver is the body's largest internal organ and performs hundreds of jobs beyond digestion, including filtering toxins from the blood and storing extra glucose as glycogen." },
      { id: 'pancreas', label: 'Pancreas', info: 'Produces digestive enzymes that are released into the small intestine to break down food.', deepDive: 'The pancreas has a second, completely separate job too -- it also produces insulin, the hormone that controls blood sugar levels throughout the body.' },
    ],
    purpose: 'To explore the organs of the human digestive system and understand the role each one plays in digesting food.',
    predictPrompt: 'Where does most of the digestion and absorption of food happen in the human body?',
    predictOptions: ['Small intestine', 'Stomach', 'Large intestine', 'Esophagus'],
    correctPredictIndex: 0,
    keyIdea: 'Food is broken down step by step as it travels through one continuous tube, from mouth to exit.',
    keyIdeaVars: [],
    steps: [
      { number: 1, instruction: 'Click on the mouth to see what happens first.', action: 'observe' },
      { number: 2, instruction: 'Now click through the stomach and small intestine.', action: 'observe' },
      { number: 3, instruction: 'Finally, explore the large intestine, liver, and pancreas.', action: 'observe' },
    ],
    observationPrompts: [
      'Which organ does most of the actual digestion and nutrient absorption?',
      'What does the large intestine mainly do, if most digestion already happened earlier?',
    ],
    explanation: "Digestion isn't a single event -- it's a sequence, with each organ doing a specific job on food as it passes through: the mouth starts breaking down starch, the stomach churns and starts protein digestion, the small intestine (helped by the liver's bile and the pancreas's enzymes) finishes digestion and absorbs almost all the nutrients into the blood, and the large intestine absorbs leftover water before the waste is eliminated.",
    realWorldApplications: [
      'Doctors use this exact organ-by-organ map to diagnose digestive problems based on where symptoms occur.',
      "Understanding this pathway is why nutritionists recommend chewing food thoroughly -- it gives the mouth's enzymes more surface area to work with.",
    ],
    safetyNotes: [],
    extensions: [
      'What might happen if the small intestine were damaged and could not absorb nutrients properly?',
      'Why do you think the small intestine is coiled up rather than straight?',
    ],
    realLifeNote: 'The full digestive tract is roughly 9 metres long when straightened out -- coiled compactly inside the abdomen, it takes food anywhere from 24 to 72 hours to travel the entire route from end to end.',
  },
  {
    id: 'exp-onion-cell',
    title: 'Onion Cell Under the Microscope',
    branch: 'cell-biology',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Cell Structure and Functions', 'Microscopy'],
    simType: 'microscope',
    defaultParams: { focus: 10, magnification: 0 },
    paramConfig: [
      { key: 'focus', label: 'Focus', unit: '', min: 0, max: 100, step: 1 },
      { key: 'magnification', label: 'Magnification', unit: '', min: 0, max: 1, step: 1, choices: [
        { value: 0, label: '100x (Low Power)' }, { value: 1, label: '400x (High Power)' },
      ] },
    ],
    apparatusIds: ['microscope', 'glass-slide', 'onion-peel'],
    purpose: 'To prepare a wet-mount slide of onion peel and observe real plant cells under the microscope.',
    predictPrompt: 'What will you see when you correctly focus on an onion peel slide under the microscope?',
    predictOptions: ['Brick-like cells, each with a visible nucleus', 'One giant, blurry blob', 'Nothing -- onion peel is invisible', 'Moving red dots'],
    correctPredictIndex: 0,
    keyIdea: 'Turning the focus knob moves the specimen toward the exact distance where it forms a sharp image.',
    keyIdeaVars: ['focus'],
    steps: [
      { number: 1, instruction: 'The slide is in place -- slowly turn the focus knob.', action: 'release' },
      { number: 2, instruction: 'Keep adjusting until the cells come into sharp focus.', action: 'observe', hint: 'The sharpest focus is somewhere in the middle of the range.' },
      { number: 3, instruction: 'Now switch to high power (400x) and refocus.', paramChanges: { magnification: 1 }, action: 'observe' },
    ],
    observationPrompts: [
      'What shape are the individual onion cells?',
      'What did switching to high power change about what you could see?',
    ],
    explanation: 'A microscope only shows a sharp image when the specimen sits at one very precise distance from the lens (its focal point) -- too close or too far, and light rays from the specimen don\'t converge properly, producing a blur. At the right focus, onion cells appear as a tiled pattern of rectangular "bricks", each with a visible circular nucleus and a thin cell wall outline.',
    realWorldApplications: [
      'Pathologists use this exact focusing technique to examine tissue samples for signs of disease.',
      'Water quality testing labs use microscopes the same way to identify microorganisms in a water sample.',
    ],
    safetyNotes: ['Handle glass slides and cover slips carefully -- they chip and cut easily.'],
    extensions: [
      'Would a cheek cell (from inside your own mouth) look the same as an onion cell? What might be different?',
      'Why is the onion peel being only one cell thick a useful feature for this experiment?',
    ],
    realLifeNote: 'Robert Hooke first used the word "cell" in 1665 after looking at cork under an early microscope -- the boxy compartments reminded him of the small rooms ("cells") monks lived in.',
  },
  {
    id: 'exp-plant-cell',
    title: 'Explore the Plant Cell',
    branch: 'cell-biology',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Cell Structure and Functions', 'Plant Cell'],
    simType: 'explorer',
    defaultParams: {},
    paramConfig: [],
    apparatusIds: ['plant-cell-diagram'],
    diagramId: 'plant-cell',
    explorerParts: [
      { id: 'cell-wall', label: 'Cell Wall', info: 'A rigid outer layer made of cellulose that gives the cell its shape and support.', deepDive: 'Only plant cells (and some other organisms like fungi) have a cell wall -- animal cells never do, which is exactly why plant cells keep a fixed rectangular shape while animal cells are more flexible and rounded.' },
      { id: 'cell-membrane', label: 'Cell Membrane', info: 'A thin layer just inside the cell wall that controls exactly what enters and exits the cell.', deepDive: 'The cell membrane is "selectively permeable" -- it lets some substances (like water and oxygen) pass through freely while blocking others, acting like a smart gatekeeper rather than a simple wall.' },
      { id: 'nucleus', label: 'Nucleus', info: "Contains the cell's DNA and controls all of the cell's activities.", deepDive: "The nucleus is often called the cell's \"control center\" -- if it's removed, the cell can survive briefly but eventually dies, since it can no longer produce the proteins it needs to function." },
      { id: 'chloroplast', label: 'Chloroplast', info: 'The green organelle where photosynthesis happens, using sunlight to make food.', deepDive: 'Chloroplasts contain a green pigment called chlorophyll, which absorbs red and blue light for photosynthesis but reflects green light back to our eyes -- that reflected green light is literally why plants look green.' },
      { id: 'vacuole', label: 'Vacuole', info: 'A large, central, water-filled sac that stores water and nutrients and keeps the cell firm.', deepDive: "The pressure of water inside a plant cell's vacuole pushing against its cell wall (called turgor pressure) is what keeps a healthy plant standing upright -- lose that pressure, and the plant wilts, even though every cell is still alive." },
      { id: 'mitochondria', label: 'Mitochondria', info: 'Releases usable energy from food through a process called cellular respiration.', deepDive: 'Mitochondria are found in both plant and animal cells -- unlike chloroplasts, which only plants have, every living cell that needs energy relies on mitochondria to release it from food.' },
    ],
    purpose: 'To identify and understand the function of each major structure inside a plant cell.',
    predictPrompt: 'Which structure allows a plant cell to make its own food using sunlight?',
    predictOptions: ['Chloroplast', 'Mitochondria', 'Nucleus', 'Vacuole'],
    correctPredictIndex: 0,
    keyIdea: 'Plant cells have three structures animal cells lack: a cell wall, a large vacuole, and chloroplasts.',
    keyIdeaVars: [],
    steps: [
      { number: 1, instruction: 'Click on the cell wall and cell membrane first.', action: 'observe' },
      { number: 2, instruction: 'Now click on the nucleus and chloroplast.', action: 'observe' },
      { number: 3, instruction: 'Finally, explore the vacuole and mitochondria.', action: 'observe' },
    ],
    observationPrompts: [
      'Which structure is unique to plant cells and is responsible for photosynthesis?',
      'What is the difference between the cell wall and the cell membrane?',
    ],
    explanation: 'Every structure in a plant cell has a specific job: the rigid cell wall gives the cell its shape and support, the cell membrane controls what moves in and out, the nucleus stores DNA and directs all cell activity, chloroplasts capture sunlight to make food (photosynthesis), the large central vacuole stores water and keeps the cell firm, and mitochondria release usable energy from that food (respiration).',
    realWorldApplications: [
      'Understanding chloroplasts is the basis of all agriculture -- crop scientists study how to maximize photosynthetic efficiency to increase food yields.',
      'Wilted plants perk up after watering because their vacuoles refill with water and press outward against the cell wall again.',
    ],
    safetyNotes: [],
    extensions: [
      "Why do plants wilt when they don't get enough water?",
      'If you removed the cell wall, would the cell still hold its rectangular shape?',
    ],
    realLifeNote: "The pressure of water inside a plant cell's vacuole pushing against its cell wall is literally what keeps a healthy plant standing upright -- lose that pressure, and the plant wilts, even though every cell is still alive.",
  },
  {
    id: 'exp-food-chain',
    title: 'Explore a Food Chain',
    branch: 'ecology',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Food Chains and Webs', 'Ecosystems'],
    simType: 'explorer',
    defaultParams: {},
    paramConfig: [],
    apparatusIds: ['food-chain-diagram'],
    diagramId: 'food-chain',
    explorerParts: [
      { id: 'producer', label: 'Grass (Producer)', info: 'Makes its own food through photosynthesis -- the base of every food chain.', deepDive: 'Every food chain on Earth ultimately starts with a producer capturing energy from sunlight -- without producers, no other organism in the chain would have any energy source at all.' },
      { id: 'primary-consumer', label: 'Grasshopper (Primary Consumer)', info: 'A herbivore that eats producers directly.', deepDive: 'Primary consumers are almost always far more numerous than the predators above them -- a single field might support thousands of grasshoppers but only a handful of frogs.' },
      { id: 'secondary-consumer', label: 'Frog (Secondary Consumer)', info: 'Eats primary consumers like insects.', deepDive: 'Secondary consumers that eat both plants and animals are called omnivores, while ones that only eat other animals (like most frogs, mainly) are carnivores.' },
      { id: 'tertiary-consumer', label: 'Snake (Tertiary Consumer)', info: 'Eats secondary consumers like frogs.', deepDive: "A tertiary consumer sits high enough in the chain that removing it can cause a \"trophic cascade\" -- without snakes to control frog populations, insect populations the frogs used to eat can spike unexpectedly." },
      { id: 'apex-predator', label: 'Eagle (Apex Predator)', info: 'Sits at the top of the food chain, with no natural predators of its own.', deepDive: "Apex predators are naturally rare -- the \"10% rule\" of energy loss at each step means a huge base of producers and prey is needed just to support a handful of animals at the very top." },
      { id: 'decomposer', label: 'Fungi & Bacteria (Decomposers)', info: 'Break down dead organisms and waste, returning nutrients to the soil for producers to use again.', deepDive: 'Decomposers are the reason food chains form a cycle, not a dead end -- without them, nutrients would stay locked inside dead bodies forever instead of becoming available for the next generation of plants to grow.' },
    ],
    purpose: 'To explore how energy flows from one organism to the next in a real ecosystem food chain.',
    predictPrompt: 'In a food chain, roughly what fraction of energy passes from one level to the next?',
    predictOptions: ['About 10%', 'About 50%', 'About 90%', 'All of it, 100%'],
    correctPredictIndex: 0,
    keyIdea: 'Only about 10% of energy transfers from one trophic level to the next -- the rest is lost as heat.',
    keyIdeaVars: [],
    steps: [
      { number: 1, instruction: 'Click on the grass (producer) to start the chain.', action: 'observe' },
      { number: 2, instruction: 'Follow the chain through the grasshopper, frog, and snake.', action: 'observe' },
      { number: 3, instruction: 'Explore the eagle and the decomposers.', action: 'observe' },
    ],
    observationPrompts: [
      'Why does energy decrease at each step of the food chain?',
      "What role do decomposers play that isn't obvious just from looking at the chain?",
    ],
    explanation: 'Every organism uses most of the energy it eats just to stay alive -- moving, growing, staying warm -- and that energy is lost as heat, not passed on. Only roughly 10% of the energy an organism eats ends up stored in its own body tissue, available to whatever eats it next. This "10% rule" is why food chains are short (rarely more than 4-5 links) and why there are always far more producers than apex predators in a healthy ecosystem.',
    realWorldApplications: [
      'This is why eating lower on the food chain (plants) feeds more people per acre of farmland than eating meat.',
      'Conservationists use this energy math to estimate how large a wilderness area needs to be to support a stable population of top predators.',
    ],
    safetyNotes: [],
    extensions: [
      'Why are there far more grasshoppers in a field than eagles?',
      'What would happen to the whole chain if all the decomposers disappeared?',
    ],
    realLifeNote: 'This is also why apex predators like eagles and tigers are naturally rare and often endangered -- the 10% rule means a huge base of producers and prey is needed just to support a handful of animals at the very top.',
  },
  {
    id: 'exp-protein-test',
    title: 'Testing Food for Protein (Biuret Test)',
    branch: 'human-biology',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Biomolecules', 'Food Tests', 'Life Processes'],
    simType: 'foodtest',
    defaultParams: { foodSample: 0 },
    paramConfig: [
      { key: 'foodSample', label: 'Food Sample', unit: '', min: 0, max: 3, step: 1, choices: [
        { value: 0, label: 'Egg White' }, { value: 1, label: 'Milk' }, { value: 2, label: 'Boiled Potato' }, { value: 3, label: 'Cooking Oil' },
      ] },
    ],
    apparatusIds: ['test-tube-food', 'biuret-reagent'],
    purpose: 'To test different foods for the presence of protein using Biuret reagent.',
    predictPrompt: 'Biuret reagent turns which color when protein is present in a food sample?',
    predictOptions: ['Violet / Purple', 'Brick-red', 'Blue-black', 'Bright yellow'],
    correctPredictIndex: 0,
    keyIdea: "Biuret reagent turns violet/purple in the presence of protein's peptide bonds.",
    keyIdeaVars: ['foodSample'],
    steps: [
      { number: 1, instruction: 'Add Biuret reagent to the egg white sample.', action: 'release' },
      { number: 2, instruction: 'Note the color change.', action: 'observe' },
      { number: 3, instruction: 'Now try milk instead.', paramChanges: { foodSample: 1 }, action: 'observe' },
      { number: 4, instruction: 'Now try boiled potato -- predict the result first.', paramChanges: { foodSample: 2 }, action: 'observe', hint: 'Potato is mostly starch, not protein.' },
    ],
    observationPrompts: [
      'Which foods turned violet with Biuret reagent?',
      'Why do starchy foods like potato NOT react with Biuret reagent?',
    ],
    explanation: "Biuret reagent contains copper ions that form a colored complex specifically with peptide bonds -- the chemical links that join amino acids together into a protein chain. Foods made mostly of starch or fat simply don't have peptide bonds, so no matter how much Biuret reagent is added, there's nothing for the copper to bind to and no color change occurs.",
    realWorldApplications: [
      'This test (or more advanced versions of it) is used in clinical labs to measure protein levels in blood and urine samples.',
      'Food scientists use protein tests like this to verify nutrition label claims on high-protein products.',
    ],
    safetyNotes: ['Biuret reagent contains sodium hydroxide and copper sulfate -- avoid skin contact.'],
    extensions: [
      'Would you expect cheese to test positive or negative for protein? Why?',
      'Could a food test positive for BOTH starch (iodine) and protein (Biuret)? Give an example.',
    ],
    realLifeNote: 'This is a genuinely important real-world test -- some medical conditions (like kidney disease) cause protein to leak into urine, and a Biuret-style test is one of the ways doctors check for that.',
  },
  {
    id: 'exp-osmosis-potato',
    title: 'Osmosis in a Potato Strip',
    branch: 'cell-biology',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Life Processes', 'Osmosis', 'Cell Transport'],
    simType: 'osmosis',
    defaultParams: { solutionConcentration: 300 },
    paramConfig: [
      { key: 'solutionConcentration', label: 'Solution Concentration', unit: '', min: 0, max: 1000, step: 50 },
    ],
    apparatusIds: ['potato-strip', 'salt-solution'],
    purpose: 'To observe how a potato strip changes size when placed in solutions of different concentrations, demonstrating osmosis.',
    predictPrompt: "A potato strip is placed in strong salt water (higher solute concentration than the potato's own cells). What happens to the strip?",
    predictOptions: ['It shrinks and becomes limp', 'It swells and becomes firm', 'No change happens at all', 'It dissolves completely'],
    correctPredictIndex: 0,
    keyIdea: 'Water moves from an area of lower solute concentration to an area of higher solute concentration, across a membrane.',
    keyIdeaVars: ['solutionConcentration'],
    steps: [
      { number: 1, instruction: "Place the strip in a solution matching the potato's own concentration.", paramChanges: { solutionConcentration: 300 }, action: 'release' },
      { number: 2, instruction: 'Watch closely -- this is the "isotonic" baseline case.', action: 'observe' },
      { number: 3, instruction: 'Now try a much stronger salt solution.', paramChanges: { solutionConcentration: 800 }, action: 'observe' },
      { number: 4, instruction: 'Now try a much weaker, more dilute solution.', paramChanges: { solutionConcentration: 50 }, action: 'observe', hint: 'This should do the opposite of the strong solution.' },
    ],
    observationPrompts: [
      'What happened to the potato strip in the strong salt solution?',
      'What happened in the very dilute solution, and why is that the opposite result?',
    ],
    explanation: 'Osmosis is the movement of water across a membrane from a region of LOWER solute concentration to a region of HIGHER solute concentration, trying to balance things out. If the surrounding solution is more concentrated than the potato\'s own cells (hypertonic), water leaves the cells and the strip shrinks and goes limp. If the solution is more dilute (hypotonic), water enters the cells and the strip swells and becomes firmer.',
    realWorldApplications: [
      "This is exactly why salting meat or fish (or sugaring fruit for jam) preserves it -- the strong solute concentration pulls water out of any bacteria present, so they can't survive.",
      'Plant roots absorb water from soil using this same principle -- root cells maintain a higher solute concentration than the surrounding soil water.',
    ],
    safetyNotes: [],
    extensions: [
      'Why do slugs shrivel up when salt is sprinkled on them?',
      'What would happen to a potato strip placed in pure distilled water?',
    ],
    realLifeNote: 'IV drips given in hospitals are carefully balanced to match the concentration of human blood cells (isotonic) -- a drip that\'s too concentrated or too dilute would cause blood cells to shrink or even burst via this exact same osmosis process.',
  },
  {
    id: 'exp-punnett-square',
    title: 'Punnett Square: Predicting Offspring Traits',
    branch: 'genetics',
    gradeBand: 'plusTwo',
    board: 'both',
    chapterTags: ['Principles of Inheritance and Variation', 'Mendelian Genetics'],
    simType: 'punnett',
    defaultParams: { parent1Genotype: 1, parent2Genotype: 1 },
    paramConfig: [
      { key: 'parent1Genotype', label: 'Parent 1 Genotype', unit: '', min: 0, max: 2, step: 1, choices: [
        { value: 0, label: 'tt (short)' }, { value: 1, label: 'Tt (tall, carrier)' }, { value: 2, label: 'TT (tall, pure)' },
      ] },
      { key: 'parent2Genotype', label: 'Parent 2 Genotype', unit: '', min: 0, max: 2, step: 1, choices: [
        { value: 0, label: 'tt (short)' }, { value: 1, label: 'Tt (tall, carrier)' }, { value: 2, label: 'TT (tall, pure)' },
      ] },
    ],
    apparatusIds: ['punnett-chart'],
    purpose: 'To use a Punnett square to predict the genotype and phenotype ratios of offspring from a genetic cross.',
    predictPrompt: 'Two pea plants that are both heterozygous for the tall trait (Tt x Tt) are crossed. What fraction of their offspring is expected to be tall?',
    predictOptions: ['3 out of 4 (75%)', '1 out of 2 (50%)', '1 out of 4 (25%)', 'All of them (100%)'],
    correctPredictIndex: 0,
    keyIdea: 'A dominant allele (T) hides a recessive allele (t) whenever at least one T is present -- only tt shows the recessive trait.',
    keyIdeaVars: ['parent1Genotype', 'parent2Genotype'],
    steps: [
      { number: 1, instruction: 'Set both parents to Tt -- the classic Mendel cross.', paramChanges: { parent1Genotype: 1, parent2Genotype: 1 }, action: 'release' },
      { number: 2, instruction: 'Look at all 4 boxes of the Punnett square.', action: 'observe' },
      { number: 3, instruction: 'Now try crossing Tt with tt instead.', paramChanges: { parent1Genotype: 1, parent2Genotype: 0 }, action: 'observe' },
    ],
    observationPrompts: [
      'In the Tt x Tt cross, how many of the 4 boxes show the recessive tt genotype?',
      'How did the ratio change when you crossed Tt with tt instead of Tt with Tt?',
    ],
    explanation: 'Each parent contributes exactly one allele per gene to each offspring. Laying out every possible combination in a 2x2 grid (one parent\'s two possible alleles across the top, the other\'s down the side) shows all 4 equally likely outcomes. For Tt x Tt, the 4 combinations are TT, Tt, Tt, and tt -- three of the four have at least one T (dominant), so they all look tall, while only the one tt combination shows the recessive short trait. That\'s the classic 3:1 phenotype ratio Mendel discovered.',
    realWorldApplications: [
      'Genetic counselors use Punnett squares to help parents understand the odds of passing on inherited conditions.',
      'Plant and animal breeders use this exact logic to predict and select for desirable traits across generations.',
    ],
    safetyNotes: [],
    extensions: [
      'What genotype ratio would you expect from a TT x tt cross?',
      'Can two tall parents ever have a short offspring? Under what condition?',
    ],
    realLifeNote: 'Gregor Mendel worked all of this out in the 1860s by patiently cross-breeding thousands of pea plants and counting traits by hand -- decades before anyone even knew DNA existed.',
  },
];
