import { PhysicalChemExperiment } from './chemPhysicalTypes';

// Six curated Physical Chemistry Calculators -- see chemPhysicalTypes.ts's
// header for why these are parameterized tools rather than drag-reagent
// experiments, and lib/chemEngine.ts for the verified formulas behind
// every one. Same predict/explore/explain discipline as every other
// curated experiment in this app.
export const CHEM_PHYSICAL_EXPERIMENTS: PhysicalChemExperiment[] = [
  {
    id: 'phys-mole-calculator',
    title: 'Mole Calculator',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Mole Concept and Stoichiometry', 'Some Basic Concepts of Chemistry'],
    simType: 'mole-calculator',
    defaultParams: { substanceIndex: 0, massGrams: 18 },
    paramConfig: [
      {
        key: 'substanceIndex', label: 'Substance', unit: '', min: 0, max: 4, step: 1,
        choices: [
          { value: 0, label: 'Water (H2O)' },
          { value: 1, label: 'Carbon Dioxide (CO2)' },
          { value: 2, label: 'Sodium Chloride (NaCl)' },
          { value: 3, label: 'Oxygen Gas (O2)' },
          { value: 4, label: 'Glucose (C6H12O6)' },
        ],
      },
      { key: 'massGrams', label: 'Mass', unit: 'g', min: 1, max: 200, step: 1 },
    ],
    purpose: 'See how mass, moles, volume (at STP), and number of particles are all just different ways of measuring the exact same amount of substance.',
    predictPrompt: 'How many grams of water (H2O, molar mass 18 g/mol) contain exactly 1 mole of water molecules?',
    predictOptions: ['9 g', '18 g', '36 g', '180 g'],
    correctPredictIndex: 1,
    keyIdea: 'One mole of ANY substance always contains 6.022 x 10^23 particles (Avogadro\'s Number) and, if it\'s a gas, occupies 22.4 litres at STP -- only the MASS of one mole changes from substance to substance, based on its molar mass.',
    steps: [
      { number: 1, instruction: 'With water (molar mass 18) and 18g, check that the tool reports exactly 1 mole, 22.4L, and 6.022x10^23 molecules.', paramChanges: { substanceIndex: 0, massGrams: 18 } },
      { number: 2, instruction: 'Switch to Sodium Chloride (molar mass 58.5) and keep the mass the same -- notice moles goes DOWN even though mass didn\'t change, since each formula unit is heavier.', paramChanges: { substanceIndex: 2, massGrams: 18 } },
      { number: 3, instruction: 'Try Glucose at 90g -- can you predict the mole count before checking?', paramChanges: { substanceIndex: 4, massGrams: 90 } },
    ],
    observationPrompts: ['How does changing the substance (with mass held constant) change the number of moles?', 'Why do you think volume at STP only makes sense for a gas, not a solid like NaCl or glucose?'],
    explanation: 'A mole is just a counting unit, like a "dozen" -- but instead of 12, it counts out 6.022x10^23 of something. Since heavier particles weigh more per mole, the SAME mass of a heavier substance always contains FEWER moles (and fewer particles) than a lighter one.',
    realWorldApplications: ['Pharmacists calculate exact drug doses in moles to get the right number of active molecules per pill', 'Industrial chemists scale reactions from a lab beaker to a factory vat using mole ratios', 'Nutrition labels report some quantities in moles-equivalent units for precise dietary tracking'],
    extensions: ['What mass of oxygen gas (O2, molar mass 32) would give the same number of molecules as 18g of water?'],
    realLifeNote: 'The mole is one of the seven fundamental SI base units (like the metre or the second) -- it was formally defined by fixing Avogadro\'s Number as an exact constant in 2019, the same way the metre is now defined by the speed of light.',
  },
  {
    id: 'phys-gas-laws',
    title: 'Gas Laws Simulator',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Study of Gas Laws', 'States of Matter: Gases and Liquids'],
    simType: 'gas-laws',
    defaultParams: { pressure1: 1, volume1: 10, temperature1C: 27, pressure2: 1, temperature2C: 27 },
    paramConfig: [
      { key: 'pressure2', label: 'New Pressure', unit: 'atm', min: 0.5, max: 5, step: 0.5 },
      { key: 'temperature2C', label: 'New Temperature', unit: '°C', min: -20, max: 300, step: 10 },
    ],
    purpose: 'Watch a gas\'s volume respond exactly as the Combined Gas Law predicts when you change its pressure and temperature.',
    predictPrompt: 'If you double the pressure on a gas while keeping its temperature constant, what happens to its volume?',
    predictOptions: ['It doubles', 'It halves', 'It stays the same', 'It quadruples'],
    correctPredictIndex: 1,
    keyIdea: 'The Combined Gas Law, P1V1/T1 = P2V2/T2, governs any fixed amount of gas -- Boyle\'s Law (pressure and volume, temperature fixed) and Charles\'s Law (volume and temperature, pressure fixed) are just this same law with one variable held still.',
    steps: [
      { number: 1, instruction: 'Start at 1 atm, 10L, 27°C. Change ONLY the pressure to 2 atm (leave temperature at 27°C) -- this isolates Boyle\'s Law.', paramChanges: { pressure2: 2, temperature2C: 27 } },
      { number: 2, instruction: 'Reset the pressure back to 1 atm, then change ONLY the temperature to 327°C -- this isolates Charles\'s Law.', paramChanges: { pressure2: 1, temperature2C: 327 } },
      { number: 3, instruction: 'Now change BOTH sliders at once and watch the combined law handle it correctly either way.' },
    ],
    observationPrompts: ['When you doubled the pressure alone, exactly how did the volume change?', 'When you raised the temperature alone, did the volume increase or decrease -- and does that match what you\'d expect from a gas expanding when heated?'],
    explanation: 'Pressure and volume are inversely related (squeeze a gas harder, it takes up less space) while volume and temperature (in Kelvin) are directly related (heat a gas, it expands) -- the combined law is just both relationships true at the same time, for any fixed amount of gas.',
    realWorldApplications: ['A car tyre\'s pressure rises on a hot day purely from the temperature increase, with no air added', 'Scuba divers must account for gas laws -- air in their lungs expands as they rise and pressure drops, which is why holding your breath while ascending is dangerous', 'Weather balloons are only partially inflated at launch because the gas inside expands dramatically as atmospheric pressure drops at altitude'],
    extensions: ['At what new temperature would the gas return to exactly its original 10L volume, if the pressure is set to 2 atm?'],
    realLifeNote: 'These laws were worked out by three separate scientists over more than a century -- Robert Boyle (1662), Jacques Charles (1780s, though published later by Gay-Lussac) -- before anyone understood WHY they were true. The kinetic theory of gases, explaining gas behaviour in terms of moving particles, wasn\'t developed until the mid-1800s.',
  },
  {
    id: 'phys-ph-calculator',
    title: 'pH Calculator',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Study of Acids, Bases and Salts', 'Chemical Changes and Reactions'],
    simType: 'ph-calculator',
    defaultParams: { pH: 7 },
    paramConfig: [
      { key: 'pH', label: 'pH', unit: '', min: 0, max: 14, step: 0.1 },
    ],
    purpose: 'See exactly how the hydrogen ion concentration behind every pH value is calculated, not just looked up on a color chart.',
    predictPrompt: 'Pure water has a hydrogen ion concentration of 10^-7 mol/L. What is its pH?',
    predictOptions: ['1', '7', '14', '0'],
    correctPredictIndex: 1,
    keyIdea: 'pH = -log10[H+] -- it\'s a logarithmic (not linear) scale, which is why each whole-number drop in pH means a TEN TIMES higher hydrogen ion concentration, not just a little more.',
    steps: [
      { number: 1, instruction: 'Start at pH 7 (neutral) -- check that [H+] reads exactly 0.0000001 mol/L (10^-7).' },
      { number: 2, instruction: 'Move to pH 4 -- notice [H+] is now 1000 times higher than at pH 7, not just 3 units "more".', paramChanges: { pH: 4 } },
      { number: 3, instruction: 'Move all the way to pH 1 (strongly acidic) and then to pH 13 (strongly alkaline) -- watch pOH move in the opposite direction each time.' },
    ],
    observationPrompts: ['Going from pH 7 to pH 4 is a drop of 3 -- by what FACTOR did [H+] actually increase?', 'What do you notice about the relationship between pH and pOH at every point?'],
    explanation: 'Because pH is a LOG scale, a "small" change in pH number represents a huge change in actual acid strength -- pH 4 has 1,000 times more free hydrogen ions than pH 7. pOH = 14 - pH always holds at 25°C, since [H+][OH-] is a constant (10^-14) in water at that temperature.',
    realWorldApplications: ['Swimming pool pH is kept within a narrow band (~7.2-7.6) because even a small pH drift makes chlorine far less effective at killing germs', 'Blood pH is tightly regulated between 7.35-7.45 -- a shift of even 0.5 in either direction can be life-threatening', 'Soil pH determines which nutrients are actually available to plant roots, which is why farmers test and adjust it'],
    extensions: ['What is [H+] at pH 0? How does that compare to pH 7?'],
    realLifeNote: 'The pH scale was invented in 1909 by Danish chemist Søren Sørensen while working on quality control at the Carlsberg brewery -- he needed a practical, precise way to describe acidity that was faster than existing methods.',
  },
  {
    id: 'phys-equilibrium',
    title: 'Equilibrium Shift Predictor',
    gradeBand: 'plusTwo',
    board: 'both',
    chapterTags: ['Equilibrium'],
    simType: 'equilibrium',
    defaultParams: { n2: 1, h2: 1, nh3: 1, stressIndex: 0 },
    paramConfig: [
      { key: 'n2', label: '[N2] concentration', unit: 'mol/L', min: 0.1, max: 5, step: 0.1 },
      { key: 'h2', label: '[H2] concentration', unit: 'mol/L', min: 0.1, max: 5, step: 0.1 },
      { key: 'nh3', label: '[NH3] concentration', unit: 'mol/L', min: 0.1, max: 5, step: 0.1 },
      {
        key: 'stressIndex', label: 'Apply a stress', unit: '', min: 0, max: 7, step: 1,
        choices: [
          { value: 0, label: 'None' },
          { value: 1, label: 'Add N2' },
          { value: 2, label: 'Add H2' },
          { value: 3, label: 'Remove NH3' },
          { value: 4, label: 'Add NH3' },
          { value: 5, label: 'Increase Pressure' },
          { value: 6, label: 'Decrease Pressure' },
          { value: 7, label: 'Increase Temperature' },
        ],
      },
    ],
    purpose: 'Use the real Haber Process reaction (N2 + 3H2 <=> 2NH3) to see Le Chatelier\'s Principle predict which way equilibrium shifts under different stresses.',
    predictPrompt: 'In the Haber process (N2 + 3H2 <=> 2NH3), if you increase the pressure on the system, which direction does equilibrium shift?',
    predictOptions: ['Toward more NH3 (forward)', 'Toward more N2 and H2 (reverse)', 'It doesn\'t shift at all'],
    correctPredictIndex: 0,
    keyIdea: 'Le Chatelier\'s Principle: if a system at equilibrium is disturbed, it shifts in whichever direction PARTLY undoes that disturbance -- add more reactant, it shifts to consume it; raise pressure, it shifts toward the side with fewer gas molecules.',
    steps: [
      { number: 1, instruction: 'With equal concentrations of N2, H2, and NH3, check the Kc value the tool computes.' },
      { number: 2, instruction: 'Apply the "Add N2" stress and watch which direction the predictor says the system shifts.', paramChanges: { stressIndex: 1 } },
      { number: 3, instruction: 'Try "Increase Temperature" -- since the forward reaction is exothermic (releases heat), predict the direction before checking.', paramChanges: { stressIndex: 7 } },
    ],
    observationPrompts: ['Why does adding more N2 push the reaction forward, toward more NH3?', 'Why does INCREASING temperature push an EXOTHERMIC reaction backward?'],
    explanation: 'Increasing pressure squeezes a gas mixture, and the system shifts toward whichever side has FEWER gas molecules to relieve that pressure -- 4 moles of gas (1 N2 + 3 H2) become just 2 moles of NH3, so higher pressure favours the forward (product) direction. Heat acts like a "product" of an exothermic reaction, so adding more heat pushes the system to consume less of it, shifting the reaction backward.',
    realWorldApplications: ['The real industrial Haber Process (making ammonia for fertiliser) is run at HIGH pressure for exactly this reason -- to favour the forward, product-making direction', 'Carbonated drinks stay fizzy under pressure (CO2 dissolved) and fizz out once opened, releasing pressure and shifting equilibrium toward gas escaping', 'Your blood\'s oxygen-haemoglobin equilibrium shifts based on oxygen concentration in your lungs vs your tissues, following the same underlying principle'],
    extensions: ['Why might industrial ammonia production NOT simply use the highest pressure and lowest temperature possible, even though both favour more product?'],
    realLifeNote: 'The real Haber Process is one of the most consequential reactions in human history -- it lets us make fertiliser from air (nitrogen) at industrial scale, and is estimated to support the food supply for roughly half the world\'s population today.',
  },
  {
    id: 'phys-kinetics',
    title: 'Reaction Rate Grapher',
    gradeBand: 'plusTwo',
    board: 'both',
    chapterTags: ['Chemical Kinetics'],
    simType: 'kinetics',
    defaultParams: { initialConcentration: 1, rateConstantK: 0.1, orderIndex: 1 },
    paramConfig: [
      { key: 'initialConcentration', label: 'Initial Concentration', unit: 'mol/L', min: 0.2, max: 2, step: 0.1 },
      { key: 'rateConstantK', label: 'Rate Constant (k)', unit: '', min: 0.01, max: 0.5, step: 0.01 },
      {
        key: 'orderIndex', label: 'Reaction Order', unit: '', min: 0, max: 1, step: 1,
        choices: [
          { value: 0, label: 'Zero Order' },
          { value: 1, label: 'First Order' },
        ],
      },
    ],
    purpose: 'Watch how a reactant\'s concentration actually falls over time -- a straight line for zero order, a curve for first order -- and see why "half-life" only makes clean sense for one of them.',
    predictPrompt: 'In a first-order reaction with a half-life of 10 minutes, how much of the original reactant remains after 20 minutes (two half-lives)?',
    predictOptions: ['50%', '25%', '12.5%', '0%'],
    correctPredictIndex: 1,
    keyIdea: 'A zero-order reaction\'s concentration falls at a constant RATE (a straight line) -- a first-order reaction\'s concentration falls by a constant FRACTION each time interval (an exponential curve), which is exactly why first-order half-life is always the same number regardless of starting concentration.',
    steps: [
      { number: 1, instruction: 'With First Order selected, watch the curve -- notice it drops fast at first, then levels off, never quite reaching zero.' },
      { number: 2, instruction: 'Switch to Zero Order with the same k and initial concentration -- compare the shape of the line.', paramChanges: { orderIndex: 0 } },
      { number: 3, instruction: 'Back on First Order, double the rate constant k -- what happens to how quickly the curve drops?', paramChanges: { orderIndex: 1, rateConstantK: 0.2 } },
    ],
    observationPrompts: ['Which order\'s graph is a straight line, and which is a curve?', 'For the zero-order line, at what time does concentration hit exactly zero -- and does that match a simple calculation?'],
    explanation: 'A zero-order reaction proceeds at a constant rate regardless of how much reactant is left (common in reactions limited by something else, like available catalyst surface) -- so concentration drops in a straight line and hits zero at a predictable, finite time. A first-order reaction\'s rate depends on how much reactant remains, so as concentration drops, the rate drops too -- producing a curve that technically never reaches exactly zero.',
    realWorldApplications: ['Radioactive decay is always first-order, which is why radiometric dating and medical isotope dosing rely on a fixed half-life', 'Drug metabolism in the body is often first-order, which is why doctors calculate dosing intervals based on a drug\'s known half-life', 'Enzyme-catalysed reactions can appear zero-order when the enzyme is fully saturated with substrate'],
    extensions: ['For a zero-order reaction with initial concentration 1.0 mol/L and k=0.1, at exactly what time does the concentration reach zero?'],
    realLifeNote: 'Carbon-14 dating relies entirely on the fact that radioactive decay is first-order with an exact, unchanging half-life (5,730 years for Carbon-14) -- regardless of how much carbon-14 you start with, it always takes the same amount of time for half of it to decay.',
  },
  {
    id: 'phys-electrochemistry',
    title: 'Electrochemical Cell EMF Calculator',
    gradeBand: 'plusTwo',
    board: 'both',
    chapterTags: ['Electrochemistry'],
    simType: 'electrochemistry',
    defaultParams: { metal1Index: 6, metal2Index: 9 },
    paramConfig: [
      {
        key: 'metal1Index', label: 'First Electrode', unit: '', min: 0, max: 12, step: 1,
        choices: [
          { value: 0, label: 'Lithium (Li)' }, { value: 1, label: 'Potassium (K)' }, { value: 2, label: 'Calcium (Ca)' },
          { value: 3, label: 'Sodium (Na)' }, { value: 4, label: 'Magnesium (Mg)' }, { value: 5, label: 'Aluminium (Al)' },
          { value: 6, label: 'Zinc (Zn)' }, { value: 7, label: 'Iron (Fe)' }, { value: 8, label: 'Lead (Pb)' },
          { value: 9, label: 'Copper (Cu)' }, { value: 10, label: 'Silver (Ag)' }, { value: 11, label: 'Gold (Au)' },
          { value: 12, label: 'Hydrogen (reference)' },
        ],
      },
      {
        key: 'metal2Index', label: 'Second Electrode', unit: '', min: 0, max: 12, step: 1,
        choices: [
          { value: 0, label: 'Lithium (Li)' }, { value: 1, label: 'Potassium (K)' }, { value: 2, label: 'Calcium (Ca)' },
          { value: 3, label: 'Sodium (Na)' }, { value: 4, label: 'Magnesium (Mg)' }, { value: 5, label: 'Aluminium (Al)' },
          { value: 6, label: 'Zinc (Zn)' }, { value: 7, label: 'Iron (Fe)' }, { value: 8, label: 'Lead (Pb)' },
          { value: 9, label: 'Copper (Cu)' }, { value: 10, label: 'Silver (Ag)' }, { value: 11, label: 'Gold (Au)' },
          { value: 12, label: 'Hydrogen (reference)' },
        ],
      },
    ],
    purpose: 'Pick any two metal electrodes and calculate the exact voltage a real electrochemical cell built from them would produce.',
    predictPrompt: 'In a cell made from zinc and copper electrodes, which metal is oxidised (loses electrons) at the anode?',
    predictOptions: ['Zinc', 'Copper', 'Both equally', 'Neither'],
    correctPredictIndex: 0,
    keyIdea: 'E°cell = E°cathode - E°anode -- the electrode with the HIGHER (less negative) standard reduction potential is always the cathode (reduction happens there); the other is the anode, where oxidation happens.',
    steps: [
      { number: 1, instruction: 'With Zinc and Copper selected (the classic Daniell cell), check the calculated EMF against the real, well-known value of 1.10V.' },
      { number: 2, instruction: 'Swap in Silver instead of Copper -- notice the EMF changes, but Zinc is still the anode.', paramChanges: { metal1Index: 6, metal2Index: 10 } },
      { number: 3, instruction: 'Try two metals close together in the table, like Iron and Lead -- notice how much smaller the EMF is.', paramChanges: { metal1Index: 7, metal2Index: 8 } },
    ],
    observationPrompts: ['Which of your two chosen metals ended up as the cathode, and which as the anode?', 'What pattern do you notice between how far apart two metals are in the table and how large the resulting EMF is?'],
    explanation: 'Standard reduction potential measures how strongly a metal ion "wants" to gain electrons and become solid metal. The metal with the higher potential wins that competition and gets reduced (cathode); the other is forced to give up its electrons instead (oxidised, at the anode). The bigger the gap between the two potentials, the bigger the resulting voltage.',
    realWorldApplications: ['Every battery -- from a AA cell to a car battery to a phone battery -- is built on exactly this same electrode-potential-difference principle', 'Galvanised (zinc-coated) steel resists rusting because zinc, being more easily oxidised than iron, sacrifices itself first -- "sacrificial protection"', 'Mixing dissimilar metals in plumbing or ship hulls can cause serious galvanic corrosion, which is why engineers deliberately choose compatible metals or add sacrificial anodes'],
    extensions: ['Which single metal from the list would make the LARGEST possible EMF when paired with Gold?'],
    realLifeNote: 'Alessandro Volta built the first true battery (the "voltaic pile") in 1800 using alternating zinc and copper discs -- the exact same two metals default-selected in this tool -- making it one of the oldest continuously-used electrode pairs in the history of electrochemistry.',
  },
];
