import { DeepDiveContent } from './deepDive';

// Chemistry's first wave of Deep Dives -- direct response to user feedback
// using Equipment Studio as the concrete example: click an item and get a
// real hold-and-rotate object view plus everything genuinely worth knowing
// about it, not just the one-line curriculum card. Six equipment items (the
// ones with real, license-verified photos so far -- see
// apps/web/public/equipment/CREDITS.md), four reagents, and five recognizable
// periodic elements, all hand-researched and verified, never generated.
export const CHEM_EQUIPMENT_DEEP_DIVES: DeepDiveContent[] = [
  {
    id: 'chem-equip-beaker',
    lab: 'chemistry',
    title: 'Beaker',
    tagline: 'The everyday container of the chemistry lab -- for mixing and heating, not precise measuring.',
    overview: 'A beaker is a simple cylindrical glass container used for mixing, heating, and holding liquids. Its wide mouth and printed spout make it easy to pour, but the volume markings on its side are only rough guides, not precise measurements.',
    deepFacts: [
      'Modern beakers are usually made of borosilicate glass (sold under brand names like Pyrex or Duran), which resists cracking from sudden temperature changes -- an ordinary drinking glass would likely shatter if heated the same way.',
      'The small pouring spout is called a "beak," which is very likely where the word "beaker" itself comes from.',
      'The volume graduations printed on a beaker are typically only accurate to within about 5-10% -- its wide, straight-sided shape makes small reading errors translate into large volume errors, which is why a graduated cylinder, pipette, or burette is used whenever real precision matters.',
      'The common low, spouted shape used in schools worldwide is often called a "Griffin beaker," after 19th-century British scientific instrument maker John Joseph Griffin, who helped standardize it.',
    ],
    realWorldApplications: [
      'Mixing and dissolving reagents in school and research labs',
      'Holding a reaction mixture while it\'s heated on a hot plate or over a Bunsen burner',
      'Industrial-scale versions (as large mixing/process vessels) in chemical manufacturing',
      'Measuring approximate liquid volumes in food and pharmaceutical prep, where exact precision isn\'t required',
    ],
    commonMisconceptions: [
      '"The lines on a beaker are precise enough for an exact experiment" -- they\'re only approximate; real quantitative work uses a measuring cylinder, pipette, or burette instead.',
    ],
    safetyNotes: 'Only heat-rated glass (borosilicate) beakers should ever be placed directly over a flame -- plastic beakers and ordinary glass can melt, crack, or shatter.',
    relatedIds: ['chem-equip-conical-flask', 'chem-equip-measuring-cylinder'],
    visualType: 'rotate-3d',
    imageSrc: '/equipment/beaker.jpg',
    imageAlt: 'A 1000 mL Pyrex glass laboratory beaker with volume graduations',
    credit: { author: 'Abdsomod (Wikimedia Commons)', license: 'CC0 1.0', url: 'https://commons.wikimedia.org/wiki/File:Beaker_01.jpg' },
  },
  {
    id: 'chem-equip-burette',
    lab: 'chemistry',
    title: 'Burette',
    tagline: 'The most precise piece of glassware in a school lab -- built for exact, drop-by-drop measurement.',
    overview: 'A burette is a long graduated tube with a tap (stopcock) at the bottom, used to add a precise, measured volume of liquid drop by drop. It\'s the key tool in titration, where the exact volume of one solution needed to react with another has to be known accurately.',
    deepFacts: [
      'A burette reads top-to-bottom -- 0 mL is at the TOP and the numbers increase going down, the opposite of how a measuring cylinder is usually read, which trips up a lot of students the first time.',
      'Standard burettes are graduated in 0.1 mL divisions and are read to the nearest 0.05 mL by estimating between the marks -- among the most precise volume-measuring glassware used in a school lab.',
      'The correct reading is taken from the BOTTOM of the meniscus (the curved liquid surface) at eye level -- reading it from an angle above or below causes a real measurement error called parallax error.',
      'The tap can be an old-style glass-on-glass stopcock (needs a thin film of grease to turn smoothly without seizing) or a modern PTFE plastic valve, which needs no grease at all.',
    ],
    history: 'Volumetric analysis (measuring exact reacting volumes) became a serious quantitative technique in chemistry through the early-to-mid 1800s. The burette was refined for this work by chemists including Gay-Lussac, and later Karl Friedrich Mohr, who is credited with adding the now-standard glass stopcock design still recognizable in burettes today.',
    realWorldApplications: [
      'Titration in school and college chemistry labs',
      'Quality control in pharmaceutical manufacturing, checking a drug batch\'s exact acid or base content',
      'Water treatment plants testing chlorine levels or water hardness',
      'Winemaking and food labs testing acidity levels',
    ],
    commonMisconceptions: [
      '"A titration must always start at exactly 0.00 mL" -- it doesn\'t; what matters is recording the exact starting reading and subtracting it from the final reading to get the volume actually USED.',
    ],
    safetyNotes: 'Never fill or draw liquid up by mouth -- always pour carefully from above or use a funnel, and secure the burette firmly in a retort stand clamp before use.',
    relatedIds: ['chem-equip-conical-flask', 'chem-equip-measuring-cylinder'],
    visualType: 'rotate-3d',
    imageSrc: '/equipment/burette.jpg',
    imageAlt: 'A 50 mL glass burette with a red-and-white stopcock, held upright by hand',
    credit: { author: 'Gemsgy (Wikimedia Commons)', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:50_mL_Buret_whole.jpg' },
    playgroundType: 'burette-reading',
  },
  {
    id: 'chem-equip-bunsen-burner',
    lab: 'chemistry',
    title: 'Bunsen Burner',
    tagline: 'A controllable, adjustable gas flame -- the workhorse heat source of the chemistry lab.',
    overview: 'A Bunsen burner is a gas burner used to heat substances, with an adjustable air hole that controls the flame\'s temperature and character. It should always be used with the flame adjusted correctly and never left unattended.',
    deepFacts: [
      'It\'s named after German chemist Robert Bunsen, but he didn\'t design it alone -- his university\'s lab mechanic, Peter Desaga, built and refined the actual burner in 1855, improving on an earlier design by Michael Faraday.',
      'The air hole (collar) at the base controls how much air premixes with the gas: fully open gives a hot, roaring, almost invisible BLUE flame (complete combustion); closed gives a cooler, flickering, sooty YELLOW "safety flame" (incomplete combustion), used only when the burner isn\'t actively heating something.',
      'The hottest part of the flame is just above the tip of the pale blue inner cone, not at the very top of the visible flame.',
      'Before this design, chemists mostly relied on oil lamps or plain gas flames that burned less cleanly and couldn\'t be controlled nearly as precisely -- the premixed-air design was a genuine step forward for lab heating.',
    ],
    realWorldApplications: [
      'Heating and sterilizing equipment in school and university chemistry labs',
      'Sterilizing inoculating loops in microbiology between samples',
      'Glassblowing and small-scale glasswork',
      'Similar premixed-gas designs are used in some soldering and brazing torches',
    ],
    commonMisconceptions: [
      '"The bigger, brighter yellow flame is hotter" -- it\'s actually the opposite; the less visible blue flame is hotter, while the yellow flame only glows from tiny soot particles and burns cooler.',
    ],
    safetyNotes: 'Always light the match or striker BEFORE turning on the gas. Keep the yellow "safety flame" on whenever the burner isn\'t actively heating something, since it\'s easier to see. Tie back loose hair and sleeves, and never leave a lit burner unattended.',
    relatedIds: ['chem-equip-test-tube', 'chem-equip-beaker'],
    visualType: 'rotate-3d',
    imageSrc: '/equipment/bunsen-burner.jpg',
    imageAlt: 'A Bunsen burner with a blue metal base and adjustable air collar',
    credit: { author: 'Jason Woodhead (via Flickr, Wikimedia Commons)', license: 'CC BY 2.0', url: 'https://commons.wikimedia.org/wiki/File:Bunsen_burner_(5590104883).jpg' },
  },
  {
    id: 'chem-equip-conical-flask',
    lab: 'chemistry',
    title: 'Conical (Erlenmeyer) Flask',
    tagline: 'A narrow-necked flask built for vigorous swirling without spilling -- the titration flask.',
    overview: 'A conical flask has a narrow neck and a wide, flat conical base, letting it be swirled vigorously without splashing liquid out. It\'s the standard flask used to hold the solution being tested in a titration.',
    deepFacts: [
      'It\'s named after German chemist Emil Erlenmeyer, who designed this shape in 1860 specifically to improve on the plain straight-sided flasks chemists used before.',
      'The narrowing conical shape lets a chemist swirl the flask hard to mix its contents without splashing any liquid out the top -- exactly why it\'s chosen for titration, where the flask needs constant swirling while liquid drips in from a burette.',
      'Some conical flasks have a ground-glass joint at the neck, letting a stopper or another piece of glassware attach with an airtight seal -- useful for reactions that need to be kept sealed from outside air.',
    ],
    history: 'Emil Erlenmeyer introduced the flask that now carries his name in 1860, and it was quickly adopted across chemistry because its shape solved a real, practical swirling-and-splashing problem that straight-sided flasks and beakers both had.',
    realWorldApplications: [
      'Holding the solution being tested in a titration',
      'Growing bacterial or yeast cultures, since the wide base allows good aeration when swirled on a shaker',
      'Recrystallization, a common purification technique in chemistry',
      'Brewing and fermentation experiments',
    ],
    commonMisconceptions: [
      '"A conical flask and a beaker do the same job" -- both hold liquid, but only the conical flask\'s narrow neck resists splashing during vigorous swirling, which is specifically why it\'s used for titration instead of a beaker.',
    ],
    safetyNotes: 'Ordinary glass conical flasks can crack from rapid heating -- only heat-rated borosilicate glass ones should go directly over a flame.',
    relatedIds: ['chem-equip-burette', 'chem-equip-beaker'],
    visualType: 'rotate-3d',
    imageSrc: '/equipment/conical-flask.jpg',
    imageAlt: 'A 250 mL Pyrex glass conical (Erlenmeyer) flask with volume graduations',
    credit: { author: 'Pilarbini (Wikimedia Commons)', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:250_mL_Erlenmeyer_flask.jpg' },
  },
  {
    id: 'chem-equip-measuring-cylinder',
    lab: 'chemistry',
    title: 'Measuring Cylinder',
    tagline: 'A tall, narrow tube built to measure liquid volume far more accurately than a beaker.',
    overview: 'A measuring cylinder is a tall, graduated container used to measure a specific volume of liquid accurately. Its narrow, uniform shape makes it far more precise than a beaker, though still less precise than a pipette or burette.',
    deepFacts: [
      'Its narrow, uniform diameter means the same small error in reading the liquid height translates into a much smaller volume error than it would in a wide beaker -- which is exactly why it measures more accurately.',
      'Like a burette, a measuring cylinder is read from the BOTTOM of the meniscus (the curved liquid surface) at eye level, not from the top of the curve.',
      'The wide hexagonal or round base isn\'t just styling -- it makes a tall, narrow cylinder far more stable and much harder to tip over.',
      'The measuring cylinder as a distinct piece of labware is credited to French chemist Louis-Bernard Guyton de Morveau around 1784, during the period when chemistry was shifting from a mostly qualitative science into a measurement-based, quantitative one.',
    ],
    realWorldApplications: [
      'Measuring reagent volumes accurately in school and research labs',
      'Dosing liquid medicines and chemicals in industry',
      'Water quality testing',
      'A kitchen measuring cup is a much less precise, everyday cousin of the same basic idea',
    ],
    commonMisconceptions: [
      '"A bigger cylinder is always more precise" -- actually a smaller cylinder (like 10 mL) measuring a small volume is MORE precise than reading that same small volume off a large 500 mL cylinder, since the same absolute reading error is a much bigger fraction of a small total volume.',
    ],
    relatedIds: ['chem-equip-burette', 'chem-equip-beaker'],
    visualType: 'rotate-3d',
    imageSrc: '/equipment/measuring-cylinder.jpg',
    imageAlt: 'A 100 mL glass graduated measuring cylinder with a hexagonal base',
    credit: { author: 'Parispary (Wikimedia Commons)', license: 'CC BY-SA 4.0', url: 'https://commons.wikimedia.org/wiki/File:A_graduated_cylinder.jpg' },
  },
  {
    id: 'chem-equip-test-tube',
    lab: 'chemistry',
    title: 'Test Tube',
    tagline: 'A small glass tube for holding, mixing, and carefully heating tiny amounts of chemicals.',
    overview: 'A test tube is a small glass tube used to hold, mix, or heat small quantities of chemicals -- one of the most recognizable pieces of equipment in any chemistry lab.',
    deepFacts: [
      'Test tubes are traditionally made of thin borosilicate glass specifically so they can be heated directly over a flame without cracking -- ordinary glass would likely shatter from the rapid, uneven heating.',
      'When heating liquid in a test tube, it should always be tilted and pointed away from yourself and everyone nearby, and moved gently through the flame rather than held still, to avoid "bumping" -- a sudden, violent burst of superheated boiling that can eject hot liquid out of the tube.',
      'Test tube racks are often built with two different kinds of holes: shallow dips that let a wet, just-washed tube rest upside down to drain and dry, and deeper holes that hold a tube upright.',
      'Larger, thicker-walled "boiling tubes" are essentially bigger, more heat-resistant test tubes designed specifically for direct flame heating.',
    ],
    realWorldApplications: [
      'Qualitative chemical tests, like flame tests and precipitation reactions',
      'Blood sample collection tubes in medicine are a close, specialized cousin',
      'Microbiology culture tubes for growing small samples',
      'Small-scale reaction screening in chemistry research',
    ],
    commonMisconceptions: [
      '"Any glass tube shaped like a test tube is safe to heat" -- only heat-rated borosilicate glass tubes are; ordinary glass ones (sometimes used just for storage) can crack or shatter if heated directly.',
    ],
    safetyNotes: 'Point the open end away from people, wear safety goggles, use a test tube holder rather than fingers once it\'s hot, and never look straight down into a tube that\'s being heated.',
    relatedIds: ['chem-equip-bunsen-burner', 'chem-equip-beaker'],
    visualType: 'rotate-3d',
    imageSrc: '/equipment/test-tube.jpg',
    imageAlt: 'Six glass test tubes standing in a white plastic test tube rack',
    credit: { author: 'Abdsomod (Wikimedia Commons)', license: 'CC0 1.0', url: 'https://commons.wikimedia.org/wiki/File:Test_tube_and_test_tube_rake.jpg' },
  },
];

export const CHEM_REAGENT_DEEP_DIVES: DeepDiveContent[] = [
  {
    id: 'chem-reagent-copper-sulphate-solution',
    lab: 'chemistry',
    title: 'Copper Sulphate Solution',
    tagline: 'A pale blue solution whose color comes from a water-copper complex, not the copper alone.',
    overview: 'Copper sulphate solution is CuSO4 dissolved in water, giving a distinctive pale blue color used throughout school chemistry for displacement reactions and water-detection tests.',
    deepFacts: [
      'The blue color comes from the copper(II) ion bonded directly to six surrounding water molecules -- it\'s specifically that water-copper complex that produces the blue, not copper on its own. Dry (anhydrous) copper sulfate is actually white.',
      'This color change -- white anhydrous CuSO4 turning blue the instant water touches it -- is a classic, very sensitive chemical test for detecting the presence of water in an otherwise "dry" liquid or solid.',
      'Historically, copper sulfate is also known as "blue vitriol."',
      'Dipping an iron nail into blue copper sulfate solution makes the iron slowly dissolve while copper metal deposits out as a pinkish-brown coating on the nail, and the solution itself fades from blue toward pale green -- a classic, visually dramatic demonstration of a more-reactive metal displacing a less-reactive one from its salt solution.',
    ],
    realWorldApplications: [
      'A regulated fungicide and algicide in agriculture and swimming pools',
      'Electroplating baths in industry',
      'Historically used as a mordant (fixative) in fabric dyeing',
      'A component of classic sugar-detection tests used in biology and chemistry, like Fehling\'s and Benedict\'s solution',
    ],
    commonMisconceptions: [
      '"It\'s safe to touch freely since it just looks like colored water" -- copper sulfate is toxic in more than very small quantities and is an irritant even at typical lab concentrations.',
    ],
    safetyNotes: 'Mildly irritant -- avoid skin and eye contact, and wash hands thoroughly after handling.',
    relatedIds: ['chem-equip-beaker'],
    visualType: 'none',
  },
  {
    id: 'chem-reagent-dilute-hcl',
    lab: 'chemistry',
    title: 'Dilute Hydrochloric Acid',
    tagline: 'A genuine strong acid -- and the very same compound your own stomach uses to digest food.',
    overview: 'Dilute hydrochloric acid (HCl) is one of the most commonly used acids in a school lab, valued for reliably reacting with reactive metals and carbonates in clear, easy-to-observe ways.',
    deepFacts: [
      'HCl gas is intensely soluble in water -- hydrochloric acid IS essentially that gas dissolved in water, not a liquid acid that exists on its own.',
      'Your own stomach produces hydrochloric acid naturally (gastric acid, roughly pH 1.5 to 3.5) to help digest food and kill ingested bacteria -- the same compound as the lab bottle, just at a very different, tightly-controlled concentration.',
      'HCl is called a "strong acid" because it almost completely breaks apart (dissociates) into H+ and Cl- ions in water, unlike a "weak acid" like vinegar (acetic acid), which only partially dissociates. Strength describes how COMPLETELY an acid dissociates, not how concentrated or dangerous a particular sample is.',
      'Reacting dilute HCl with a reactive metal like zinc or magnesium produces hydrogen gas -- which is why the classic "pop test" (a lit splint makes a small squeaky pop at the mouth of the test tube) is the standard confirmatory test for hydrogen.',
    ],
    realWorldApplications: [
      'Steel pickling -- removing rust and scale before further processing',
      'pH adjustment in swimming pools and water treatment plants',
      'Food processing, including producing corn syrup and gelatin',
      'Industrial and masonry cleaning, sold under the older name "muriatic acid"',
    ],
    commonMisconceptions: [
      '"Concentrated acid is chemically stronger than dilute acid" -- concentration (how much is dissolved) and strength (how completely it dissociates) are two separate properties. HCl is a strong acid whether it\'s dilute or concentrated; dilute HCl is simply less concentrated, not a "weaker" type of acid.',
    ],
    safetyNotes: 'Corrosive at higher concentrations -- always use the dilute, lab-safe strength and wear goggles for any real hands-on version.',
    relatedIds: ['chem-equip-test-tube'],
    visualType: 'none',
  },
  {
    id: 'chem-reagent-universal-indicator',
    lab: 'chemistry',
    title: 'Universal Indicator',
    tagline: 'Not one dye but a carefully blended cocktail, tuned to paint the whole pH scale as a rainbow.',
    overview: 'Universal indicator is a mixed pH indicator that turns a different color across the full 0-14 pH range, making it possible to estimate a solution\'s acidity or alkalinity by eye.',
    deepFacts: [
      'It isn\'t a single dye -- it\'s a carefully blended mixture of several different indicator dyes, each changing color at a different pH, combined so together they produce a smooth, continuous spectrum of color rather than one abrupt change.',
      'Because it shows a whole spectrum instead of a sharp single-point change, universal indicator is excellent for ESTIMATING pH quickly, but a precise numerical reading needs an electronic pH meter instead.',
      'Universal indicator paper (a dye mixture dried onto strips) and universal indicator solution (added drop by drop to a liquid) use the same underlying blend of dyes, just in different, more or less portable forms.',
    ],
    realWorldApplications: [
      'Quick classroom or field testing of soil, water, or household substances',
      'Simplified versions are used in swimming pool and aquarium test kits',
      'Science demonstrations showing the full acid-neutral-alkaline spectrum at once',
    ],
    commonMisconceptions: [
      '"Universal indicator gives an exact pH reading" -- it gives a useful visual estimate, generally accurate to only about half a pH unit by eye, not a precise decimal value.',
    ],
    relatedIds: ['chem-equip-test-tube'],
    visualType: 'none',
  },
  {
    id: 'chem-reagent-marble-chips',
    lab: 'chemistry',
    title: 'Marble Chips',
    tagline: 'Calcium carbonate rock -- the classic reactant for studying how surface area changes reaction rate.',
    overview: 'Marble chips are small pieces of calcium carbonate (CaCO3) rock, most often used to react with dilute acid and study how factors like particle size affect reaction rate.',
    deepFacts: [
      'Marble is a natural rock formed when limestone is transformed ("metamorphosed") by intense heat and pressure deep underground -- chemically it\'s still essentially the same calcium carbonate as limestone and chalk, just recrystallized into a different structure.',
      'Marble chips reacting with dilute hydrochloric acid to fizz and release carbon dioxide is the standard classroom reaction for studying reaction RATE, because the chips\' surface area (changed by using bigger chips, smaller chips, or powder) has a dramatic, easily measured effect on how fast gas is produced.',
      'The same calcium-carbonate-plus-acid reaction, playing out much more slowly over decades, is why acid rain and even ordinary slightly-acidic rainwater gradually erode marble statues and limestone buildings.',
    ],
    realWorldApplications: [
      'Reaction-rate experiments in school chemistry',
      'Testing rock samples for carbonate content in geology, using the same "fizz test" with dilute acid',
      'Industrial production of quicklime (CaO) by heating limestone or marble',
      'Antacid tablets, which neutralize stomach acid using the same calcium carbonate chemistry',
    ],
    commonMisconceptions: [
      '"Marble chips dissolve in water the way sugar does" -- they don\'t dissolve in plain water at all; the fizzing and disappearing only happens because the acid chemically REACTS with and breaks down the calcium carbonate, a completely different process from dissolving.',
    ],
    relatedIds: ['chem-equip-conical-flask'],
    visualType: 'none',
  },
];

export const CHEM_ELEMENT_DEEP_DIVES: DeepDiveContent[] = [
  {
    id: 'chem-element-h',
    lab: 'chemistry',
    title: 'Hydrogen',
    tagline: 'The simplest, lightest, and by far most abundant element in the entire universe.',
    overview: 'Hydrogen is the first element on the periodic table -- the lightest and most abundant element in the universe, powering stars through fusion and being explored as a clean fuel on Earth.',
    deepFacts: [
      'Hydrogen makes up about 75% of all normal matter in the universe by mass -- almost all of it forged in the first few minutes after the Big Bang, making it the most abundant element in existence by a huge margin.',
      'A hydrogen atom is the simplest possible atom: just one proton and one electron, with no neutron at all in its most common form (called protium) -- every other element\'s atom is more complex than this.',
      'Stars, including our own Sun, generate their light and heat by fusing hydrogen nuclei together into helium -- hydrogen fusion literally powers most of the visible light in the universe.',
      'Despite being so abundant everywhere else, free hydrogen gas is very rare in Earth\'s atmosphere -- it\'s so light that it easily escapes Earth\'s gravity into space over geological time, so almost all hydrogen on Earth is locked up in compounds like water rather than existing as free gas.',
    ],
    realWorldApplications: [
      'Fuel cells for clean-energy vehicles',
      'Ammonia production for fertiliser via the Haber process',
      'Liquid hydrogen as rocket fuel',
      'Hydrogenating vegetable oils to make margarine',
    ],
    commonMisconceptions: [
      '"Hydrogen is a metal" -- under everyday conditions it\'s a nonmetal gas; it has only been shown to behave like a metal under the extreme pressures found deep inside gas giant planets like Jupiter.',
    ],
    relatedIds: ['chem-element-o'],
    visualType: 'none',
  },
  {
    id: 'chem-element-o',
    lab: 'chemistry',
    title: 'Oxygen',
    tagline: 'Essential for breathing and burning alike -- and it wasn\'t always part of Earth\'s atmosphere.',
    overview: 'Oxygen is essential for respiration in almost all life, and needed for burning (combustion) to happen at all -- one of the most chemically important elements to everyday life on Earth.',
    deepFacts: [
      'Oxygen makes up about 21% of Earth\'s atmosphere by volume and roughly 65% of the human body by mass (mostly locked up as water) -- essential for the energy-releasing reactions that power almost all animal life.',
      'Free oxygen gas didn\'t always exist in Earth\'s atmosphere. It built up gradually starting roughly 2.4 billion years ago, produced by early photosynthetic cyanobacteria, in an event geologists call the "Great Oxidation Event" -- which was actually toxic to much of the anaerobic life that existed before it.',
      'Ozone (O3), a different molecular form of the same element, sits high in the atmosphere and absorbs harmful ultraviolet radiation from the Sun -- the same element that keeps us alive to breathe also shields us from radiation, just in a different molecular form.',
      'Liquid oxygen is pale blue in color and is noticeably attracted to strong magnets (paramagnetic), an unusual property for such a common gas.',
    ],
    realWorldApplications: [
      'Medical oxygen therapy',
      'Steelmaking, where it\'s blown through molten iron to remove impurities',
      'Rocket propellant oxidiser',
      'Water and wastewater treatment',
    ],
    commonMisconceptions: [
      '"Burning only uses up oxygen and produces carbon dioxide" -- combustion of most real fuels, which also contain hydrogen, produces water vapor alongside carbon dioxide too.',
    ],
    relatedIds: ['chem-element-h'],
    visualType: 'none',
  },
  {
    id: 'chem-element-na',
    lab: 'chemistry',
    title: 'Sodium',
    tagline: 'A dangerously reactive metal on its own -- that combines into the harmless salt on your table.',
    overview: 'Sodium is a soft, highly reactive metal that combines with chlorine to form ordinary table salt -- one of the clearest examples in chemistry of how a compound behaves nothing like the elements it\'s made from.',
    deepFacts: [
      'Pure sodium metal is so reactive it\'s never found free in nature -- it must be stored under oil or in an inert atmosphere in a lab, since it reacts vigorously (sometimes explosively) with the moisture and oxygen in ordinary air.',
      'Dropped into water, sodium reacts violently enough to skitter across the surface, melt from the heat of its own reaction, and sometimes ignite the hydrogen gas it produces -- a classic, carefully supervised demonstration reaction.',
      'Despite being a genuinely dangerous reactive metal on its own, sodium combined with chlorine forms ordinary, harmless table salt (NaCl) -- one of chemistry\'s clearest examples of a compound behaving completely unlike the elements that make it up.',
      'Sodium ions are essential to how nerve cells transmit electrical signals (the sodium-potassium pump) -- without it, your body couldn\'t move, think, or feel anything.',
    ],
    realWorldApplications: [
      'Table salt and food preservation',
      'Sodium-vapor streetlights, which produce a distinctive orange-yellow glow',
      'Soap-making, using sodium hydroxide',
      'Nerve signal transmission and fluid balance in the human body',
    ],
    commonMisconceptions: [
      '"Sodium is safe to handle like any ordinary solid metal" -- pure sodium metal is genuinely hazardous and reacts dangerously with the moisture on skin and with water; it should only ever be handled by trained people with proper safety equipment.',
    ],
    relatedIds: [],
    visualType: 'none',
  },
  {
    id: 'chem-element-fe',
    lab: 'chemistry',
    title: 'Iron',
    tagline: 'The metal at the heart of Earth\'s core, and the reason your blood is red.',
    overview: 'Iron is the most-used metal in the world by weight -- essential to steel, magnets, Earth\'s core, and the oxygen-carrying protein in your own blood.',
    deepFacts: [
      'Iron is the most abundant element on Earth overall by mass, because most of it is concentrated in the planet\'s core. Earth\'s solid inner core and liquid outer core are both mostly iron, and the slow churning of that liquid outer core is what generates Earth\'s protective magnetic field.',
      'Iron rusting -- forming reddish-brown iron oxide when exposed to both oxygen AND water together -- is a genuine chemical reaction, not just "wearing out." It\'s the same basic type of reaction (oxidation) as burning, just happening much more slowly.',
      'Pure iron on its own is relatively soft. The enormous range of steel types, from soft wire to hardened tool steel, comes almost entirely from precisely controlling how much carbon and which other elements are mixed in, plus how the resulting alloy is heat-treated.',
      'Blood is red specifically because of iron -- haemoglobin, the oxygen-carrying protein in red blood cells, uses an iron atom at its core to bind oxygen.',
    ],
    realWorldApplications: [
      'Steel for construction, vehicles, and tools -- the single most-used metal in the world by weight',
      'Haemoglobin in blood, for biological oxygen transport',
      'Magnets',
      'Iron supplements for treating anaemia',
    ],
    commonMisconceptions: [
      '"Rust is just old, worn-out iron" -- rust is chemically a completely different substance (iron oxide) from the metal it came from, formed by a real reaction with oxygen and water, not simple wear.',
    ],
    relatedIds: [],
    visualType: 'none',
  },
  {
    id: 'chem-element-au',
    lab: 'chemistry',
    title: 'Gold',
    tagline: 'One of the least reactive metals known -- which is exactly why ancient gold still shines today.',
    overview: 'Gold is a rare, dense, highly unreactive metal, prized throughout history for jewellery and currency, and used today in electronics for exactly the same corrosion resistance.',
    deepFacts: [
      'Gold is one of the least reactive metals known -- it doesn\'t rust, tarnish, or corrode in air or water, which is exactly why gold jewellery and coins found from thousands of years ago can still look bright and untarnished today.',
      'Gold is extraordinarily malleable -- a single gram can be hammered into a sheet covering roughly a square metre, thin enough to be almost transparent (gold leaf), without breaking apart.',
      'Its chemical symbol, Au, comes from the Latin word "aurum," meaning "shining dawn" -- unrelated to the English word "gold," which comes from an old Germanic word for the color yellow.',
      'Because it\'s such a reliable, corrosion-proof conductor of electricity, tiny amounts of gold are used to coat the electrical contacts inside smartphones, computers, and spacecraft electronics -- reliability matters more than cost in connections that must never fail.',
    ],
    realWorldApplications: [
      'Jewellery and currency, historically and today',
      'Electronics, as corrosion-resistant electrical contacts and connectors',
      'Dentistry, for crowns and fillings since it doesn\'t corrode in the mouth',
      'Spacecraft, where thin gold coatings help reflect infrared radiation and control temperature',
    ],
    commonMisconceptions: [
      '"Gold is the heaviest or densest common metal" -- it is very dense (about 19.3 g/cm3), but several other metals, like osmium and platinum, are actually denser. Gold\'s fame comes from its rarity, appearance, and unreactivity, not from being the single densest substance.',
    ],
    relatedIds: [],
    visualType: 'none',
  },
];
