import { MathTheorem } from './mathTypes';

// Theorem Corner -- Phase 1 shipped 8 theorems as text statement + text
// proof-step walkthrough. Phase 2 (this file) grows the set to 20,
// hand-verified the same way as before against real CBSE/ICSE chapter
// names (see each `chapterTags`), and adds two new fields to every entry:
// `realWorldApplications` (several concrete real uses, not just one note)
// and `visualProofId` (13 of the 20 now drive a bespoke interactive proof
// diagram in TheoremVisualProof.tsx -- the remaining 7 are symbolic
// algebraic derivations where clean step-through TEXT is the honest
// medium, not a forced animation; see that file's header for the
// reasoning behind which theorems got which treatment).
export const MATH_THEOREMS: MathTheorem[] = [
  {
    id: 'angle-sum-triangle',
    name: 'Angle Sum Property of a Triangle',
    branch: 'geometry',
    gradeBand: 'junior',
    board: 'both',
    chapterTags: ['Lines and Angles', 'Fundamental Concepts of Geometry, Angles and Their Types'],
    statement: 'The sum of the three interior angles of any triangle is always 180 degrees.',
    whyItMatters: 'This is the single most-used fact in all of triangle geometry -- once you know any two angles of a triangle, this theorem hands you the third one for free.',
    proofSteps: [
      'Draw any triangle, and draw a line through one vertex that runs parallel to the opposite side.',
      'That parallel line creates two new angles right next to the triangle\'s top angle.',
      'Because the line is parallel to the base, those two new angles are equal to the triangle\'s other two base angles (alternate angles on parallel lines).',
      'All three angles -- the two new ones plus the triangle\'s top angle -- now sit together on a straight line, and angles on a straight line always add up to 180 degrees.',
      'So the triangle\'s three original angles must also add up to 180 degrees.',
    ],
    realLifeNote: 'Carpenters and drafters use this constantly -- if you know two angles of a triangular brace or roof truss, the third is automatically fixed, no measuring needed.',
    visualProofId: 'angle-sum',
    realWorldApplications: [
      'Carpenters and drafters fix a triangular brace or roof truss\'s third angle automatically, no measuring needed.',
      'Surveyors cross-check a triangulated survey plot -- if three measured angles don\'t sum to 180°, there\'s a measurement error.',
      'Ship and aircraft bearing calculations solve navigation triangles using this exact rule.',
    ],
  },
  {
    id: 'exterior-angle-triangle',
    name: 'Exterior Angle Theorem',
    branch: 'geometry',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Lines and Angles', 'Parallel and Intersecting Lines', 'Properties of Angles and Lines (Including Parallel Lines)'],
    statement: 'An exterior angle of a triangle equals the sum of the two interior angles that are not next to it (its "remote interior angles").',
    whyItMatters: 'It\'s a direct shortcut from the Angle Sum Property -- instead of subtracting from 180 degrees, you can add the two remote angles straight away.',
    proofSteps: [
      'Extend one side of a triangle past a vertex to create an exterior angle.',
      'That exterior angle and the triangle\'s interior angle at the same vertex sit on a straight line, so together they equal 180 degrees.',
      'The triangle\'s three interior angles also add up to 180 degrees (Angle Sum Property).',
      'Since both facts equal 180 degrees and share the same interior angle at that vertex, the exterior angle must equal the sum of the other two interior angles.',
    ],
    realLifeNote: 'This shows up in navigation and surveying -- turning angles measured "outside" a path relate directly to the interior angles of the triangle the path traces out.',
    visualProofId: 'exterior-angle',
    realWorldApplications: [
      'Navigation and surveying -- "turning angles" measured outside a path relate directly to a triangle\'s interior angles.',
      'Roof truss design -- a rafter\'s slope angle relates directly to the two angles it doesn\'t touch.',
      'Mechanical design uses it in gear and pulley-system angle calculations.',
    ],
  },
  {
    id: 'pythagoras-theorem',
    name: 'Pythagoras Theorem',
    branch: 'geometry',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['The Baudhayana-Pythagoras Theorem', 'Pythagoras Theorem', 'Pythagoras Theorem (Proof and Simple Applications with Converse)'],
    statement: 'In a right-angled triangle, the square of the hypotenuse equals the sum of the squares of the other two sides: a squared plus b squared equals c squared.',
    whyItMatters: 'It\'s the bridge between geometry and algebra -- the moment you can turn a right triangle\'s side lengths into a simple equation.',
    proofSteps: [
      'Take a right triangle with legs a and b, and hypotenuse c.',
      'Build a square with side (a + b), and place four copies of the triangle inside it, arranged to leave a smaller square of side c in the middle.',
      'The big square\'s area is (a + b) squared. It also equals the four triangles\' combined area plus the inner square\'s area (c squared).',
      'Expanding (a + b) squared and cancelling the matching triangle-area terms on both sides leaves exactly a squared plus b squared equals c squared.',
    ],
    realLifeNote: 'This is literally named after the Indian mathematician Baudhayana in the CBSE Class 8 curriculum -- his Sulba Sutra stated this same rule centuries before Pythagoras, using it to build perfectly square altars.',
    visualProofId: 'pythagoras',
    realWorldApplications: [
      'Baudhayana\'s Sulba Sutra used this exact rule to build perfectly square altars, centuries before Pythagoras.',
      'TV and monitor sizes (the diagonal) are computed from width and height using this theorem.',
      'Construction crews check a foundation is truly square using the 3-4-5 rule, a direct application.',
    ],
  },
  {
    id: 'midpoint-theorem',
    name: 'Mid-point Theorem',
    branch: 'geometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Mid-point and Its Converse, Including Intercept Theorem'],
    statement: 'The line segment joining the midpoints of any two sides of a triangle is parallel to the third side, and exactly half its length.',
    whyItMatters: 'It gives you a guaranteed parallel line and a guaranteed length ratio just from knowing two midpoints -- no angle measuring required.',
    proofSteps: [
      'Take a triangle and mark the midpoints of two of its sides.',
      'Join those two midpoints with a straight segment.',
      'Extend that segment to twice its length, and connect its new endpoint back into the triangle -- this creates a second triangle congruent to a piece of the first.',
      'Comparing the two triangles shows the midpoint segment must run parallel to the third side, and matching up the equal sides shows it\'s exactly half that side\'s length.',
    ],
    realLifeNote: 'Structural engineers use this to find the centerline of triangular trusses and bridge supports without needing to measure the full span directly.',
    visualProofId: 'midpoint',
    realWorldApplications: [
      'Structural engineers find the centerline of triangular trusses and bridge supports without measuring the full span.',
      'Used to prove a triangle\'s three medians always meet at one single point (the centroid).',
      'Cartographers interpolate points on a map using midpoint relationships instead of direct measurement.',
    ],
  },
  {
    id: 'basic-proportionality-theorem',
    name: 'Basic Proportionality Theorem (Thales Theorem)',
    branch: 'geometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Triangles', 'Similarity'],
    statement: 'If a line is drawn parallel to one side of a triangle so that it crosses the other two sides, it divides those two sides in the same ratio.',
    whyItMatters: 'This is the foundation of similar triangles -- it\'s the exact rule that lets you scale a triangle up or down while keeping its shape.',
    proofSteps: [
      'Draw a triangle, then draw a line parallel to its base that crosses the other two sides at two new points.',
      'That parallel line cuts off a smaller triangle at the top that shares the same angles as the original (parallel lines preserve angles).',
      'Because the two triangles have identical angles, they are similar -- meaning their corresponding sides are all in the same ratio.',
      'That shared ratio is exactly the ratio in which the parallel line divided the two original sides.',
    ],
    realLifeNote: 'This is credited to the ancient Greek mathematician Thales, who is said to have used it to measure the height of the Great Pyramid of Giza from the length of its shadow.',
    visualProofId: 'bpt',
    realWorldApplications: [
      'Thales is said to have measured the Great Pyramid of Giza\'s height from its shadow using this exact rule.',
      'Map scaling -- enlarging or shrinking a shape while keeping every internal ratio identical.',
      'Camera and projector lens optics relate object distance, image distance, and size using similar-triangle ratios.',
    ],
  },
  {
    id: 'angle-in-semicircle',
    name: 'Angle in a Semicircle',
    branch: 'geometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Circles', 'Tangent and Secant Properties', 'Circle'],
    statement: 'The angle subtended by a diameter at any point on the circle\'s circumference is always exactly 90 degrees.',
    whyItMatters: 'It\'s a special case of a bigger circle rule (the angle at the center is always twice the angle at the circumference) -- since a diameter\'s "center angle" is a straight 180 degrees, the circumference angle it creates must be exactly half of that: 90 degrees, no matter where on the circle you pick the point.',
    proofSteps: [
      'Draw a circle with a diameter, and pick any third point on the circle to form a triangle with the two ends of the diameter.',
      'Draw a line from the center to that third point -- this splits the triangle into two smaller isosceles triangles (each has two equal radii as sides).',
      'In each isosceles triangle, the two base angles are equal, so label them x and y.',
      'The triangle\'s three angles are x, y, and (x + y), and by the Angle Sum Property they total 180 degrees, giving 2x + 2y = 180, so x + y = 90 degrees -- exactly the angle at the third point.',
    ],
    realLifeNote: 'This rule is why a semicircular carpenter\'s square (or a "Thales square") can reliably mark a perfect right angle just by resting its ends on a circle\'s diameter.',
    visualProofId: 'circle-angle',
    realWorldApplications: [
      'A carpenter\'s "Thales square" marks a perfect right angle just by resting its ends on a circle\'s diameter.',
      'Engineering drawing constructs a perfect right angle using only a compass and straightedge via this rule.',
      'Sports court markings (like the "D" arc on a basketball or football pitch) use related circle-geometry constructions.',
    ],
  },
  {
    id: 'sum-of-ap',
    name: 'Sum of the First n Terms of an Arithmetic Progression',
    branch: 'algebra',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Arithmetic Progressions', 'Arithmetic and Geometric Progression'],
    statement: 'The sum of the first n terms of an arithmetic progression (first term a, common difference d) is: Sn = n/2 times (2a + (n-1)d).',
    whyItMatters: 'It turns "add up hundreds of evenly-spaced numbers" into a single quick calculation instead of tedious repeated addition.',
    proofSteps: [
      'Write the sum S forwards: a + (a+d) + (a+2d) + ... + (last term).',
      'Write the exact same sum backwards, term for term, and add the two versions together.',
      'Every matching pair (first term + last term, second term + second-last term, and so on) adds up to the SAME total: (first term + last term).',
      'There are n such pairs, so 2S = n times (first term + last term), which rearranges into the formula Sn = n/2 times (2a + (n-1)d).',
    ],
    realLifeNote: 'Legend has it a young Carl Friedrich Gauss discovered this exact pairing trick as a schoolboy, instantly summing 1 to 100 by pairing 1+100, 2+99, and so on, instead of adding all 100 numbers one by one.',
    visualProofId: 'ap-pairing',
    realWorldApplications: [
      'A young Gauss instantly summed 1 to 100 with this exact pairing trick instead of adding one by one.',
      'Loan/EMI schedules where a fixed amount decreases (or increases) each period sum via this formula.',
      'Stacking problems -- total bricks or cans in a triangular stack, each row one more than the last.',
    ],
  },
  {
    id: 'binomial-theorem',
    name: 'Binomial Theorem',
    branch: 'algebra',
    gradeBand: 'plusTwo',
    board: 'both',
    chapterTags: ['Binomial Theorem', 'Algebra'],
    statement: 'For a positive whole number n, (a + b) raised to the power n expands into the sum, over k from 0 to n, of "n choose k" times a to the power (n-k) times b to the power k.',
    whyItMatters: 'It replaces tedious repeated multiplication -- expanding (a+b) to a high power by hand -- with a direct formula using combinations you can look up or compute instantly.',
    proofSteps: [
      'Think of (a + b) to the power n as n identical brackets (a + b) all multiplied together.',
      'Expanding fully means picking either "a" or "b" from each of the n brackets and multiplying your n picks together, then adding up every possible way of picking.',
      'For a term with exactly k copies of "b" (and therefore (n-k) copies of "a"), the number of different ways to choose WHICH k brackets contributed the "b" is exactly "n choose k".',
      'Collecting all these equal terms together for each value of k from 0 to n gives the full binomial expansion.',
    ],
    realLifeNote: 'The same "n choose k" coefficients form Pascal\'s Triangle -- a pattern that shows up far beyond algebra, including in probability calculations and even in genetics when predicting trait combinations across generations.',
    visualProofId: 'binomial-pascal',
    realWorldApplications: [
      'Pascal\'s Triangle coefficients predict trait combinations across generations in genetics.',
      'Probability calculations for binomial-distribution outcomes (like coin-flip counts) use these exact coefficients.',
      'Compound-interest approximations and error-propagation formulas in physics/engineering use binomial expansions.',
    ],
  },

  // -- New in Phase 2 --------------------------------------------------------
  {
    id: 'angle-sum-polygon',
    name: 'Angle Sum of a Polygon',
    branch: 'geometry',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Understanding Quadrilaterals', 'Rectilinear Figures'],
    statement: 'The sum of the interior angles of a polygon with n sides is (n minus 2) times 180 degrees.',
    whyItMatters: 'It generalizes the Angle Sum Property of a Triangle to any polygon -- once you know how many sides a shape has, this instantly tells you what all its interior angles must add up to.',
    proofSteps: [
      'Pick any vertex of the polygon and draw diagonals from it to every other non-adjacent vertex.',
      'This splits the polygon into a number of non-overlapping triangles -- for an n-sided polygon, this always gives exactly (n - 2) triangles.',
      'Each triangle\'s angles sum to 180 degrees (Angle Sum Property), and together the triangles\' angles exactly cover every interior angle of the polygon.',
      'So the polygon\'s total interior angle sum is (n - 2) triangles times 180 degrees each, giving (n - 2) times 180 degrees.',
    ],
    realLifeNote: 'A regular hexagon\'s interior angle works out to exactly 120 degrees -- which is exactly why hexagonal tiles (and honeycomb cells) fit together with no gaps at all.',
    realWorldApplications: [
      'Architects design regular polygon floor plans (like a hexagonal gazebo) where every interior angle must be identical and known in advance.',
      'Honeycomb and tiling patterns rely on knowing a hexagon\'s interior angle (120°) fits perfectly with no gaps.',
      'Robotics path-planning around polygonal obstacles computes turning angles from interior angle sums.',
    ],
  },
  {
    id: 'congruence-sas',
    name: 'Triangle Congruence -- SAS Criterion',
    branch: 'geometry',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Congruence of Triangles', 'Congruency: Similarity'],
    statement: 'If two sides and the included angle of one triangle are equal to two sides and the included angle of another triangle, the two triangles are congruent (SAS: Side-Angle-Side).',
    whyItMatters: 'It\'s one of the fastest ways to prove two triangles are exactly identical in shape and size without measuring every single side and angle.',
    proofSteps: [
      'Take two triangles where two sides and the angle between them are already known to match exactly.',
      'Imagine picking up the first triangle and placing it on top of the second, matching the two equal sides and the equal angle between them exactly.',
      'Because two sides and the angle between them are fixed, there is only one possible position for the third vertex -- it is completely determined.',
      'Since every vertex now lines up exactly, the two triangles must be identical in every side and angle -- they are congruent.',
    ],
    realLifeNote: 'Manufacturing relies on this: if a machine cuts two sides and the angle between them to the same specification every time, every part produced is guaranteed identical.',
    realWorldApplications: [
      'Manufacturing and CNC machining guarantee identical parts from the same two-side-and-angle specification.',
      'Bridge truss fabrication -- congruent triangular sections make a truss symmetric and load-predictable.',
      'Used as a building block to prove other results, like the Isosceles Triangle base-angles theorem.',
    ],
  },
  {
    id: 'similarity-aa',
    name: 'Similarity of Triangles -- AA Criterion',
    branch: 'geometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Triangles', 'Similarity'],
    statement: 'If two angles of one triangle are equal to two angles of another triangle, the two triangles are similar (AA: Angle-Angle) -- their corresponding sides are all in the same ratio.',
    whyItMatters: 'Since a triangle\'s three angles always sum to 180 degrees, matching just two angles automatically forces the third to match too -- so AA is really the minimum possible information needed to guarantee the same shape.',
    proofSteps: [
      'Take two triangles where two pairs of corresponding angles are already known to be equal.',
      'By the Angle Sum Property, the third angle in each triangle is 180 degrees minus the other two -- so if two angles match, the third automatically matches too.',
      'With all three angles equal, one triangle is just a scaled-up or scaled-down copy of the other -- same shape, possibly different size.',
      'A scaled copy means every pair of corresponding sides shares the exact same ratio -- that shared ratio is the similarity (scale) factor.',
    ],
    realLifeNote: 'Shadow-based height measurement (a stick and its shadow vs. a tree and its shadow) works because the sun\'s rays create two similar right triangles at the same instant.',
    realWorldApplications: [
      'Measuring a tall tree or building\'s height via shadows -- the classic Thales-style technique.',
      'Map and blueprint scaling -- a map is a similar, much smaller copy of the real terrain.',
      'Photography and optics -- a camera\'s image on the sensor is similar to the real scene.',
    ],
  },
  {
    id: 'tangent-radius-perpendicular',
    name: 'Tangent-Radius Theorem',
    branch: 'geometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Circles', 'Tangent and Secant Properties', 'Tangent Properties'],
    statement: 'A tangent to a circle is always perpendicular to the radius drawn to the point of contact.',
    whyItMatters: 'It\'s the key fact that turns "draw a line touching the circle at exactly one point" into an exact, constructible 90-degree relationship.',
    proofSteps: [
      'Draw a circle with center O, and a tangent line touching it at point P.',
      'Pick any other point Q on the tangent line, and draw the segment OQ.',
      'Because the tangent only touches the circle at P, every other point on the tangent line -- including Q -- must lie outside the circle, so OQ is always longer than the radius OP.',
      'Since OP is shorter than every other segment from O to the tangent line, OP must be the shortest distance from O to that line -- and the shortest distance from a point to a line is always the perpendicular distance.',
      'So OP (the radius) is perpendicular to the tangent line at P.',
    ],
    realLifeNote: 'Gear design relies on this constantly -- the line where two gear teeth touch is tangent to both gears\' pitch circles, and engineers use the perpendicular-radius relationship to compute contact forces.',
    visualProofId: 'tangent-radius',
    realWorldApplications: [
      'Gear-tooth contact-force engineering uses the radius-perpendicular relationship at the contact point.',
      'Satellite dish and antenna reflector curves use tangent-radius geometry to focus signals.',
      'Vehicle wheel geometry -- the tangent line at the road-contact point is exactly perpendicular to the wheel\'s radius there.',
    ],
  },
  {
    id: 'quadratic-formula-derivation',
    name: 'The Quadratic Formula',
    branch: 'algebra',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Quadratic Equations'],
    statement: 'For any quadratic equation ax squared + bx + c = 0 (with a not zero), the solutions are x = (negative b plus-or-minus the square root of (b squared minus 4ac)) divided by 2a.',
    whyItMatters: 'It solves ANY quadratic equation directly, without needing to factorize -- which is essential since many quadratics (with irrational or complex roots) can\'t be factorized neatly at all.',
    proofSteps: [
      'Start with ax² + bx + c = 0, and divide every term by a (allowed since a is not zero), giving x² + (b/a)x + (c/a) = 0.',
      'Move the constant term to the other side: x² + (b/a)x = -(c/a).',
      'Complete the square by adding (b/2a)² to both sides, turning the left side into a perfect square: (x + b/2a)² = (b/2a)² - c/a.',
      'Simplify the right side over a common denominator: (x + b/2a)² = (b² - 4ac) / 4a².',
      'Take the square root of both sides (keeping both the plus and minus root) and subtract b/2a, giving the quadratic formula.',
    ],
    realLifeNote: 'This formula is built directly into calculators and computer programs -- any software that needs to solve a quadratic (physics simulations, financial models, computer graphics) usually calls this exact formula internally.',
    realWorldApplications: [
      'Projectile motion -- solving for when a thrown object hits the ground (a quadratic in time).',
      'Computer graphics -- ray-sphere intersection tests solve a quadratic for where a ray hits a curved surface.',
      'Financial modeling -- some break-even and profit-maximization problems reduce to a quadratic equation.',
    ],
  },
  {
    id: 'remainder-theorem',
    name: 'Remainder Theorem',
    branch: 'algebra',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Polynomials', 'Remainder and Factor Theorems'],
    statement: 'If a polynomial p(x) is divided by (x minus a), the remainder is exactly p(a) -- the polynomial\'s value when x is replaced by a.',
    whyItMatters: 'It lets you find a division remainder instantly by plugging in one number, without doing the actual long division of polynomials.',
    proofSteps: [
      'Dividing p(x) by (x - a) always gives p(x) = (x - a) times q(x) + r, where q(x) is the quotient and r is some constant remainder (since dividing by a degree-1 polynomial always leaves a constant remainder).',
      'This equation is true for every value of x, so it must also be true when x = a specifically.',
      'Substituting x = a makes the first term (x - a) equal zero, so p(a) = 0 times q(a) + r = r.',
      'So the remainder r is exactly p(a) -- the original polynomial evaluated at x = a.',
    ],
    realLifeNote: 'Example: dividing p(x) = x cubed minus 2x plus 5 by (x - 2) gives a remainder of p(2) = 8 - 4 + 5 = 9, instantly -- no long division needed.',
    realWorldApplications: [
      'Shortcuts polynomial division constantly in competitive-exam algebra.',
      'Error-correcting codes (like CRC checksums used in networking and storage) are built on polynomial remainder arithmetic.',
      'Computer algebra systems use this to evaluate and simplify polynomial expressions efficiently.',
    ],
  },
  {
    id: 'factor-theorem',
    name: 'Factor Theorem',
    branch: 'algebra',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Polynomials', 'Remainder and Factor Theorems'],
    statement: '(x minus a) is a factor of a polynomial p(x) if and only if p(a) equals zero.',
    whyItMatters: 'It turns "find a factor" into "find a root" -- test a candidate number, and if it makes the polynomial zero, you\'ve found an exact factor.',
    proofSteps: [
      'By the Remainder Theorem, dividing p(x) by (x - a) always leaves a remainder of exactly p(a).',
      '(x - a) is a factor of p(x) exactly when that division leaves no remainder, i.e. when the remainder is 0.',
      'Combining those two facts: (x - a) is a factor of p(x) if and only if p(a) = 0.',
    ],
    realLifeNote: 'Example: for p(x) = x squared minus 5x plus 6, testing x = 2 gives p(2) = 4 - 10 + 6 = 0, so (x - 2) is a factor -- and dividing confirms p(x) = (x - 2)(x - 3).',
    realWorldApplications: [
      'The standard technique for factorizing cubic and higher-degree polynomials in CBSE/ICSE algebra.',
      'Engineering control systems find the roots (poles) of a system\'s characteristic polynomial this way.',
      'Cryptography and coding theory use polynomial factorization over finite fields, built on this same principle.',
    ],
  },
  {
    id: 'sum-of-gp',
    name: 'Sum of the First n Terms of a Geometric Progression',
    branch: 'algebra',
    gradeBand: 'plusTwo',
    board: 'both',
    chapterTags: ['Arithmetic and Geometric Progression', 'Sequences and Series'],
    statement: 'The sum of the first n terms of a geometric progression (first term a, common ratio r, r not 1) is: Sn = a(r to the n minus 1) divided by (r minus 1).',
    whyItMatters: 'It turns "add up n terms that are each a fixed multiple of the last" into one direct calculation -- essential since GP terms can grow (or shrink) far too fast to add by hand.',
    proofSteps: [
      'Write the sum S = a + ar + ar² + ... + ar^(n-1).',
      'Multiply the entire sum by r: rS = ar + ar² + ar³ + ... + ar^n.',
      'Subtract the first equation from the second: rS - S = ar^n - a (every middle term cancels out, since the two sums share every term except the very first and very last).',
      'Factor both sides: S(r - 1) = a(r^n - 1), so S = a(r^n - 1) / (r - 1).',
    ],
    realLifeNote: 'Compound interest is a geometric progression -- each year\'s balance is the previous year\'s multiplied by (1 + rate) -- so this exact formula is what banks use to compute total value over time.',
    realWorldApplications: [
      'Compound interest and investment growth calculations.',
      'Population growth/decay models (bacteria doubling, radioactive decay) over discrete time steps.',
      'Analyzing total work across all levels of a divide-and-conquer algorithm (like merge sort) sums a geometric series.',
    ],
  },
  {
    id: 'pythagorean-trig-identity',
    name: 'Pythagorean Trigonometric Identity',
    branch: 'trigonometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Introduction to Trigonometry', 'Trigonometrical Ratios', 'Trigonometric Identities'],
    statement: 'For any angle theta, sin squared theta plus cos squared theta always equals 1.',
    whyItMatters: 'It\'s the single most-used trigonometric identity -- nearly every other trig identity in the CBSE/ICSE syllabus is derived from this one.',
    proofSteps: [
      'Draw a right triangle with angle theta, hypotenuse of length 1 (a "unit" right triangle), the side opposite theta of length sin theta, and the side adjacent to theta of length cos theta.',
      'By definition, sin theta = opposite / hypotenuse = opposite / 1, and cos theta = adjacent / hypotenuse = adjacent / 1.',
      'Apply the Pythagoras Theorem to this right triangle: (opposite)² + (adjacent)² = (hypotenuse)².',
      'Substituting: (sin theta)² + (cos theta)² = 1² = 1.',
    ],
    realLifeNote: 'This is exactly why a point at angle theta on a unit circle always has coordinates (cos theta, sin theta) -- both trig ratios and circle geometry describe the exact same fact.',
    visualProofId: 'unit-circle',
    realWorldApplications: [
      'Computer graphics and game engines use it constantly to keep rotation calculations numerically stable.',
      'Audio and radio signal processing analyzes and combines waveforms using sin/cos identities built on this.',
      'GPS and navigation systems convert between coordinate systems using trigonometric identities derived from this.',
    ],
  },
  {
    id: 'fundamental-theorem-arithmetic',
    name: 'Fundamental Theorem of Arithmetic',
    branch: 'number-systems',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Real Numbers', 'Fundamental Theorem of Arithmetic'],
    statement: 'Every whole number greater than 1 can be written as a product of prime numbers in exactly one way, ignoring the order of the factors.',
    whyItMatters: 'It guarantees prime numbers are the true, unique "building blocks" of every whole number -- there is never more than one possible prime breakdown for any given number.',
    proofSteps: [
      'Take any whole number greater than 1. If it\'s already prime, it is its own one-factor prime factorization -- done.',
      'If it\'s not prime, it can be split into two smaller factors, each greater than 1.',
      'Repeat this splitting process on each new factor -- since the factors keep getting smaller, this process must eventually stop, at which point every remaining factor is prime.',
      'The harder remaining part (which this sketch only summarizes) is proving this prime breakdown is always UNIQUE -- no matter which splitting order you choose, you always end up with the exact same set of prime factors.',
    ],
    realLifeNote: 'This is exactly why HCF and LCM can always be computed reliably from prime factorizations -- and it\'s the deep reason modern encryption (RSA) is secure: factoring a huge number into its unique primes is computationally very hard.',
    visualProofId: 'prime-factor-tree',
    realWorldApplications: [
      'HCF and LCM computation via prime factorization.',
      'RSA encryption (used to secure most of the internet) relies on large numbers being hard to factor into their unique primes.',
      'Proves numbers like the square root of 2 are irrational, a classic proof-by-contradiction application.',
    ],
  },
  {
    id: 'euler-formula-polyhedra',
    name: "Euler's Formula for Polyhedra",
    branch: 'mensuration',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Visualising Solid Shapes'],
    statement: 'For any convex polyhedron, the number of vertices minus the number of edges plus the number of faces always equals 2: V minus E plus F equals 2.',
    whyItMatters: 'It\'s a genuinely surprising fact -- however you stretch, rotate, or resize a convex solid (cube, pyramid, prism...), this exact relationship between its corners, edges, and faces never changes.',
    proofSteps: [
      'Count the vertices (corners), edges, and faces of a simple polyhedron -- for example, a cube has 8 vertices, 12 edges, and 6 faces.',
      'Check: V - E + F = 8 - 12 + 6 = 2.',
      'Now try a triangular pyramid (tetrahedron): 4 vertices, 6 edges, 4 faces -- V - E + F = 4 - 6 + 4 = 2, the same result.',
      'This holds for every convex polyhedron -- adding a new face always adds enough new edges and vertices together to keep V - E + F fixed at exactly 2.',
    ],
    realLifeNote: "Euler's formula is the starting point for topology (the branch of math studying shapes that stretch and bend) -- the same reasoning shows a soccer ball's 12 pentagons and 20 hexagons can only ever be arranged one consistent way.",
    visualProofId: 'euler-polyhedron',
    realWorldApplications: [
      "Geodesic dome architecture (like Buckminster Fuller's domes) plans exactly how many struts and joints a design needs.",
      '3D computer graphics and game engines validate a mesh is a properly "closed" (watertight) solid using this.',
      'Soccer ball panel layouts and virus-capsid structures (both roughly polyhedral) follow this exact relationship.',
    ],
  },
  {
    id: 'cone-cylinder-volume-ratio',
    name: 'Volume of a Cone is One-Third the Volume of a Cylinder',
    branch: 'mensuration',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Surface Areas and Volumes', 'Mensuration'],
    statement: 'A cone and a cylinder with the same base radius and the same height always have this exact relationship: the cone\'s volume is exactly one-third the cylinder\'s volume.',
    whyItMatters: 'It\'s the reason the cone volume formula has that "1/3" in it -- not an arbitrary constant, but a direct, provable relationship to the simpler cylinder formula.',
    proofSteps: [
      'Take a cylinder and a cone that share the exact same base radius r and the exact same height h.',
      'The cylinder\'s volume is the well-established formula: pi times r squared times h.',
      'A classic hands-on demonstration (fill an empty cone-shaped container with water or sand, and pour it into an empty same-base-same-height cylinder) always takes exactly 3 full cone-fulls to fill the cylinder.',
      'So the cone\'s volume must be exactly one-third of the cylinder\'s: (1/3) times pi times r squared times h -- exactly the standard cone volume formula.',
    ],
    realLifeNote: 'This 1:3 ratio is why cone-shaped paper cups and ice cream cones feel like they hold "surprisingly little" compared to a cylindrical cup of the same width and height -- they genuinely hold exactly one-third as much.',
    visualProofId: 'cone-cylinder-ratio',
    realWorldApplications: [
      'Packaging design compares how much a cone-shaped versus cylinder-shaped container actually holds.',
      'Civil engineering calculates the volume of conical stockpiles (sand, gravel) versus cylindrical silos.',
      'Derives the volume of a pyramid too -- a pyramid is also exactly 1/3 of the prism that contains it.',
    ],
  },
];
