import { MathTheorem } from './mathTypes';

// Theorem Corner -- Phase 1 of Math Lab. Every statement below is a standard
// CBSE/ICSE textbook result, hand-verified against the real chapter names
// pulled from this app's own curriculum database (see each `chapterTags`).
// `proofSteps` are plain-English walk-through steps for a visual sketch to
// animate one at a time -- not a full formal proof, the same "show the
// real idea, not just the label" spirit as every other lab's `explanation`.
export const MATH_THEOREMS: MathTheorem[] = [
  {
    id: 'angle-sum-triangle',
    name: 'Angle Sum Property of a Triangle',
    branch: 'geometry',
    gradeBand: 'junior',
    board: 'both',
    chapterTags: ['Lines and Angles', 'Fundamental Concepts of Geometry, Angles and Their Types'],
    statement: 'The sum of the three interior angles of any triangle is always 180 degrees.',
    whyItMatters: 'This is the single most-used fact in all of triangle geometry -- once you know any two angles of a triangle, this theorem hands you the third one for free.',
    proofSteps: [
      'Draw any triangle, and draw a line through one vertex that runs parallel to the opposite side.',
      'That parallel line creates two new angles right next to the triangle\'s top angle.',
      'Because the line is parallel to the base, those two new angles are equal to the triangle\'s other two base angles (alternate angles on parallel lines).',
      'All three angles -- the two new ones plus the triangle\'s top angle -- now sit together on a straight line, and angles on a straight line always add up to 180 degrees.',
      'So the triangle\'s three original angles must also add up to 180 degrees.',
    ],
    realLifeNote: 'Carpenters and drafters use this constantly -- if you know two angles of a triangular brace or roof truss, the third is automatically fixed, no measuring needed.',
  },
  {
    id: 'exterior-angle-triangle',
    name: 'Exterior Angle Theorem',
    branch: 'geometry',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Lines and Angles', 'Parallel and Intersecting Lines', 'Properties of Angles and Lines (Including Parallel Lines)'],
    statement: 'An exterior angle of a triangle equals the sum of the two interior angles that are not next to it (its "remote interior angles").',
    whyItMatters: 'It\'s a direct shortcut from the Angle Sum Property -- instead of subtracting from 180 degrees, you can add the two remote angles straight away.',
    proofSteps: [
      'Extend one side of a triangle past a vertex to create an exterior angle.',
      'That exterior angle and the triangle\'s interior angle at the same vertex sit on a straight line, so together they equal 180 degrees.',
      'The triangle\'s three interior angles also add up to 180 degrees (Angle Sum Property).',
      'Since both facts equal 180 degrees and share the same interior angle at that vertex, the exterior angle must equal the sum of the other two interior angles.',
    ],
    realLifeNote: 'This shows up in navigation and surveying -- turning angles measured "outside" a path relate directly to the interior angles of the triangle the path traces out.',
  },
  {
    id: 'pythagoras-theorem',
    name: 'Pythagoras Theorem',
    branch: 'geometry',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['The Baudhayana-Pythagoras Theorem', 'Pythagoras Theorem', 'Pythagoras Theorem (Proof and Simple Applications with Converse)'],
    statement: 'In a right-angled triangle, the square of the hypotenuse equals the sum of the squares of the other two sides: a squared plus b squared equals c squared.',
    whyItMatters: 'It\'s the bridge between geometry and algebra -- the moment you can turn a right triangle\'s side lengths into a simple equation.',
    proofSteps: [
      'Take a right triangle with legs a and b, and hypotenuse c.',
      'Build a square with side (a + b), and place four copies of the triangle inside it, arranged to leave a smaller square of side c in the middle.',
      'The big square\'s area is (a + b) squared. It also equals the four triangles\' combined area plus the inner square\'s area (c squared).',
      'Expanding (a + b) squared and cancelling the matching triangle-area terms on both sides leaves exactly a squared plus b squared equals c squared.',
    ],
    realLifeNote: 'This is literally named after the Indian mathematician Baudhayana in the CBSE Class 8 curriculum -- his Sulba Sutra stated this same rule centuries before Pythagoras, using it to build perfectly square altars.',
  },
  {
    id: 'midpoint-theorem',
    name: 'Mid-point Theorem',
    branch: 'geometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Mid-point and Its Converse, Including Intercept Theorem'],
    statement: 'The line segment joining the midpoints of any two sides of a triangle is parallel to the third side, and exactly half its length.',
    whyItMatters: 'It gives you a guaranteed parallel line and a guaranteed length ratio just from knowing two midpoints -- no angle measuring required.',
    proofSteps: [
      'Take a triangle and mark the midpoints of two of its sides.',
      'Join those two midpoints with a straight segment.',
      'Extend that segment to twice its length, and connect its new endpoint back into the triangle -- this creates a second triangle congruent to a piece of the first.',
      'Comparing the two triangles shows the midpoint segment must run parallel to the third side, and matching up the equal sides shows it\'s exactly half that side\'s length.',
    ],
    realLifeNote: 'Structural engineers use this to find the centerline of triangular trusses and bridge supports without needing to measure the full span directly.',
  },
  {
    id: 'basic-proportionality-theorem',
    name: 'Basic Proportionality Theorem (Thales Theorem)',
    branch: 'geometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Triangles', 'Similarity'],
    statement: 'If a line is drawn parallel to one side of a triangle so that it crosses the other two sides, it divides those two sides in the same ratio.',
    whyItMatters: 'This is the foundation of similar triangles -- it\'s the exact rule that lets you scale a triangle up or down while keeping its shape.',
    proofSteps: [
      'Draw a triangle, then draw a line parallel to its base that crosses the other two sides at two new points.',
      'That parallel line cuts off a smaller triangle at the top that shares the same angles as the original (parallel lines preserve angles).',
      'Because the two triangles have identical angles, they are similar -- meaning their corresponding sides are all in the same ratio.',
      'That shared ratio is exactly the ratio in which the parallel line divided the two original sides.',
    ],
    realLifeNote: 'This is credited to the ancient Greek mathematician Thales, who is said to have used it to measure the height of the Great Pyramid of Giza from the length of its shadow.',
  },
  {
    id: 'angle-in-semicircle',
    name: 'Angle in a Semicircle',
    branch: 'geometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Circles', 'Tangent and Secant Properties', 'Circle'],
    statement: 'The angle subtended by a diameter at any point on the circle\'s circumference is always exactly 90 degrees.',
    whyItMatters: 'It\'s a special case of a bigger circle rule (the angle at the center is always twice the angle at the circumference) -- since a diameter\'s "center angle" is a straight 180 degrees, the circumference angle it creates must be exactly half of that: 90 degrees, no matter where on the circle you pick the point.',
    proofSteps: [
      'Draw a circle with a diameter, and pick any third point on the circle to form a triangle with the two ends of the diameter.',
      'Draw a line from the center to that third point -- this splits the triangle into two smaller isosceles triangles (each has two equal radii as sides).',
      'In each isosceles triangle, the two base angles are equal, so label them x and y.',
      'The triangle\'s three angles are x, y, and (x + y), and by the Angle Sum Property they total 180 degrees, giving 2x + 2y = 180, so x + y = 90 degrees -- exactly the angle at the third point.',
    ],
    realLifeNote: 'This rule is why a semicircular carpenter\'s square (or a "Thales square") can reliably mark a perfect right angle just by resting its ends on a circle\'s diameter.',
  },
  {
    id: 'sum-of-ap',
    name: 'Sum of the First n Terms of an Arithmetic Progression',
    branch: 'algebra',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Arithmetic Progressions', 'Arithmetic and Geometric Progression'],
    statement: 'The sum of the first n terms of an arithmetic progression (first term a, common difference d) is: Sn = n/2 times (2a + (n-1)d).',
    whyItMatters: 'It turns "add up hundreds of evenly-spaced numbers" into a single quick calculation instead of tedious repeated addition.',
    proofSteps: [
      'Write the sum S forwards: a + (a+d) + (a+2d) + ... + (last term).',
      'Write the exact same sum backwards, term for term, and add the two versions together.',
      'Every matching pair (first term + last term, second term + second-last term, and so on) adds up to the SAME total: (first term + last term).',
      'There are n such pairs, so 2S = n times (first term + last term), which rearranges into the formula Sn = n/2 times (2a + (n-1)d).',
    ],
    realLifeNote: 'Legend has it a young Carl Friedrich Gauss discovered this exact pairing trick as a schoolboy, instantly summing 1 to 100 by pairing 1+100, 2+99, and so on, instead of adding all 100 numbers one by one.',
  },
  {
    id: 'binomial-theorem',
    name: 'Binomial Theorem',
    branch: 'algebra',
    gradeBand: 'plusTwo',
    board: 'both',
    chapterTags: ['Binomial Theorem', 'Algebra'],
    statement: 'For a positive whole number n, (a + b) raised to the power n expands into the sum, over k from 0 to n, of "n choose k" times a to the power (n-k) times b to the power k.',
    whyItMatters: 'It replaces tedious repeated multiplication -- expanding (a+b) to a high power by hand -- with a direct formula using combinations you can look up or compute instantly.',
    proofSteps: [
      'Think of (a + b) to the power n as n identical brackets (a + b) all multiplied together.',
      'Expanding fully means picking either "a" or "b" from each of the n brackets and multiplying your n picks together, then adding up every possible way of picking.',
      'For a term with exactly k copies of "b" (and therefore (n-k) copies of "a"), the number of different ways to choose WHICH k brackets contributed the "b" is exactly "n choose k".',
      'Collecting all these equal terms together for each value of k from 0 to n gives the full binomial expansion.',
    ],
    realLifeNote: 'The same "n choose k" coefficients form Pascal\'s Triangle -- a pattern that shows up far beyond algebra, including in probability calculations and even in genetics when predicting trait combinations across generations.',
  },
];
