import { MathExperiment } from './mathTypes';

// Guided Predict -> Explore -> Explain experiments -- Phase 2 of Math Lab,
// same curated-not-generated discipline as every other lab's experiment
// library. Six experiments span early through senior grade bands; plusTwo
// (calculus-era) experiments are a Phase 3 item alongside the deeper Free
// Play calculators. Every chapterTag traces to a real NCERT/ICSE chapter
// name pulled from this app's own curriculum database.
export const MATH_EXPERIMENTS: MathExperiment[] = [
  {
    id: 'exp-fair-share',
    title: 'Fair Share Divider',
    branch: 'number-systems',
    gradeBand: 'early',
    board: 'both',
    chapterTags: ['Fair Share', 'Grouping and Sharing'],
    simType: 'divide',
    defaultParams: { totalItems: 20, groups: 4 },
    paramConfig: [
      { key: 'totalItems', label: 'Total Items', unit: '', min: 4, max: 40, step: 1 },
      { key: 'groups', label: 'Number of Groups', unit: '', min: 2, max: 8, step: 1 },
    ],
    purpose: 'See exactly what "sharing equally" means -- and what happens to the items left over when a number doesn\'t divide evenly.',
    predictPrompt: 'If you share 20 items equally among 4 people, will there be any items left over?',
    predictOptions: ['No, it divides evenly', 'Yes, there will be leftovers', 'It depends on the items'],
    correctPredictIndex: 0,
    keyIdea: 'Division splits a total into equal groups -- whatever can\'t be split evenly is the remainder.',
    steps: [
      { number: 1, instruction: 'Start with the default 20 items shared among 4 groups. Watch every item land in a group with none left over.', paramChanges: { totalItems: 20, groups: 4 } },
      { number: 2, instruction: 'Now try 22 items among 4 groups -- watch what happens to the 2 that don\'t fit evenly.', paramChanges: { totalItems: 22, groups: 4 } },
      { number: 3, instruction: 'Try changing the numbers yourself with the sliders below. Can you find a combination with no remainder at all?' },
    ],
    observationPrompts: ['How many items landed in each group, and how many were left over?', 'What do you notice about the remainder compared to the number of groups?'],
    explanation: 'Division answers "how many in each group" (the quotient) and "how many are left over" (the remainder). The remainder is always smaller than the number of groups -- if it weren\'t, one more full item could still be shared out.',
    realWorldApplications: ['Splitting a bill equally among friends', 'A teacher handing out worksheets evenly across rows', 'Packing items into boxes that hold a fixed number each'],
    extensions: ['What is the largest possible remainder when sharing among 4 groups? Why can it never reach 4?'],
    realLifeNote: 'This exact idea -- quotient and remainder -- is the foundation the Euclidean Algorithm (used to find HCF) builds on, which you can try next in the HCF & LCM Finder experiment.',
  },
  {
    id: 'exp-hcf-lcm',
    title: 'HCF & LCM Finder',
    branch: 'number-systems',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Prime Time', 'HCF and LCM'],
    simType: 'euclidean',
    defaultParams: { numberA: 48, numberB: 18 },
    paramConfig: [
      { key: 'numberA', label: 'First Number', unit: '', min: 4, max: 200, step: 1 },
      { key: 'numberB', label: 'Second Number', unit: '', min: 4, max: 200, step: 1 },
    ],
    purpose: 'Watch the real Euclidean Algorithm find the HCF of two numbers step by step -- no factor-listing required.',
    predictPrompt: 'What do you think the HCF of 48 and 18 is?',
    predictOptions: ['2', '6', '9', '18'],
    correctPredictIndex: 1,
    keyIdea: 'The Euclidean Algorithm repeatedly replaces the larger number with the remainder of dividing it by the smaller, until the remainder is 0 -- the last non-zero remainder is the HCF.',
    steps: [
      { number: 1, instruction: 'With 48 and 18, watch the algorithm compute 48 = 2 x 18 + 12, then repeat with 18 and 12.', paramChanges: { numberA: 48, numberB: 18 } },
      { number: 2, instruction: 'Now try two numbers that share no common factors at all, like 17 and 22 -- watch the HCF land on 1.', paramChanges: { numberA: 17, numberB: 22 } },
      { number: 3, instruction: 'Try your own pair of numbers with the sliders below, and check the LCM the tool computes using HCF x LCM = a x b.' },
    ],
    observationPrompts: ['How many steps did the algorithm take to reach a remainder of 0?', 'How does the LCM compare to simply multiplying the two numbers together?'],
    explanation: 'The Euclidean Algorithm works because any common factor of two numbers is also a common factor of their difference (and therefore their remainder) -- so repeatedly reducing to smaller remainders never loses the HCF, it just finds it faster.',
    realWorldApplications: ['Simplifying fractions to lowest terms using the HCF', 'Finding when two repeating events (like buses on different schedules) next coincide, using the LCM', 'Tiling a rectangular floor with the largest possible square tiles and no cutting'],
    extensions: ['Try two numbers where one is a multiple of the other -- what happens to the number of steps?'],
    realLifeNote: 'This algorithm is over 2,300 years old (first written down by Euclid around 300 BCE) and is still the fastest known general method for finding HCF -- it\'s even used inside modern cryptography software today.',
  },
  {
    id: 'exp-ap-explorer',
    title: 'Arithmetic Progression Explorer',
    branch: 'algebra',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Arithmetic Progressions', 'Arithmetic and Geometric Progression'],
    simType: 'progression',
    defaultParams: { firstTerm: 3, commonDifference: 5, numTerms: 8 },
    paramConfig: [
      { key: 'firstTerm', label: 'First Term (a)', unit: '', min: -20, max: 20, step: 1 },
      { key: 'commonDifference', label: 'Common Difference (d)', unit: '', min: -10, max: 10, step: 1 },
      { key: 'numTerms', label: 'Number of Terms (n)', unit: '', min: 2, max: 15, step: 1 },
    ],
    purpose: 'Watch an arithmetic progression build itself term by term, and see the sum formula match the real running total exactly.',
    predictPrompt: 'For the sequence 3, 8, 13, 18, ... what is the 8th term?',
    predictOptions: ['38', '43', '40', '35'],
    correctPredictIndex: 0,
    keyIdea: 'Each term of an AP is the previous term plus a fixed common difference -- the nth term is a + (n-1)d, and the sum of n terms is n/2 x (2a + (n-1)d).',
    steps: [
      { number: 1, instruction: 'With a=3, d=5, n=8, watch each term get added one at a time -- check the running sum matches the formula.' },
      { number: 2, instruction: 'Try a negative common difference, like d=-4 -- watch the sequence count DOWN instead.', paramChanges: { firstTerm: 30, commonDifference: -4, numTerms: 8 } },
      { number: 3, instruction: 'Try d=0 -- what happens to the sequence, and does the sum formula still work?' },
    ],
    observationPrompts: ['Does the tool\'s running sum match the Sn formula at every step?', 'What pattern do you notice when the common difference is negative?'],
    explanation: 'An AP is defined entirely by just two numbers -- the first term and the common difference -- because every later term is built the same simple way: add d again. That\'s exactly why the sum formula can be derived once and reused for any AP.',
    realWorldApplications: ['Calculating total savings when you deposit a fixed extra amount each month', 'Seating arrangements in a stadium where each row has a fixed number more seats than the last', 'Simple interest, which grows by the exact same amount every year'],
    extensions: ['What values of a and d would make every term in the sequence exactly equal?'],
    realLifeNote: 'The famous story of a young Carl Friedrich Gauss instantly summing 1 to 100 (by pairing 1+100, 2+99, and so on) is the exact same pairing trick this formula is built from -- see the Theorem Corner for the full walkthrough.',
  },
  {
    id: 'exp-quadratic-solver',
    title: 'Quadratic Equation Solver',
    branch: 'algebra',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Quadratic Equations'],
    simType: 'quadratic',
    defaultParams: { a: 1, b: -5, c: 6 },
    paramConfig: [
      { key: 'a', label: 'a', unit: '', min: -5, max: 5, step: 1 },
      { key: 'b', label: 'b', unit: '', min: -10, max: 10, step: 1 },
      { key: 'c', label: 'c', unit: '', min: -10, max: 10, step: 1 },
    ],
    purpose: 'Adjust a, b, and c and watch the discriminant decide -- in real time -- whether the equation has two, one, or zero real roots.',
    predictPrompt: 'For x^2 - 5x + 6 = 0, how many real roots does it have?',
    predictOptions: ['Zero real roots', 'Exactly one real root', 'Two real roots'],
    correctPredictIndex: 2,
    keyIdea: 'The discriminant (b^2 - 4ac) tells you everything before you even solve: positive means two real roots, zero means one repeated root, negative means no real roots at all.',
    steps: [
      { number: 1, instruction: 'With a=1, b=-5, c=6, check the roots the tool finds against the discriminant\'s sign.' },
      { number: 2, instruction: 'Adjust c until the discriminant hits exactly 0 -- watch the parabola just touch the x-axis at a single point.', paramChanges: { a: 1, b: -6, c: 9 } },
      { number: 3, instruction: 'Now push the discriminant negative -- notice the parabola never touches the x-axis at all.', paramChanges: { a: 1, b: 1, c: 5 } },
    ],
    observationPrompts: ['How does the parabola\'s shape change as the discriminant crosses from positive to zero to negative?', 'What do the two x-intercepts of the parabola represent?'],
    explanation: 'A quadratic\'s roots are exactly where its parabola crosses the x-axis. The discriminant measures how "wide" the plus-or-minus gap is inside the quadratic formula -- when it\'s negative, that gap becomes an imaginary number, meaning the parabola never actually reaches the x-axis.',
    realWorldApplications: ['Finding when a thrown ball returns to ground height (a projectile\'s height is a quadratic function of time)', 'Working out the dimensions of a rectangular garden given its area and a fixed amount of fencing', 'Break-even analysis in business, where profit is often a quadratic function of price'],
    extensions: ['Can you find values of a, b, c where BOTH roots are negative? Both positive?'],
    realLifeNote: 'The quadratic formula\'s core idea -- "complete the square" -- was worked out by the Persian mathematician Al-Khwarizmi in the 9th century, whose name is literally the origin of the word "algorithm".',
  },
  {
    id: 'exp-dice-probability',
    title: 'Dice Probability Simulator',
    branch: 'statistics-probability',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Probability', 'Statistics'],
    simType: 'probability',
    defaultParams: { targetSum: 7 },
    paramConfig: [
      { key: 'targetSum', label: 'Target Sum (rolling 2 dice)', unit: '', min: 2, max: 12, step: 1 },
    ],
    purpose: 'Roll two dice again and again and watch the experimental probability creep toward the true theoretical probability the more you roll.',
    predictPrompt: 'Which sum is most likely when rolling two dice: 2, 7, or 12?',
    predictOptions: ['2', '7', '12'],
    correctPredictIndex: 1,
    keyIdea: 'Probability = favourable outcomes / total possible outcomes. With two dice there are 36 equally likely outcomes, and a sum of 7 has the most ways to happen (6 of them).',
    steps: [
      { number: 1, instruction: 'Set the target sum to 7 (the default), then roll a few times and watch the experimental probability bar.' },
      { number: 2, instruction: 'Keep rolling until you\'ve done at least 30 rolls -- does the experimental probability get closer to the theoretical one?' },
      { number: 3, instruction: 'Now try target sum 12 (only possible one way: 6+6) and compare how rare it is to hit.', paramChanges: { targetSum: 12 } },
    ],
    observationPrompts: ['After many rolls, how close did your experimental probability get to the theoretical value?', 'Why is a sum of 7 so much more common than a sum of 2 or 12?'],
    explanation: 'A sum of 7 can be made 6 different ways (1+6, 2+5, 3+4, 4+3, 5+2, 6+1), while a sum of 12 can only be made 1 way (6+6) -- more ways to happen means higher probability, exactly what "favourable outcomes over total outcomes" measures.',
    realWorldApplications: ['Casino and board games are designed entirely around these exact probabilities', 'Insurance companies price policies using the same favourable-over-total logic at a much larger scale', 'Quality control sampling uses the same law of large numbers this simulator demonstrates'],
    extensions: ['Which two DIFFERENT target sums have exactly the same probability as each other? Why?'],
    realLifeNote: 'This "experimental probability approaches theoretical probability with more trials" idea is called the Law of Large Numbers -- it\'s the entire mathematical reason casinos reliably profit even though any single gambler might win big on any single bet.',
  },
  {
    id: 'exp-linear-grapher',
    title: 'Linear Equation Grapher',
    branch: 'geometry',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Coordinate Geometry', 'Pair of Linear Equations in Two Variables'],
    simType: 'graph',
    defaultParams: { slope: 2, intercept: 1 },
    paramConfig: [
      { key: 'slope', label: 'Slope (m)', unit: '', min: -5, max: 5, step: 0.5 },
      { key: 'intercept', label: 'y-Intercept (c)', unit: '', min: -8, max: 8, step: 1 },
    ],
    purpose: 'Adjust the slope and intercept of y = mx + c and watch the line on the grid respond exactly as the algebra predicts.',
    predictPrompt: 'If you increase the slope (m) while keeping c the same, what happens to the line?',
    predictOptions: ['It shifts up or down without changing angle', 'It gets steeper (or steeper downward)', 'Nothing changes'],
    correctPredictIndex: 1,
    keyIdea: 'In y = mx + c, m controls the line\'s steepness and direction, and c controls exactly where it crosses the y-axis -- the two are completely independent of each other.',
    steps: [
      { number: 1, instruction: 'With m=2, c=1, check where the line crosses the y-axis -- it should exactly match c.' },
      { number: 2, instruction: 'Keep c fixed and change only the slope from 2 down to -2 -- watch the line flip direction through zero.', paramChanges: { slope: -2, intercept: 1 } },
      { number: 3, instruction: 'Now keep the slope fixed and slide the intercept up and down -- confirm the line only shifts, never rotates.', paramChanges: { slope: -2, intercept: 6 } },
    ],
    observationPrompts: ['Where exactly does the line cross the y-axis, and does it match the c value?', 'What happens to the line when the slope is exactly 0?'],
    explanation: 'The slope m is a rate -- how much y changes for every 1 unit x changes -- so it entirely controls the line\'s tilt. The intercept c is just a starting point, a single fixed offset, which is why changing it only slides the line up or down without ever rotating it.',
    realWorldApplications: ['A taxi fare that starts at a fixed amount (c) and adds a fixed rate per kilometre (m)', 'Converting between Celsius and Fahrenheit, which is a straight-line relationship', 'Predicting cost from quantity when there\'s a fixed setup fee plus a per-unit charge'],
    extensions: ['What slope and intercept would make the line pass through both the origin AND the point (2, 6)?'],
    realLifeNote: 'This y = mx + c form is sometimes called the "slope-intercept form" -- it\'s the single most-used way to write a straight line\'s equation because both constants can be read straight off a graph at a glance.',
  },
];
