import { PhysicsExperiment } from './physicsTypes';

// Mechanics MVP -- the first three flagship experiments for Physics Lab.
// Every predict-question has exactly one verifiably correct answer, every
// formula is the standard CBSE/ICSE textbook form, and every apparatus
// referenced exists in physicsEquipment.ts. More branches (Optics,
// Electricity, Waves & Sound) are a deliberate next pass -- see the Physics
// Lab plan -- rather than shipped half-finished here.
export const PHYSICS_EXPERIMENTS: PhysicsExperiment[] = [
  {
    id: 'exp-simple-pendulum',
    title: 'The Simple Pendulum',
    branch: 'mechanics',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Simple Pendulum', 'Oscillatory Motion', 'Time Period'],
    simType: 'pendulum',
    defaultParams: { length: 1.0, gravity: 9.8, amplitudeDeg: 15, mass: 0.2 },
    paramConfig: [
      { key: 'length', label: 'String Length', unit: 'm', min: 0.2, max: 3, step: 0.1 },
      { key: 'gravity', label: 'Gravity (g)', unit: 'm/s²', min: 1, max: 25, step: 0.1 },
      { key: 'amplitudeDeg', label: 'Swing Amplitude', unit: '°', min: 5, max: 80, step: 1 },
      { key: 'mass', label: 'Bob Mass', unit: 'kg', min: 0.05, max: 1, step: 0.05 },
    ],
    apparatusIds: ['pendulum-stand', 'pendulum-bob', 'pendulum-string', 'stopwatch', 'meter-scale'],
    hasSmallAngleToggle: true,
    purpose: "To study how a simple pendulum's time period depends on its string length, and to verify it does NOT depend on the bob's mass or (for small swings) the amplitude.",
    predictPrompt: "If you double the pendulum's string length, what happens to its time period (the time for one full swing)?",
    predictOptions: ['It exactly doubles', 'It increases, but by less than double', 'It stays exactly the same', 'It halves'],
    correctPredictIndex: 1,
    formula: 'T = 2π√(L/g)',
    formulaVars: ['length', 'gravity'],
    steps: [
      { number: 1, instruction: 'Release the pendulum at its default 1.0m length and watch it swing.', action: 'release' },
      { number: 2, instruction: 'Note the time period shown on the stopwatch readout.', action: 'observe' },
      { number: 3, instruction: 'Now double the length to 2.0m -- predict what happens to the period before you watch.', paramChanges: { length: 2.0 }, action: 'observe', hint: 'T is proportional to the square root of L, not L itself.' },
      { number: 4, instruction: "Keep the length the same, but try changing the bob's mass. Does the time period change?", paramChanges: { mass: 0.8 }, action: 'observe', hint: 'Look closely at the stopwatch readout, not just the (now bigger-looking) bob.' },
    ],
    observationPrompts: [
      'What happened to the time period when you doubled the length?',
      "Did changing the bob's mass change the time period? Why do you think that is?",
    ],
    explanation: "A simple pendulum's time period only depends on its length and the local gravity -- T=2π√(L/g). Mass drops out of the formula entirely: a heavier bob feels a bigger gravitational pull, but it also has more inertia resisting that pull, and the two effects cancel exactly. This is the same insight behind Galileo's (later confirmed by Newton) observation that all objects fall at the same rate regardless of mass, ignoring air resistance.",
    realWorldApplications: [
      'Pendulum clocks use this exact relationship -- a fixed length gives a fixed, reliable time period to keep accurate time.',
      'Seismometers historically used a similar swinging mass on a pivot to detect and record earthquake vibrations.',
    ],
    safetyNotes: ['In a real lab, keep the swing angle small and stand clear of the swinging bob\'s path.'],
    extensions: [
      'What time period would a 4m long pendulum have on Earth?',
      "Would this same pendulum swing faster or slower on the Moon, where gravity is about 1/6th of Earth's?",
    ],
    realLifeNote: 'Grandfather clocks are tuned by adjusting the pendulum\'s length, not its bob\'s weight -- exactly what this experiment demonstrates.',
  },
  {
    id: 'exp-hookes-law',
    title: "Hooke's Law & the Oscillating Spring",
    branch: 'mechanics',
    gradeBand: 'plusTwo',
    board: 'both',
    chapterTags: ["Hooke's Law", 'Elasticity', 'Simple Harmonic Motion'],
    simType: 'spring',
    defaultParams: { mass: 0.5, springConstant: 20, amplitude: 0.15 },
    paramConfig: [
      { key: 'mass', label: 'Hanging Mass', unit: 'kg', min: 0.1, max: 2, step: 0.1 },
      { key: 'springConstant', label: 'Spring Constant (k)', unit: 'N/m', min: 5, max: 60, step: 1 },
      { key: 'amplitude', label: 'Pull Distance', unit: 'm', min: 0.05, max: 0.3, step: 0.01 },
    ],
    apparatusIds: ['pendulum-stand', 'spring-coil', 'mass-hanger', 'stopwatch', 'meter-scale'],
    purpose: "To verify Hooke's Law (the restoring force is proportional to displacement) and to see how a spring-mass system's oscillation period depends on mass and spring stiffness.",
    predictPrompt: 'If you swap in a stiffer spring (higher spring constant k) but keep the same mass, what happens to how fast it oscillates?',
    predictOptions: ['It oscillates faster (shorter time period)', 'It oscillates slower (longer time period)', 'The speed of oscillation stays exactly the same', 'It stops oscillating'],
    correctPredictIndex: 0,
    formula: 'F = -kx,  T = 2π√(m/k)',
    formulaVars: ['mass', 'springConstant'],
    steps: [
      { number: 1, instruction: 'Pull the mass down and release it -- watch the spring stretch and compress.', action: 'release' },
      { number: 2, instruction: 'Note the time period of one full oscillation.', action: 'observe' },
      { number: 3, instruction: 'Now try a stiffer spring -- predict first, then watch.', paramChanges: { springConstant: 45 }, action: 'observe' },
      { number: 4, instruction: 'Reset the spring, then try doubling the hanging mass instead.', paramChanges: { springConstant: 20, mass: 1.0 }, action: 'observe', hint: 'More mass means more inertia resisting the spring\'s pull.' },
    ],
    observationPrompts: [
      'Did a stiffer spring make the oscillation faster or slower?',
      'Did more mass make the oscillation faster or slower? Why does that make physical sense?',
    ],
    explanation: "Hooke's Law says the spring's restoring force is directly proportional to how far it's stretched or compressed: F=-kx (the minus sign just means the force always pulls back toward the resting position). When you combine that restoring force with Newton's second law, the resulting motion is Simple Harmonic Motion with period T=2π√(m/k) -- a stiffer spring (higher k) pulls back harder and oscillates faster, while more mass resists that pull and oscillates slower.",
    realWorldApplications: [
      "A car's suspension springs use this exact relationship, tuned so the ride absorbs bumps smoothly instead of bouncing forever.",
      'Spring scales (like a kitchen weighing scale) use Hooke\'s Law directly -- the amount of stretch tells you the weight.',
    ],
    safetyNotes: ["Don't stretch a real spring past its elastic limit -- it can snap back suddenly, and once overstretched it won't return to its original shape."],
    extensions: [
      'If you quadruple the spring constant, by what factor does the time period change?',
      'What would happen to the oscillation if there were no gravity at all -- would the spring still oscillate?',
    ],
    realLifeNote: 'Bathroom weighing scales, pogo sticks, and trampolines are all everyday applications of the same F=-kx relationship you just tested.',
  },
  {
    id: 'exp-projectile-motion',
    title: 'Projectile Motion',
    branch: 'mechanics',
    gradeBand: 'plusTwo',
    board: 'both',
    chapterTags: ['Projectile Motion', 'Motion in a Plane', 'Kinematics'],
    simType: 'projectile',
    defaultParams: { speed: 15, angleDeg: 45, gravity: 9.8 },
    paramConfig: [
      { key: 'speed', label: 'Launch Speed', unit: 'm/s', min: 5, max: 30, step: 1 },
      { key: 'angleDeg', label: 'Launch Angle', unit: '°', min: 5, max: 90, step: 1 },
      { key: 'gravity', label: 'Gravity (g)', unit: 'm/s²', min: 1, max: 25, step: 0.1 },
    ],
    apparatusIds: ['launcher', 'ball', 'meter-scale', 'stopwatch'],
    purpose: 'To study how launch angle and speed affect a projectile\'s range, maximum height, and time of flight -- and to find the angle that gives the maximum range.',
    predictPrompt: 'At which launch angle does a projectile travel the farthest horizontal distance, for the same launch speed?',
    predictOptions: ['15 degrees', '45 degrees', '60 degrees', '90 degrees (straight up)'],
    correctPredictIndex: 1,
    formula: 'R = (v² sin(2θ)) / g',
    formulaVars: ['speed', 'angleDeg', 'gravity'],
    steps: [
      { number: 1, instruction: 'Launch the ball at the default 45° angle and watch its full arc.', action: 'release' },
      { number: 2, instruction: 'Note the range (horizontal distance) it landed at.', action: 'observe' },
      { number: 3, instruction: 'Now try a lower angle -- predict whether the range increases or decreases.', paramChanges: { angleDeg: 20 }, action: 'observe' },
      { number: 4, instruction: 'Now try a higher angle.', paramChanges: { angleDeg: 70 }, action: 'observe', hint: 'Compare this range to the 45° launch -- which was farther?' },
    ],
    observationPrompts: [
      'Which angle gave the longest range: 20°, 45°, or 70°?',
      'What do you notice about the ranges for 20° and 70°? (Hint: they add up to 90°.)',
    ],
    explanation: 'A projectile\'s horizontal and vertical motions are independent: horizontally it moves at constant velocity (no horizontal force, ignoring air resistance), while vertically it accelerates downward under gravity exactly like a dropped object. Combining both gives the range formula R=(v²sin2θ)/g, which is maximized when sin(2θ)=1, i.e. when 2θ=90°, so θ=45°. Angles that add up to 90° (like 20° and 70°) always give the exact same range as each other, just with different heights and flight times.',
    realWorldApplications: [
      'Sports like basketball, football, and javelin throw all involve athletes intuitively optimizing launch angle for distance or accuracy.',
      'Artillery and fire-fighting water cannons are aimed using these same range calculations.',
    ],
    safetyNotes: ['Real projectile launchers should always be aimed in a safe, clear direction, never at people.'],
    extensions: [
      'What launch angle would you use if you wanted maximum height instead of maximum range?',
      'How would the range change on the Moon, where gravity is about 1/6th of Earth\'s?',
    ],
    realLifeNote: 'The next time you watch a basketball free throw, notice the arc -- players instinctively use an angle well above 45° because releasing above head height changes the ideal angle from the textbook case.',
  },
  {
    id: 'exp-magnets',
    title: 'Magnets: Attract or Repel?',
    branch: 'electricity',
    gradeBand: 'junior',
    board: 'both',
    chapterTags: ['Magnets', 'Fun with Magnets', 'Poles'],
    simType: 'magnet',
    defaultParams: { orientation: 0 },
    paramConfig: [
      { key: 'orientation', label: 'Facing Poles', unit: '', min: 0, max: 1, step: 1 },
    ],
    apparatusIds: ['bar-magnet'],
    purpose: 'To find out what happens when you bring two magnets close together, facing each other in different ways.',
    predictPrompt: 'If you bring two magnets together with their North poles facing each other, what happens?',
    predictOptions: ['They attract (pull together)', 'They repel (push apart)', 'Nothing happens at all', 'They start spinning'],
    correctPredictIndex: 1,
    formula: 'Like poles repel, unlike poles attract.',
    formulaVars: ['orientation'],
    steps: [
      { number: 1, instruction: 'Set the sliding magnet to face North-to-North (like poles) and release it.', paramChanges: { orientation: 0 }, action: 'release' },
      { number: 2, instruction: 'Watch what happens as it gets close to the fixed magnet.', action: 'observe' },
      { number: 3, instruction: 'Now flip it so a North pole faces a South pole, and release again.', paramChanges: { orientation: 1 }, action: 'observe' },
    ],
    observationPrompts: [
      'What happened when like poles (N facing N) were brought close together?',
      'What happened when opposite poles (N facing S) were brought close together?',
    ],
    explanation: 'Every magnet has two ends, called poles -- North and South. Two poles that are the same (North-North or South-South) push each other away, while two different poles (North-South) pull toward each other. This happens because of the invisible magnetic field surrounding every magnet, which is strongest at its poles.',
    realWorldApplications: [
      'Compasses work because their needle is a tiny magnet that lines up with the Earth\'s own huge magnetic field.',
      'Fridge doors, some bags, and pencil cases use magnetic clasps that snap shut using this same attraction.',
    ],
    safetyNotes: ['Keep strong magnets away from credit cards, phones, and other electronics -- they can erase or damage them.'],
    extensions: [
      'What do you think happens if you bring THREE magnets together in a row?',
      'Can you think of a machine or toy at home that uses magnets?',
    ],
    realLifeNote: 'Maglev (magnetic levitation) trains use extremely powerful versions of this exact repel/attract effect to float above the track and glide forward with almost no friction.',
  },
  {
    id: 'exp-plane-mirror',
    title: 'Laws of Reflection: Light & Mirrors',
    branch: 'optics',
    gradeBand: 'middle',
    board: 'both',
    chapterTags: ['Light', 'Reflection', 'Laws of Reflection'],
    simType: 'mirror',
    defaultParams: { incidenceAngleDeg: 40 },
    paramConfig: [
      { key: 'incidenceAngleDeg', label: 'Angle of Incidence', unit: '°', min: 5, max: 80, step: 1 },
    ],
    apparatusIds: ['plane-mirror', 'light-ray-source'],
    purpose: 'To verify the Laws of Reflection: the incident ray, reflected ray, and normal all lie in the same plane, and the angle of incidence always equals the angle of reflection.',
    predictPrompt: 'If a light ray hits a flat mirror at 30° from the normal (the imaginary perpendicular line), at what angle does it reflect?',
    predictOptions: ['15°', '30°', '60°', '90°'],
    correctPredictIndex: 1,
    formula: 'Angle of Incidence = Angle of Reflection',
    formulaVars: ['incidenceAngleDeg'],
    steps: [
      { number: 1, instruction: 'Aim the ray box at the mirror at the default angle and watch the reflected ray.', action: 'release' },
      { number: 2, instruction: 'Compare the incident and reflected angles either side of the normal line.', action: 'observe' },
      { number: 3, instruction: 'Now try a much smaller angle -- predict the reflected angle before you look.', paramChanges: { incidenceAngleDeg: 15 }, action: 'observe' },
      { number: 4, instruction: 'Now try a much larger angle.', paramChanges: { incidenceAngleDeg: 70 }, action: 'observe' },
    ],
    observationPrompts: [
      'Did the reflected angle ever differ from the incident angle?',
      'What happens to the reflected ray as the incident angle gets close to 0° (light hitting the mirror almost straight on)?',
    ],
    explanation: "The Laws of Reflection state that the incident ray, the reflected ray, and the normal (the perpendicular line at the point of contact) all lie in the same flat plane, and the angle between the incident ray and the normal always exactly equals the angle between the reflected ray and the normal. This holds true no matter what angle the light arrives at.",
    realWorldApplications: [
      'Periscopes (used in submarines) use two angled mirrors and this exact law to let you see over an obstacle.',
      'Bathroom and dressing mirrors, car side-mirrors, and even the mirrors inside a kaleidoscope all rely on this same predictable law.',
    ],
    safetyNotes: ['Never aim a laser pointer or bright light source directly into anyone\'s eyes, including your own, when reflecting light.'],
    extensions: [
      'What angle would the reflected ray be at if the incident ray hit the mirror at exactly 0° (straight on)?',
      'How would a curved (not flat) mirror change this experiment?',
    ],
    realLifeNote: 'Every time you check your reflection, you\'re relying on this exact law -- your image appears to be exactly as far "behind" the mirror as you are standing in front of it.',
  },
  {
    id: 'exp-lever-moments',
    title: 'The Lever & Principle of Moments',
    branch: 'mechanics',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Levers', 'Moments', 'Simple Machines'],
    simType: 'lever',
    defaultParams: { leftForce: 20, leftDistance: 2, rightForce: 20, rightDistance: 2 },
    paramConfig: [
      { key: 'leftForce', label: 'Left Weight', unit: 'N', min: 5, max: 50, step: 5 },
      { key: 'leftDistance', label: 'Left Distance', unit: 'm', min: 0.5, max: 4, step: 0.5 },
      { key: 'rightForce', label: 'Right Weight', unit: 'N', min: 5, max: 50, step: 5 },
      { key: 'rightDistance', label: 'Right Distance', unit: 'm', min: 0.5, max: 4, step: 0.5 },
    ],
    apparatusIds: ['lever-beam', 'lever-pivot', 'lever-weight'],
    purpose: 'To verify the Principle of Moments: a lever balances exactly when the clockwise turning effect equals the anticlockwise turning effect.',
    predictPrompt: 'A 20N weight sits 2m from the pivot. Where should you place a 40N weight on the other side to balance it?',
    predictOptions: ['0.5m from the pivot', '1m from the pivot', '2m from the pivot', '4m from the pivot'],
    correctPredictIndex: 1,
    formula: 'F1 x d1 = F2 x d2 (clockwise moment = anticlockwise moment)',
    formulaVars: ['leftForce', 'leftDistance', 'rightForce', 'rightDistance'],
    steps: [
      { number: 1, instruction: 'Start with equal weights at equal distances and watch the beam settle.', action: 'release' },
      { number: 2, instruction: 'Notice the beam balances perfectly -- equal moments on both sides.', action: 'observe' },
      { number: 3, instruction: 'Now double the right weight -- predict which way it tips.', paramChanges: { rightForce: 40 }, action: 'observe' },
      { number: 4, instruction: 'Try to re-balance it by moving the right weight closer to the pivot instead.', paramChanges: { rightForce: 40, rightDistance: 1 }, action: 'observe', hint: '20N x 2m = 40N x 1m -- both moments equal 40.' },
    ],
    observationPrompts: [
      'What happened to the beam when you doubled one side\'s weight without changing anything else?',
      'How did moving the heavier weight closer to the pivot affect the balance?',
    ],
    explanation: 'A lever balances when the turning effect (called a "moment") on each side is equal. A moment is calculated as force multiplied by its distance from the pivot: Moment = Force x Distance. This means a smaller weight placed farther from the pivot can balance a larger weight placed closer to it -- exactly the principle behind a see-saw, where a lighter person can balance a heavier one by sitting farther from the middle.',
    realWorldApplications: [
      'A see-saw, a wheelbarrow, a pair of scissors, and a bottle opener are all everyday levers using this exact principle.',
      'Old-fashioned balance scales use this same idea to measure unknown weights against known ones.',
    ],
    safetyNotes: ['In a real lab, keep fingers clear of the beam\'s pivot point while weights are being added or removed.'],
    extensions: [
      'If a 60N weight is 1m from the pivot, how far from the pivot should a 30N weight go to balance it?',
      'Why can a long crowbar let you lift a heavy rock with much less force than lifting it directly?',
    ],
    realLifeNote: 'Archimedes\' famous (if exaggerated) claim -- "Give me a lever long enough and a place to stand, and I will move the Earth" -- was a boast about exactly this principle: a long enough lever arm can balance almost any force.',
  },
  {
    id: 'exp-archimedes-buoyancy',
    title: "Sink or Float: Archimedes' Principle",
    branch: 'mechanics',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Floatation', "Archimedes' Principle", 'Density'],
    simType: 'buoyancy',
    defaultParams: { objectDensity: 700, fluidDensity: 1000 },
    paramConfig: [
      { key: 'objectDensity', label: 'Object Density', unit: 'kg/m³', min: 200, max: 2000, step: 50 },
      { key: 'fluidDensity', label: 'Fluid Density', unit: 'kg/m³', min: 700, max: 1400, step: 25 },
    ],
    apparatusIds: ['beaker-water', 'density-block'],
    purpose: "To verify Archimedes' Principle: whether an object floats or sinks depends on how its density compares to the fluid's, not on its total weight.",
    predictPrompt: 'A block has a density of 1200 kg/m³. Will it float or sink in water (density 1000 kg/m³)?',
    predictOptions: ['Float, mostly above the surface', 'Sink to the bottom', 'Stay perfectly still wherever it\'s placed', 'It depends only on its shape, not density'],
    correctPredictIndex: 1,
    formula: 'Object floats if its density < fluid density',
    formulaVars: ['objectDensity', 'fluidDensity'],
    steps: [
      { number: 1, instruction: 'Lower the block (700 kg/m³, less dense than water) into the beaker.', action: 'release' },
      { number: 2, instruction: 'Notice how much of it stays above the water line.', action: 'observe' },
      { number: 3, instruction: 'Now increase the block\'s density past water\'s -- predict what happens first.', paramChanges: { objectDensity: 1200 }, action: 'observe' },
      { number: 4, instruction: 'Try a denser fluid instead, like salt water, with the same dense block.', paramChanges: { objectDensity: 1200, fluidDensity: 1250 }, action: 'observe', hint: 'The block is now LESS dense than the fluid again.' },
    ],
    observationPrompts: [
      'What fraction of the block stayed above the water when it floated?',
      'Why did the same 1200 kg/m³ block behave differently in plain water versus the denser salt water?',
    ],
    explanation: "Archimedes' Principle says a floating or submerged object experiences an upward buoyant force equal to the weight of the fluid it displaces. Practically, this means an object floats if it's LESS dense than the fluid (it displaces its own weight in fluid before it's fully submerged), and sinks if it's MORE dense (even displacing its full volume isn't enough fluid weight to hold it up).",
    realWorldApplications: [
      'A massive steel ship floats because its hollow hull shape gives it a low AVERAGE density, even though solid steel itself sinks.',
      'Submarines control tanks that fill with water or air to precisely adjust their average density and dive or surface on command.',
    ],
    safetyNotes: [],
    extensions: [
      'Why does a person float more easily in the ocean (salt water) than in a swimming pool (fresh water)?',
      'An ice cube floats in water -- what does that tell you about ice\'s density compared to liquid water?',
    ],
    realLifeNote: 'Legend says Archimedes discovered this principle in his bathtub, realizing the water that overflowed as he got in equaled his own submerged volume -- and ran through the streets shouting "Eureka!" ("I have found it!").',
  },
  {
    id: 'exp-ohms-law',
    title: "Ohm's Law: Current, Voltage & Resistance",
    branch: 'electricity',
    gradeBand: 'senior',
    board: 'both',
    chapterTags: ['Electricity', "Ohm's Law", 'Current & Resistance'],
    simType: 'circuit',
    defaultParams: { voltage: 6, resistance: 3 },
    paramConfig: [
      { key: 'voltage', label: 'Battery Voltage', unit: 'V', min: 1, max: 12, step: 1 },
      { key: 'resistance', label: 'Resistance', unit: 'Ω', min: 1, max: 12, step: 1 },
    ],
    apparatusIds: ['battery', 'bulb', 'connecting-wire'],
    purpose: "To verify Ohm's Law: the current flowing through a circuit is directly proportional to voltage and inversely proportional to resistance.",
    predictPrompt: 'If you double the resistance in a circuit while keeping the voltage the same, what happens to the current?',
    predictOptions: ['It doubles', 'It is cut in half', 'It stays exactly the same', 'It drops to zero'],
    correctPredictIndex: 1,
    formula: 'V = I x R  (Ohm\'s Law)',
    formulaVars: ['voltage', 'resistance'],
    steps: [
      { number: 1, instruction: 'Close the circuit at the default settings and watch the bulb light up.', action: 'release' },
      { number: 2, instruction: 'Note the current reading and how bright the bulb glows.', action: 'observe' },
      { number: 3, instruction: 'Now double the resistance -- predict what happens to the bulb before you look.', paramChanges: { resistance: 6 }, action: 'observe' },
      { number: 4, instruction: 'Instead, try doubling the voltage from the original setting.', paramChanges: { voltage: 12, resistance: 3 }, action: 'observe' },
    ],
    observationPrompts: [
      'What happened to the bulb\'s brightness when you doubled the resistance?',
      'What happened to the bulb\'s brightness when you doubled the voltage instead?',
    ],
    explanation: "Ohm's Law states V=IR, where V is voltage (the electrical \"push\"), I is current (the flow of charge), and R is resistance (how much the circuit opposes that flow). Rearranged as I=V/R, this shows current is directly proportional to voltage (more push, more flow) and inversely proportional to resistance (more opposition, less flow) -- doubling the resistance exactly halves the current if voltage stays the same.",
    realWorldApplications: [
      'Dimmer switches work by adding adjustable resistance into the lighting circuit, directly reducing the current and brightness.',
      'Electrical fuses are designed to melt and break the circuit if current gets dangerously high, protecting the wiring and devices.',
    ],
    safetyNotes: ['Never touch bare wires or test a real circuit with mains household electricity -- always use safe, low-voltage battery cells for hands-on circuit experiments.'],
    extensions: [
      'If a circuit has a 9V battery and 3Ω of resistance, what current flows through it?',
      'What resistance would you need to limit the current to exactly 1A from a 6V battery?',
    ],
    realLifeNote: 'Every charging cable, phone charger, and USB port is designed around exactly this relationship, carefully controlling voltage and resistance to deliver a safe, steady current to your device.',
  },
];
