import { ChemReagent } from './types';

// Every reagent used by any curated experiment in experiments.ts. Kept as
// one flat list (not per-experiment) so the same bottle/label design is
// reused everywhere in the lab-bench UI.
export const CHEM_REAGENTS: ChemReagent[] = [
  { id: 'vinegar', name: 'Vinegar', formulaOrDescription: 'Dilute acetic acid, CH3COOH (~5%)' },
  { id: 'baking-soda', name: 'Baking Soda', formulaOrDescription: 'Sodium bicarbonate, NaHCO3 (solid)' },
  { id: 'baking-soda-solution', name: 'Baking Soda Solution', formulaOrDescription: 'NaHCO3 dissolved in water' },
  { id: 'red-cabbage-indicator', name: 'Red Cabbage Indicator', formulaOrDescription: 'Natural pH indicator extracted from boiled red cabbage leaves' },
  { id: 'lemon-juice', name: 'Lemon Juice', formulaOrDescription: 'A common weak, natural acid' },
  { id: 'soap-solution', name: 'Soap Solution', formulaOrDescription: 'A common mild alkaline (basic) household solution' },
  { id: 'iron-nail', name: 'Iron Nail', formulaOrDescription: 'A clean iron nail, Fe' },
  { id: 'water', name: 'Water', formulaOrDescription: 'H2O' },
  { id: 'cooking-oil', name: 'Cooking Oil', formulaOrDescription: 'Seals out air/moisture -- used as a control' },
  { id: 'salt', name: 'Common Salt', formulaOrDescription: 'Sodium chloride, NaCl (solid)' },
  { id: 'sugar', name: 'Sugar', formulaOrDescription: 'Sucrose, C12H22O11 (solid)' },
  { id: 'copper-sulphate-solution', name: 'Copper Sulphate Solution', formulaOrDescription: 'CuSO4 dissolved in water -- pale blue', hazardNote: 'Mildly irritant -- avoid skin/eye contact, wash hands after.' },
  { id: 'dilute-hcl', name: 'Dilute Hydrochloric Acid', formulaOrDescription: 'Dilute HCl', hazardNote: 'Corrosive at higher concentrations -- always use the dilute, lab-safe strength and wear goggles for the real version.' },
  { id: 'dilute-naoh', name: 'Dilute Sodium Hydroxide', formulaOrDescription: 'Dilute NaOH', hazardNote: 'Corrosive at higher concentrations -- always use the dilute, lab-safe strength and wear goggles for the real version.' },
  { id: 'universal-indicator', name: 'Universal Indicator', formulaOrDescription: 'A mixed indicator that turns a different color across the full pH range' },
  { id: 'zinc-granules', name: 'Zinc Granules', formulaOrDescription: 'Zn (solid)' },
  { id: 'marble-chips', name: 'Marble Chips', formulaOrDescription: 'Calcium carbonate, CaCO3 (solid)' },
  { id: 'limewater', name: 'Limewater', formulaOrDescription: 'A clear solution of calcium hydroxide, Ca(OH)2' },
  { id: 'hydrogen-peroxide', name: 'Hydrogen Peroxide Solution', formulaOrDescription: 'Dilute H2O2', hazardNote: 'Can bleach skin/fabric -- handle the dilute solution with care.' },
  { id: 'manganese-dioxide', name: 'Manganese Dioxide', formulaOrDescription: 'MnO2 -- acts as a catalyst, is not used up in the reaction' },
  { id: 'dilute-sulphuric-acid', name: 'Dilute Sulphuric Acid', formulaOrDescription: 'Dilute H2SO4, used here as the electrolyte for electrolysis', hazardNote: 'Corrosive at higher concentrations -- only the dilute, lab-safe strength is used.' },
  { id: 'sodium-chloride-flame-sample', name: 'Sodium Chloride Sample', formulaOrDescription: 'NaCl -- for the flame test (sodium gives a strong yellow flame)' },
  { id: 'potassium-chloride-flame-sample', name: 'Potassium Chloride Sample', formulaOrDescription: 'KCl -- for the flame test (potassium gives a lilac flame)' },
  { id: 'calcium-chloride-flame-sample', name: 'Calcium Chloride Sample', formulaOrDescription: 'CaCl2 -- for the flame test (calcium gives a brick-red flame)' },
  { id: 'copper-chloride-flame-sample', name: 'Copper Chloride Sample', formulaOrDescription: 'CuCl2 -- for the flame test (copper gives a blue-green flame)' },
  { id: 'oxalic-acid-solution', name: 'Standard Oxalic Acid Solution', formulaOrDescription: 'A precisely known concentration of (COOH)2, used as the reference standard in this titration' },
  { id: 'sodium-hydroxide-solution', name: 'Sodium Hydroxide Solution', formulaOrDescription: 'NaOH solution of unknown concentration -- what the titration finds out', hazardNote: 'Corrosive at higher concentrations -- only the dilute, lab-safe strength is used.' },
  { id: 'phenolphthalein', name: 'Phenolphthalein Indicator', formulaOrDescription: 'Colorless in acid, pink in base -- the indicator used in acid-base titrations' },
  { id: 'unknown-salt-sample', name: 'Unknown Salt Sample', formulaOrDescription: 'A solid salt whose cation and anion the student must identify systematically' },
  { id: 'barium-chloride-solution', name: 'Barium Chloride Solution', formulaOrDescription: 'BaCl2 -- used to test for a sulphate or carbonate ion' },
  { id: 'silver-nitrate-solution', name: 'Silver Nitrate Solution', formulaOrDescription: 'AgNO3 -- used to test for a chloride ion', hazardNote: 'Stains skin on contact -- handle with gloves in the real version.' },
  { id: 'zinc-electrode', name: 'Zinc Electrode Strip', formulaOrDescription: 'A strip of solid zinc metal' },
  { id: 'copper-electrode', name: 'Copper Electrode Strip', formulaOrDescription: 'A strip of solid copper metal' },
  { id: 'zinc-sulphate-solution', name: 'Zinc Sulphate Solution', formulaOrDescription: 'ZnSO4 dissolved in water' },
  { id: 'salt-bridge', name: 'Salt Bridge', formulaOrDescription: 'A tube of gel/filter paper soaked in KNO3 or KCl solution that completes the electrical circuit between the two half-cells' },
  { id: 'ethanol', name: 'Ethanol', formulaOrDescription: 'C2H5OH -- a simple alcohol' },
  { id: 'acetic-acid', name: 'Glacial Acetic Acid', formulaOrDescription: 'Concentrated CH3COOH', hazardNote: 'Corrosive and has a sharp smell -- the real version needs a fume hood and adult supervision.' },
  { id: 'conc-sulphuric-acid', name: 'Concentrated Sulphuric Acid (catalyst)', formulaOrDescription: 'Used here only as a catalyst, in a small amount', hazardNote: 'Highly corrosive -- this step is teacher-demonstration-only in a real lab, never student-handled.' },
];
