import { RoboticsExperiment } from './roboticsExperimentTypes';

// 11 real hands-on experiments -- 8 newly built around formulas verified in
// roboticsEngineeringEngine.ts (full PID, 2-link inverse kinematics, real
// ITU Morse timing, real note-frequency math, real 8-bit PWM), plus 3 of
// the existing 7 playable simulations (originally built for the
// Applications Gallery, buried one-per-card there) surfaced here as their
// own first-class experiments, per the explicit instruction to keep what
// already exists rather than throw it away. Every experiment is a real
// design-and-iterate loop: change a parameter, run it, see a real result,
// change it again -- not a single slider reading a single number.
export const ROBOTICS_EXPERIMENTS: RoboticsExperiment[] = [
  {
    id: 'exp-pid-line-follower',
    category: 'control-systems',
    name: 'PID Line-Follower Tuning Lab',
    tagline: 'The single most common first exercise in any real robotics course -- and the reason PID is worth learning at all.',
    overview: 'Tune a real PID controller\'s three gains and watch a simulated two-wheeled robot follow a curvy line -- too little correction and it drifts off, too much and it oscillates wildly.',
    whatYoullDo: [
      'Start with all gains at zero and watch the robot fail to follow the track at all.',
      'Raise Kp until the robot roughly tracks the line but visibly overshoots every curve.',
      'Add Kd to damp that overshoot, then a small Ki to correct any steady drift -- exactly the real tuning process engineers use.',
    ],
    realWorldTieIn: 'This is the exact algorithm (Proportional-Integral-Derivative control) running inside real line-following robots, drones holding altitude, 3D printer hotends, and cruise control systems -- one formula, everywhere.',
    componentsUsed: ['IR line sensor (reused from Fundamentals)', 'Differential-drive wheels', 'PID controller'],
    outputType: 'motion',
    difficulty: 'intermediate',
    playgroundType: 'pid-line-follower',
  },
  {
    id: 'exp-arm-reach-grab',
    category: 'kinematics-motion',
    name: 'Robotic Arm: Reach and Grab',
    tagline: 'Real inverse kinematics -- click a target, the arm solves its own joint angles to reach it.',
    overview: 'Command a real 2-joint robotic arm by clicking anywhere in its reach -- the arm solves the actual inverse-kinematics math to work out the two joint angles needed, then physically reaches, grips, and moves a real object to a drop zone.',
    whatYoullDo: [
      'Click a target within the arm\'s reach and watch it solve its own joint angles to get there.',
      'Try clicking outside the arm\'s maximum reach -- watch it honestly report the target as unreachable, exactly like a real robot would.',
      'Chain a full pick-and-place: reach the object, grip, lift, then reach the drop zone and release.',
    ],
    realWorldTieIn: 'The exact 2-link inverse-kinematics solution used here (Craig-style elbow-down solution) is the same class of math that runs inside every real industrial pick-and-place arm, just extended to more joints.',
    componentsUsed: ['2-joint robotic arm', 'Servo motors (shoulder + elbow)', 'Gripper'],
    outputType: 'motion',
    difficulty: 'intermediate',
    playgroundType: 'arm-reach-grab',
  },
  {
    id: 'exp-gear-design-challenge',
    category: 'mechanical-design',
    name: 'Gear Train Design Challenge',
    tagline: 'You\'re given a motor that isn\'t strong enough. Pick real gears to fix that.',
    overview: 'A task needs more torque than your motor alone can deliver -- pick input and output gear sizes from a set of real available gears to hit the required torque, and see exactly what speed you trade away to get it.',
    whatYoullDo: [
      'Read the challenge: a required torque your bare motor can\'t reach.',
      'Pick input and output gear teeth counts and watch the real achievable torque and speed update live.',
      'Discover firsthand that more torque always costs speed -- there is no combination that gives you both for free.',
    ],
    realWorldTieIn: 'This exact torque-speed tradeoff is why every geared robot -- from a robotic arm lifting a real load to a car\'s gearbox -- has to choose gear ratios deliberately, task by task.',
    componentsUsed: ['DC motor', 'Gear train (selectable teeth counts)', 'Output shaft'],
    outputType: 'visual',
    difficulty: 'beginner',
    playgroundType: 'gear-design-challenge',
    playgroundConfig: { requiredTorqueNcm: 45, inputTorqueNcm: 12, inputRPM: 300 },
  },
  {
    id: 'exp-stepper-precision',
    category: 'mechanical-design',
    name: 'Stepper Motor Precision Positioning',
    tagline: 'Command an exact angle. The motor can only move in fixed steps -- can you land exactly on target?',
    overview: 'Command a real stepper motor to a target angle using whole step counts -- unlike a servo, a stepper can only land on the specific angles its step size allows, so hitting an exact target takes real calculation, not guessing.',
    whatYoullDo: [
      'Pick a target angle and a step mode (standard 1.8 degrees/step, or half-step 0.9 degrees/step).',
      'Calculate the step count needed and watch the real dial rotate to wherever that count actually lands.',
      'See exactly how much finer half-stepping gets you, and why it\'s a genuine, real engineering option.',
    ],
    realWorldTieIn: 'This is exactly how real 3D printers and CNC machines position their axes precisely -- by counting real, discrete steps, never by "sliding" to a position the way a servo does.',
    componentsUsed: ['Stepper motor (NEMA 17 class)', 'Positioning dial'],
    outputType: 'motion',
    difficulty: 'beginner',
    playgroundType: 'stepper-precision',
  },
  {
    id: 'exp-buzzer-tone-lab',
    category: 'sound-light-output',
    name: 'Buzzer Tone & Alarm Lab',
    tagline: 'A real, audible sound your robot could actually make -- computed from real note-frequency math.',
    overview: 'Generate a genuinely audible tone at a precise, real frequency -- pick a named preset (a reversing beep, a success chime, an alarm) or dial in any frequency by hand, using the actual equal-temperament note-frequency formula.',
    whatYoullDo: [
      'Play each preset tone and hear the real pitch difference between a 220 Hz warning and an 880 Hz alarm.',
      'Drag the frequency slider yourself and hear pitch rise and fall continuously.',
      'Build a simple two-tone "alert pattern" by chaining two frequencies with a real timed gap.',
    ],
    realWorldTieIn: 'Real robots use exactly this kind of piezo buzzer output for reversing beeps, low-battery alarms, and task-complete chimes -- driven by a microcontroller\'s tone() function computing the same frequency math used here.',
    componentsUsed: ['Piezo buzzer', 'Microcontroller tone output'],
    outputType: 'sound',
    difficulty: 'beginner',
    playgroundType: 'buzzer-tone-lab',
  },
  {
    id: 'exp-morse-led-blinker',
    category: 'sound-light-output',
    name: 'Morse Code LED Blinker',
    tagline: 'Type a message. Watch a real LED blink it out in genuine, correctly-timed Morse code.',
    overview: 'Type any short message and watch a simulated LED blink it out in real International Morse Code, using the actual ITU timing standard -- a dot is one unit, a dash is three, with real, correctly-proportioned gaps between letters and words.',
    whatYoullDo: [
      'Type a word and watch the LED blink the genuine Morse pattern for it, letter by letter.',
      'Slow down or speed up the timing unit and hear/see how the whole message compresses or stretches proportionally.',
      'Try decoding a blink pattern back into letters yourself before revealing the answer.',
    ],
    realWorldTieIn: 'Real robots and satellites have historically used blinking-light status codes for exactly this reason -- no radio needed, just a real timed light a human (or camera) can read from a distance.',
    componentsUsed: ['Status LED', 'Microcontroller timer'],
    outputType: 'light',
    difficulty: 'beginner',
    playgroundType: 'morse-led-blinker',
  },
  {
    id: 'exp-rgb-pwm-mixer',
    category: 'sound-light-output',
    name: 'RGB LED Color Mixer (Real PWM)',
    tagline: 'Every color your robot\'s status LED can show comes from mixing three real 0-255 PWM signals.',
    overview: 'Mix a real RGB status-LED color by setting each channel\'s PWM duty cycle on the actual 0-255 scale real microcontrollers use (Arduino\'s analogWrite range) -- watch the swatch update live as you adjust red, green, and blue.',
    whatYoullDo: [
      'Set each channel to 255 (full on) or 0 (full off) and rediscover the 8 pure colors an RGB LED can make.',
      'Mix intermediate values and watch smooth color blending -- exactly how a real status LED shows "charging" (amber) vs "ready" (green) vs "error" (red).',
      'Try to recreate a specific real-world robot status color by eye, using only the three real sliders.',
    ],
    realWorldTieIn: 'This 0-255 duty-cycle range is not simplified for teaching -- it\'s the literal real range a microcontroller\'s 8-bit PWM output uses to drive an RGB LED\'s brightness per channel.',
    componentsUsed: ['RGB LED', 'PWM output (3 channels)'],
    outputType: 'light',
    difficulty: 'beginner',
    playgroundType: 'rgb-pwm-mixer',
  },
  {
    id: 'exp-balance-pid-tuning',
    category: 'control-systems',
    name: 'Self-Balancing Robot: PID Tuning',
    tagline: 'Tune a real controller gain, don\'t just tap buttons -- watch the robot balance (or fall) entirely on its own.',
    overview: 'Unlike reacting by hand, this hands the balancing job to an actual P-controller -- set the gain too low and the robot slowly topples, too high and it oscillates itself over, and there is a real, findable sweet spot in between.',
    whatYoullDo: [
      'Start with Kp at 0 and watch the robot fall immediately -- no correction being applied at all.',
      'Raise Kp gradually and find the point where it genuinely, autonomously holds itself upright against random disturbances.',
      'Push Kp too high and watch real, growing oscillation -- overcorrection is a real, common tuning failure, not just a slow response.',
    ],
    realWorldTieIn: 'This is the literal control law behind real self-balancing robots and Segway-style vehicles -- correction proportional to how far off-balance the robot currently is.',
    componentsUsed: ['IMU (tilt sensing)', 'Differential-drive wheels', 'P-controller'],
    outputType: 'motion',
    difficulty: 'intermediate',
    playgroundType: 'balance-pid-tuning',
  },
  {
    id: 'exp-maze-pathfinding',
    category: 'sensing-navigation',
    name: 'Maze Pathfinding Lab',
    tagline: 'Build your own maze, then find the real shortest path through it.',
    overview: 'Click to build any maze layout you like, then run a real breadth-first search to find the genuinely shortest path from start to goal -- the same class of algorithm real warehouse and delivery robots use to plan routes.',
    whatYoullDo: [
      'Design a maze layout by clicking to place walls.',
      'Run the real pathfinding search and watch the shortest path get highlighted.',
      'Try to design a maze that has no valid path at all, and watch the algorithm correctly report that.',
    ],
    realWorldTieIn: 'Breadth-first search guarantees the shortest path on an unweighted grid -- exactly the property that makes it (or its more advanced relatives) the right tool for real robot route planning.',
    componentsUsed: ['Grid map', 'Path-planning algorithm'],
    outputType: 'visual',
    difficulty: 'beginner',
    playgroundType: 'maze-pathfinding',
    playgroundConfig: { gridSize: [8, 8], startLabel: 'Start', goalLabel: 'Goal', obstacleLabel: 'Wall' },
  },
  {
    id: 'exp-obstacle-course',
    category: 'sensing-navigation',
    name: 'Autonomous Obstacle Course',
    tagline: 'Place real obstacles, then let the robot\'s own sensor decide when to stop.',
    overview: 'Place obstacles anywhere along a lane, then run the robot autonomously -- its simulated distance sensor decides in real time whether to keep going or stop, exactly like a real ultrasonic-equipped robot would.',
    whatYoullDo: [
      'Place obstacles anywhere ahead of the robot\'s starting position.',
      'Start the run and watch the robot\'s own sensor logic decide when to stop.',
      'Clear the path and resume -- exactly the real "detect, stop, wait, continue" loop a warehouse robot runs.',
    ],
    realWorldTieIn: 'This detect-and-stop behavior is the most basic real safety layer in almost every autonomous mobile robot, from warehouse robots to robot vacuums.',
    componentsUsed: ['Ultrasonic distance sensor', 'Drive motors'],
    outputType: 'motion',
    difficulty: 'beginner',
    playgroundType: 'obstacle-course',
    playgroundConfig: { vehicleLabel: 'Robot', laneLength: 12, obstacleEmoji: '\u{1F6A7}' },
  },
  {
    id: 'exp-swarm-playground',
    category: 'swarm-multi-robot',
    name: 'Swarm Robotics Playground',
    tagline: 'No leader, no central plan -- watch group behavior emerge from simple local rules.',
    overview: 'Watch real flocking behavior emerge from a swarm of simple robots, each one only reacting to its own nearby neighbors -- no robot knows the group\'s overall shape, yet coordinated movement emerges anyway.',
    whatYoullDo: [
      'Start with a small swarm and watch simple local rules produce group movement.',
      'Scale the swarm size up and watch the same simple rules keep working at a larger scale.',
      'Notice that no single agent is "in charge" -- the coordinated behavior is a genuine emergent property of the whole group.',
    ],
    realWorldTieIn: 'This cohesion-and-alignment approach is the same basic class of rule (inspired by Craig Reynolds\' 1986 "boids" model of flocking) used in real robot-swarm research and drone light shows.',
    componentsUsed: ['Multiple simple robot agents', 'Local proximity sensing'],
    outputType: 'visual',
    difficulty: 'intermediate',
    playgroundType: 'swarm-playground',
    playgroundConfig: { agentLabel: 'Bot', agentEmoji: '\u{1F916}', defaultCount: 10, maxCount: 30, behaviorLabel: 'Flocking' },
  },
];
