import { RoboticsApplication } from './roboticsTypes';

// Robotics Lab's curated catalog -- real robots doing real jobs in the
// world today, not just DIY project prompts (see techProjectIdeas.ts for
// that, a separate AI-assisted "build guide" flow). Every fact here is
// hand-researched from well-documented, publicly known robots, companies,
// and missions (Boston Dynamics, ISRO, DRDO, Amazon Robotics, Intuitive
// Surgical, DJI, iRobot, and more) -- never generated at request time, same
// discipline as every other content file in this package. Deliberately
// broad (24 entries across 8 real-world categories) per the standing
// instruction: "don't give only a few projects... let it be open plenty of
// available projects." Every entry maps to one of 7 reusable, genuinely
// playable simulation types (see RoboticsPlaygroundType in roboticsTypes.ts
// and the *Playground components in apps/web), parameterized per robot so
// the interaction is specific, not generic.
export const ROBOTICS_APPLICATIONS: RoboticsApplication[] = [
  // -- Industrial & Manufacturing -------------------------------------------
  {
    id: 'industrial-robotic-arm',
    name: 'Robotic Arm Assembly Line',
    category: 'industrial',
    gradeBand: 'middle',
    tagline: 'The six-axis arm that builds nearly everything you own, moving to a fraction of a millimetre.',
    overview: 'Multi-jointed robotic arms weld, paint, and assemble parts on factory floors around the world, repeating the same precise motion thousands of times a day.',
    howItWorks: [
      "Each joint, usually six for a full range of motion, is driven by its own motor, letting the arm's tip reach almost any position and angle within its work envelope.",
      'A teach pendant or offline programming software records a precise sequence of positions -- the arm then repeats that exact path every single cycle.',
      "Sensors, like force/torque sensors at the wrist or vision cameras, let modern arms adjust slightly in real time instead of blindly repeating a fixed path.",
      "The end effector -- the arm's 'hand' -- is swapped depending on the job: a welding torch, a paint sprayer, a suction gripper, or a mechanical claw.",
    ],
    realExamples: ['KUKA and Fanuc industrial arms used across global car manufacturing', 'ABB arms welding car bodies at Tata Motors and Maruti Suzuki plants in India', "Foxconn's assembly-line arms building electronics components"],
    curriculumTie: "Connects directly to CBSE Class 9-10's robotics/AI unit on actuators and degrees of freedom, and Class 11-12 Computer Science's introduction to automation.",
    deepFacts: [
      'The first industrial robotic arm, Unimate, started work on a General Motors assembly line in 1961, lifting and stacking hot metal die-castings too dangerous for a human to handle directly.',
      'A typical six-axis arm can repeat the same motion to within a fraction of a millimetre, thousands of times a day, for years -- a precision no human hand can sustain over that many repetitions.',
      "Modern 'cobots' (collaborative robots) are specifically designed to work safely right next to humans, using force sensors that make them stop instantly on contact -- unlike older industrial arms, which had to be caged off.",
      "India's automotive industry is one of the largest users of robotic arms in Asia, with plants in Pune, Chennai, and Gurugram running thousands of them.",
    ],
    realWorldImpact: 'Robotic arms let factories produce consistent, high-precision products at a scale and speed impossible by hand, while taking over the most repetitive and hazardous tasks that used to injure human workers.',
    careersAndFutures: "Robotics technicians, automation engineers, and industrial designers are in high and growing demand as more factories adopt robotic arms -- India's PLI manufacturing push is accelerating this.",
    playgroundType: 'pick-and-place',
    playgroundConfig: { itemLabel: 'Car Door Panel', itemColor: '#3b82f6', pickZoneLabel: 'Stamping Station', placeZoneLabel: 'Assembly Conveyor', scenario: 'Move the stamped panel from the press to the conveyor without dropping it.' },
  },
  {
    id: 'industrial-warehouse-robot',
    name: 'Warehouse Picking Robot',
    category: 'industrial',
    gradeBand: 'senior',
    tagline: 'The robot that carries an entire shelf to a human, instead of sending a human to walk the aisles.',
    overview: 'Fleets of small, flat robots slide under shelving units and carry entire product shelves to a human picker, who never has to walk the warehouse floor.',
    howItWorks: [
      'Each robot follows a grid of floor markers or uses onboard cameras/lidar to know exactly where it is in the warehouse.',
      'A central computer system assigns each robot a shelf to fetch based on incoming orders, then plans a collision-free path for every robot moving at once.',
      'The robot slides underneath the target shelving unit, lifts it slightly, and carries the whole shelf to a picking station, then carries it back once an item is picked.',
    ],
    realExamples: ['Amazon Robotics (formerly Kiva Systems) drive units used in hundreds of Amazon fulfillment centres worldwide', 'Flipkart and other Indian e-commerce warehouses using similar automated guided vehicle (AGV) systems', 'GreyOrange, an Indian robotics company building warehouse robots used internationally'],
    curriculumTie: "Ties to CBSE Class 11-12 Computer Science's graph algorithms and pathfinding, and the AI curriculum's multi-agent systems coverage.",
    deepFacts: [
      'These robots (descended from a company called Kiva Systems, acquired by Amazon in 2012) can move a shelving unit weighing hundreds of kilograms while the robot itself weighs only a few dozen kilograms.',
      'A single large warehouse can run thousands of these robots simultaneously, all coordinated by central software that plans routes to avoid collisions -- effectively solving a massive, constantly-changing traffic problem in real time.',
      'This approach dramatically cuts the walking time that used to dominate a human picker\'s day -- instead of walking to the product, the product comes to them.',
      'GreyOrange, founded in India in 2011, builds similar warehouse robots and now operates in North America, Europe, and Asia -- a genuine homegrown robotics success story.',
    ],
    realWorldImpact: 'This kind of automation is a major reason same-day and next-day delivery became possible at the scale online shopping now runs at.',
    careersAndFutures: 'Warehouse robotics blends mechanical engineering, computer vision, and logistics/operations research -- a fast-growing field as e-commerce continues to scale in India and worldwide.',
    playgroundType: 'path-planning',
    playgroundConfig: { gridSize: [8, 6], startLabel: 'Charging Dock', goalLabel: 'Picking Station', terrainLabel: 'Warehouse Floor', obstacleLabel: 'Shelving Unit' },
  },
  {
    id: 'industrial-sorting-robot',
    name: 'Quality-Control Sorting Robot',
    category: 'industrial',
    gradeBand: 'middle',
    tagline: 'A camera, a decision, and a puff of air -- sorting thousands of items a minute by sight alone.',
    overview: 'Vision-guided robots inspect products moving past on a conveyor belt and automatically sort out defective or miscategorized items, at speeds no human inspector could match.',
    howItWorks: [
      'A camera photographs each item as it passes a fixed point on the conveyor belt, often thousands of times per minute.',
      "Software analyses each image against known 'good' examples, checking size, color, shape, or surface defects.",
      'Items that fail the check are diverted, often by a precisely-timed puff of compressed air, into a reject bin -- passing items continue untouched.',
    ],
    realExamples: ['Fruit and vegetable grading lines in food processing plants worldwide', 'Recycling facilities using AI-vision sorters to separate plastic types', 'Pharmaceutical packaging lines checking pill counts and blister-pack integrity'],
    curriculumTie: "Connects to CBSE's AI curriculum unit on computer vision and image classification, and Class 9-10 Science's coverage of automation in industry.",
    deepFacts: [
      'Modern vision-sorting systems can inspect and sort well over 1,000 items per minute -- far faster than any human visual inspector, and without fatigue-related errors that creep in over a long shift.',
      'Recycling facilities increasingly sort different plastic types (which look nearly identical to the human eye) using infrared light, since different plastics absorb and reflect infrared differently.',
      "The 'puff of air' rejection method is deliberately non-contact -- it diverts a bad item without ever touching the product, keeping the line running at full speed.",
      "These systems are a direct real-world application of the same image-classification AI concept taught with tools like Google Teachable Machine in Tech Lab's AI projects.",
    ],
    realWorldImpact: 'Automated sorting keeps food, medicine, and recycling supply chains safer and more efficient, catching defects a human would find exhausting to check consistently all day.',
    careersAndFutures: 'Computer vision engineers, quality assurance automation specialists, and machine learning practitioners are needed to build and maintain these systems.',
    playgroundType: 'sensor-threshold',
    playgroundConfig: { sensorLabel: 'Item Quality Score', sensorUnit: '%', sensorMin: 0, sensorMax: 100, thresholdDefault: 70, actuatorLabel: 'Reject Air-Jet', actuatorOnText: 'REJECTED -- diverted to bin', actuatorOffText: 'PASSED -- continues on belt', higherTriggers: false },
  },

  // -- Agriculture -----------------------------------------------------------
  {
    id: 'agriculture-precision-irrigation',
    name: 'Precision Irrigation Robot',
    category: 'agriculture',
    gradeBand: 'junior',
    tagline: "A robot that waters only what's thirsty, using soil data instead of a fixed schedule.",
    overview: 'Automated irrigation systems read live soil-moisture and weather data across a field and water only the zones that actually need it, instead of watering on a blind fixed timer.',
    howItWorks: [
      'Soil-moisture sensors buried at multiple points across a field send readings to a central controller.',
      'The controller compares each reading against a crop-specific target moisture level, and factors in weather forecast data.',
      'Valves or robotic sprinkler arms open only over the zones that are actually below target, for only as long as needed.',
    ],
    realExamples: ["Israel's Netafim, a global leader in precision drip-irrigation technology", 'ICAR-backed precision farming pilots in Punjab and Maharashtra', "John Deere's connected-field irrigation systems"],
    curriculumTie: "Ties to CBSE Class 9-10 Science's water conservation and agriculture chapters, and the robotics curriculum's sensors-and-actuators unit.",
    deepFacts: [
      "Agriculture uses roughly 70% of the world's fresh water withdrawals -- precision irrigation is one of the highest-leverage places sensing and robotics can cut real waste.",
      'Drip irrigation combined with soil sensing can cut water use by 30-50% compared to flood irrigation, while often increasing crop yield.',
      'India, facing serious groundwater depletion in states like Punjab and Haryana, has made precision irrigation a national agricultural policy priority.',
    ],
    realWorldImpact: 'Precision irrigation directly addresses water scarcity, one of the most serious resource challenges facing Indian and global agriculture, while improving crop yields.',
    careersAndFutures: 'Agri-tech is a fast-growing sector in India specifically, blending agronomy, electronics, and software.',
    playgroundType: 'sensor-threshold',
    playgroundConfig: { sensorLabel: 'Soil Moisture', sensorUnit: '%', sensorMin: 0, sensorMax: 100, thresholdDefault: 35, actuatorLabel: 'Irrigation Valve', actuatorOnText: 'ON -- watering this zone', actuatorOffText: 'OFF -- soil moisture is sufficient', higherTriggers: false },
  },
  {
    id: 'agriculture-crop-drone',
    name: 'Autonomous Crop-Monitoring Drone',
    category: 'agriculture',
    gradeBand: 'senior',
    tagline: "A flying eye that spots a sick crop days before it's visible from the ground.",
    overview: 'Drones fly preprogrammed patterns over farmland, capturing images -- including infrared -- that reveal crop health problems long before they are visible to the naked eye.',
    howItWorks: [
      'The drone flies a preprogrammed grid pattern over a field using GPS, capturing overlapping photos.',
      'Special cameras capture near-infrared light in addition to visible light -- healthy plants reflect infrared very differently from stressed or diseased ones.',
      'Software stitches the images into a single field map and highlights problem zones for a farmer to inspect or treat.',
    ],
    realExamples: ['DJI Agras agricultural drones, widely used in China and increasingly India', 'Indian startups like IoTechWorld and Marut Drones building agri-drones for Indian farm conditions', "Government of India's Kisan Drone subsidy schemes"],
    curriculumTie: "Connects to the robotics/AI curriculum's drones and remote-sensing unit, and Class 11-12 Geography's remote sensing and GIS topics.",
    deepFacts: [
      'Healthy plant leaves reflect a lot of near-infrared light, while stressed or diseased leaves reflect much less -- a difference invisible to human eyes but very clear to a drone camera.',
      'A drone can survey in minutes a field that would take a person hours to walk and inspect row by row.',
      "India's government has actively promoted 'Kisan Drones' through subsidies, aiming to modernize agriculture for millions of small and marginal farmers.",
    ],
    realWorldImpact: 'Early detection of crop disease or water stress lets farmers treat a small problem before it spreads across an entire field, directly protecting yield and income.',
    careersAndFutures: 'Drone piloting, agronomy-tech, and remote-sensing analysis are emerging skilled roles across Indian agriculture.',
    playgroundType: 'balance-control',
    playgroundConfig: { subjectLabel: 'Survey Drone', disturbanceLabel: 'Wind Gust', targetLabel: 'Steady Flight Path' },
  },
  {
    id: 'agriculture-harvest-robot',
    name: 'Fruit-Harvesting Robot',
    category: 'agriculture',
    gradeBand: 'middle',
    tagline: "A robotic hand gentle enough to pick a ripe strawberry without bruising it.",
    overview: 'Vision-guided robotic arms identify ripe fruit by color and shape, then use a soft gripper to pick it without damaging the fruit or the plant -- a genuinely hard robotics problem.',
    howItWorks: [
      'A camera scans the plant and uses color/shape recognition to identify which fruits are ripe versus still growing.',
      "The system calculates the exact 3D position of each ripe fruit relative to the arm.",
      'A soft, pressure-sensitive gripper approaches and picks the fruit with just enough force to detach it without bruising it or damaging the plant.',
    ],
    realExamples: ["Fieldwork Robotics and Dogtooth Technologies' UK strawberry-picking robots", "Israeli company Tevel's fruit-picking drones for orchards", 'Research prototypes at Indian agricultural universities for tomato and cotton picking'],
    curriculumTie: "Connects to the robotics curriculum's end effectors and computer vision unit, and Class 9-10 Biology's plant growth topics.",
    deepFacts: [
      'Picking delicate fruit without bruising it is genuinely one of the hardest problems in agricultural robotics -- much harder than picking a rigid industrial part, since the right force varies fruit to fruit.',
      'Fruit-picking robots must also work outdoors in changing light, wind, and weather -- conditions far less predictable than a controlled factory floor.',
      'Labour shortages during harvest season are a real, serious problem in agriculture worldwide, which is a major reason harvesting robotics has attracted heavy investment.',
    ],
    realWorldImpact: 'Harvesting robots address a genuine labour crunch many farms face at peak season, and can work through the night or in extreme heat.',
    careersAndFutures: 'Agricultural robotics combines mechanical design, soft robotics, and computer vision -- a specialized, growing niche within robotics.',
    playgroundType: 'pick-and-place',
    playgroundConfig: { itemLabel: 'Ripe Strawberry', itemColor: '#ef4444', pickZoneLabel: 'Plant', placeZoneLabel: 'Collection Tray', scenario: 'Gently pick only the ripe (red) fruit without bruising it.' },
  },

  // -- Medical & Healthcare ----------------------------------------------------
  {
    id: 'medical-surgical-robot',
    name: 'Surgical Robot',
    category: 'medical',
    gradeBand: 'plusTwo',
    tagline: "A surgeon's hands, scaled down to millimetre precision, operating through a keyhole incision.",
    overview: "Surgeon-controlled robotic systems translate a doctor's hand movements into smaller, steadier, more precise movements of tiny instruments inside a patient's body.",
    howItWorks: [
      'The surgeon sits at a console and views a magnified 3D image of the surgical site, captured through a small incision.',
      "The surgeon's hand movements are translated in real time into precise, scaled-down movements of robotic instrument arms inside the patient.",
      "Built-in tremor filtering removes any natural small shake in the surgeon's hand, so the instrument moves more steadily than an unaided hand ever could.",
    ],
    realExamples: ["Intuitive Surgical's da Vinci Surgical System, used in hospitals across India including AIIMS and major private hospitals", 'SSI Mantra, an Indian-developed surgical robot system built by SS Innovations', 'Robotic systems used for prostate, cardiac, and gynecological surgery worldwide'],
    curriculumTie: "Connects to the robotics curriculum's teleoperation and precision-actuators unit, and Biology's coverage of minimally invasive procedures.",
    deepFacts: [
      "Surgical robots don't operate autonomously -- a human surgeon always directly controls every movement in real time; the robot's role is precision and stability, not decision-making.",
      'Because incisions can be much smaller than in traditional open surgery, patients often recover faster and with less pain and scarring.',
      "SS Innovations' Mantra system, developed in India, is a notable example of India building its own advanced surgical robotics rather than only importing foreign systems.",
    ],
    realWorldImpact: 'Robot-assisted surgery has made many complex procedures less invasive, reducing recovery time and complication risk for patients.',
    careersAndFutures: 'Biomedical engineering, surgical robotics research, and medical device design are specialized, high-impact fields combining medicine and engineering.',
    playgroundType: 'pick-and-place',
    playgroundConfig: { itemLabel: 'Surgical Instrument', itemColor: '#e5e7eb', pickZoneLabel: 'Instrument Tray', placeZoneLabel: 'Precise Target Point', scenario: 'Guide the instrument through the small incision to the exact target -- steady hands only.' },
  },
  {
    id: 'medical-exoskeleton',
    name: 'Robotic Exoskeleton',
    category: 'medical',
    gradeBand: 'senior',
    tagline: 'A wearable frame that adds strength or restores a lost ability to walk.',
    overview: 'Wearable robotic frames assist or restore movement -- helping stroke or spinal-injury patients walk again, or letting workers safely lift far more than their own body could manage.',
    howItWorks: [
      'Sensors detect the wearer\'s intended movement, either through subtle muscle electrical signals (EMG) or force sensors that pick up the very start of a motion.',
      'Motors at the joints, usually hips and knees, then add power to assist or complete that movement.',
      'A control system continuously balances how much assistance to give -- enough to help, not so much that it fights the wearer\'s own effort.',
    ],
    realExamples: ['Ekso Bionics and ReWalk exoskeletons used in rehabilitation hospitals worldwide', "India's Genrobotics building exoskeleton and robotic assistance devices, including the Bandicoot manhole-cleaning robot", 'Industrial exoskeletons used by workers at car plants and warehouses to reduce injury from repetitive lifting'],
    curriculumTie: "Connects to the robotics curriculum's actuators and sensors unit, and Biology's coverage of the human musculoskeletal system.",
    deepFacts: [
      'Medical exoskeletons have helped some patients with spinal cord injuries stand and walk again for the first time since their injury.',
      "Industrial exoskeletons don't need to be nearly as complex as medical ones -- many are simple, unpowered spring-and-frame systems that redirect load away from the back, no motors required.",
      "Genrobotics, an Indian robotics company, built the Bandicoot robot specifically to eliminate the dangerous practice of manual scavenging in India -- a robotics solution to a serious public health and dignity issue.",
    ],
    realWorldImpact: 'Exoskeletons restore mobility and independence for patients with paralysis or mobility impairment, and reduce workplace injury for physically demanding jobs.',
    careersAndFutures: "Biomechanical engineering and assistive robotics are growing fields with direct, visible impact on people's quality of life.",
    playgroundType: 'balance-control',
    playgroundConfig: { subjectLabel: 'Patient in Exoskeleton', disturbanceLabel: 'Muscle Fatigue', targetLabel: 'Stable Walking Gait' },
  },
  {
    id: 'medical-prosthetic-hand',
    name: 'Robotic Prosthetic Hand',
    category: 'medical',
    gradeBand: 'senior',
    tagline: 'A hand controlled by the same electrical signals your muscles already send.',
    overview: "Advanced prosthetic hands read electrical signals from a wearer's remaining muscles and translate them into specific finger and grip movements.",
    howItWorks: [
      'Electrodes on the skin detect tiny electrical signals (EMG) generated when the wearer flexes remaining muscles in their arm.',
      "Software trained on the wearer's own signal patterns interprets which grip or finger movement they're intending.",
      'Small motors in each finger then execute that specific movement -- a pinch grip, a full-hand grip, or individual finger control on advanced models.',
    ],
    realExamples: ['Ottobock and Össur myoelectric prosthetic hands used worldwide', "India's Society for Biomedical Technology and BionicYantra building affordable prosthetic hands for Indian patients", "Open Bionics' 'Hero Arm', a lower-cost 3D-printed myoelectric prosthetic"],
    curriculumTie: "Connects to the robotics curriculum's sensors unit (bioelectric signals) and Biology's coverage of muscles and the nervous system.",
    deepFacts: [
      'EMG signals are the same kind of electrical activity doctors measure to diagnose muscle and nerve conditions -- prosthetic hands repurpose that same signal as a genuine control interface.',
      "Learning to control a myoelectric hand takes practice -- the wearer's brain has to learn to reliably produce distinct, repeatable muscle signals for each different grip.",
      'Cost remains a major real-world barrier -- advanced myoelectric hands can cost many thousands of dollars, exactly why lower-cost, 3D-printed alternatives are an active area of accessible design.',
    ],
    realWorldImpact: 'Myoelectric prosthetics restore genuine functional independence -- eating, writing, holding objects -- to amputees.',
    careersAndFutures: 'Prosthetics and orthotics, biomedical signal processing, and assistive-device design are specialized fields combining engineering with direct human impact.',
    playgroundType: 'gesture-match',
    playgroundConfig: { commands: [{ label: 'Flex signal: strong', icon: '💪', actionLabel: 'Power Grip' }, { label: 'Flex signal: light', icon: '🤏', actionLabel: 'Pinch Grip' }, { label: 'Flex signal: quick double', icon: '✌️', actionLabel: 'Point Gesture' }] },
  },

  // -- Space & Exploration -----------------------------------------------------
  {
    id: 'space-mars-rover',
    name: 'Mars Rover',
    category: 'space',
    gradeBand: 'plusTwo',
    tagline: 'A robot geologist, 140+ million miles from the nearest repair shop.',
    overview: 'Autonomous rovers explore the Martian surface, navigating unfamiliar terrain and analysing rock and soil samples, sending data back across a distance so vast that real-time remote control is impossible.',
    howItWorks: [
      "Because a radio signal takes anywhere from about 4 to 24 minutes one-way to reach Mars, the rover can't be joystick-controlled in real time -- it navigates obstacles on its own using onboard cameras and software.",
      'Six wheels with an independent suspension system let it climb over rocks and uneven terrain far rougher than a wheeled vehicle would handle on Earth.',
      'Scientific instruments -- cameras, spectrometers, drills -- analyse rock and soil composition and beam the data back to Earth over the following hours.',
    ],
    realExamples: ['NASA\'s Perseverance and Curiosity rovers, currently active on Mars', "China's Zhurong rover, part of the Tianwen-1 mission", "ISRO's Chandrayaan-3 Pragyan rover, which explored the Moon's south pole region in 2023"],
    curriculumTie: "Directly connects to CBSE/ICSE Class 11-12 Physics (communication delay, mechanics) and the robotics curriculum's autonomous navigation unit.",
    deepFacts: [
      "Because of the communication delay, Mars rovers must detect and safely stop for an obstacle entirely on their own -- there's no way for a human on Earth to react in time if something goes wrong.",
      "India's Chandrayaan-3 mission successfully landed the Pragyan rover near the Moon's south pole in August 2023, making India the fourth country to achieve a soft lunar landing and the first near the lunar south pole.",
      'Perseverance carries a small helicopter, Ingenuity, which made history in 2021 as the first powered aircraft to fly on another planet.',
    ],
    realWorldImpact: 'Rovers let humanity explore other worlds without risking human life, and the navigation/autonomy technology developed for them has directly influenced self-driving car and warehouse-robot software on Earth.',
    careersAndFutures: "Aerospace engineering, autonomous systems, and planetary science are the career paths behind missions like this -- ISRO's growing space program is opening real opportunities for Indian students.",
    playgroundType: 'path-planning',
    playgroundConfig: { gridSize: [8, 6], startLabel: 'Landing Site', goalLabel: 'Sample Target', terrainLabel: 'Martian Regolith', obstacleLabel: 'Boulder' },
  },
  {
    id: 'space-underwater-rov',
    name: 'Underwater ROV',
    category: 'space',
    gradeBand: 'senior',
    tagline: 'Exploring a world darker and more crushing than space -- and far less explored.',
    overview: 'Tethered, remotely piloted submersibles explore ocean depths humans cannot survive unprotected, inspecting shipwrecks, pipelines, and deep-sea ecosystems.',
    howItWorks: [
      'A long cable (tether) connects the ROV to a ship on the surface, carrying both power and control signals -- an ROV IS controlled live by a human pilot.',
      'Thrusters let the pilot move the ROV forward/back, up/down, and rotate in any direction.',
      'Lights and cameras let the pilot see in the pitch-dark deep ocean, while robotic arms can collect samples or manipulate objects.',
    ],
    realExamples: ['Woods Hole Oceanographic Institution\'s ROVs, used to help locate and film the Titanic wreck', 'ROVs used for offshore oil-rig pipeline inspection worldwide', "India's National Institute of Ocean Technology developing deep-sea ROVs as part of the Samudrayaan deep-ocean mission"],
    curriculumTie: "Connects to CBSE Class 11 Physics's pressure and fluids chapter, and the robotics curriculum's teleoperation unit.",
    deepFacts: [
      'Water pressure increases roughly 1 atmosphere for every 10 metres of depth -- at the bottom of the Mariana Trench, the pressure is over 1,000 times sea level, exactly why ROVs need extremely strong pressure-resistant housings.',
      "India's Samudrayaan mission aims to send a crewed submersible to 6,000 metres depth, part of the Deep Ocean Mission -- sometimes called India's answer to its space program, but for the ocean.",
      'Deep-sea ROVs have discovered entirely new species living near hydrothermal vents, in conditions of total darkness and extreme pressure once assumed unable to support life.',
    ],
    realWorldImpact: 'ROVs let scientists and industries inspect environments no human diver could safely reach, from deep shipwrecks to offshore pipelines and unexplored deep-ocean ecosystems.',
    careersAndFutures: "Marine robotics and ocean engineering are a growing field in India, tied to the government's Deep Ocean Mission and blue-economy priorities.",
    playgroundType: 'obstacle-avoidance',
    playgroundConfig: { vehicleLabel: 'ROV Submersible', laneLength: 10, obstacleEmoji: '🪨' },
  },
  {
    id: 'space-station-arm',
    name: 'Robotic Space Station Arm',
    category: 'space',
    gradeBand: 'senior',
    tagline: 'A giant robotic arm that grapples spacecraft and builds structures in zero gravity.',
    overview: 'Large robotic arms mounted on space stations capture arriving cargo spacecraft, move astronauts during spacewalks, and help assemble the station itself piece by piece in orbit.',
    howItWorks: [
      "The arm has multiple joints, much like a human shoulder-elbow-wrist, letting it reach and orient its 'hand' (a grapple fixture) in almost any direction.",
      "Astronauts inside the station control it using a console with camera views, since there's no way to see the whole arm and target at once directly.",
      'A special grapple mechanism captures a fixture on an approaching spacecraft or a piece of station structure, then physically moves it into place.',
    ],
    realExamples: ["Canadarm2 on the International Space Station, built by Canada's MDA", 'Canadarm, the original Space Shuttle robotic arm used from 1981-2011', "ISRO's Gaganyaan program, India's crewed spaceflight mission in development, which will need similar robotic assist systems"],
    curriculumTie: "Connects to CBSE Class 11-12 Physics's mechanics and torque chapters, and the robotics curriculum's manipulator/actuator unit.",
    deepFacts: [
      'Canadarm2 helped assemble most of the International Space Station piece by piece, moving multi-tonne modules into position with a precision extremely difficult even on Earth, let alone in zero gravity.',
      "In zero gravity, a robotic arm doesn't need to fight gravity to hold something up -- but it still needs careful control, since even a gentle push can send a massive object drifting if not stopped precisely.",
      "The arm can 'walk' end-over-end along the station's exterior, grappling one fixture, releasing the other end, and reaching further -- effectively relocating itself around the station.",
    ],
    realWorldImpact: 'Without a robotic arm this capable, building and maintaining a structure as large as the International Space Station with only human spacewalks would be far slower and more dangerous.',
    careersAndFutures: "Aerospace robotics is highly specialized -- as ISRO's own human spaceflight program (Gaganyaan) develops, India will need engineers with exactly this expertise.",
    playgroundType: 'pick-and-place',
    playgroundConfig: { itemLabel: 'Cargo Spacecraft', itemColor: '#94a3b8', pickZoneLabel: 'Approach Point', placeZoneLabel: 'Docking Port', scenario: 'Grapple the arriving spacecraft and guide it precisely to the docking port.' },
  },

  // -- Home & Daily Life ---------------------------------------------------
  {
    id: 'home-robot-vacuum',
    name: 'Robot Vacuum Cleaner',
    category: 'home',
    gradeBand: 'junior',
    tagline: 'The robot that maps your living room better than you could draw it from memory.',
    overview: "Autonomous vacuum robots navigate and clean a home's floor space on their own, building an internal map of the rooms as they go and avoiding obstacles and stairs.",
    howItWorks: [
      'Bump sensors, infrared, or laser (LIDAR) sensors detect walls, furniture, and drop-offs like stairs in real time.',
      'Many modern models build a full map of the home during the first cleaning run, then use it to plan efficient, systematic cleaning paths on future runs.',
      'When the battery runs low, the robot navigates back to its charging dock on its own, resuming cleaning once recharged.',
    ],
    realExamples: ["iRobot's Roomba, the original mass-market robot vacuum, first launched in 2002", 'Xiaomi and Ecovacs robot vacuums, popular and widely sold in India', "Dyson's robot vacuum line combining strong suction with room-mapping navigation"],
    curriculumTie: "Connects to the robotics curriculum's sensors and mapping/navigation unit -- a genuinely relatable, in-home example of autonomous robotics.",
    deepFacts: [
      'Early robot vacuums moved in essentially random bouncing patterns with no memory of the room -- modern models build and remember an actual floor-plan map, a major leap in capability.',
      'Cliff sensors pointed downward detect a sudden drop, like the edge of a staircase, and stop the robot before it falls -- a simple but critical safety feature.',
      'Some advanced models now use small cameras and basic AI object recognition to identify and avoid obstacles like pet waste or loose cables, not just bump into and reroute around them.',
    ],
    realWorldImpact: 'Robot vacuums are one of the most widely adopted consumer robots in the world, genuinely saving people time on a repetitive household chore.',
    careersAndFutures: 'Consumer robotics blends embedded systems, sensor design, and increasingly AI/computer vision.',
    playgroundType: 'obstacle-avoidance',
    playgroundConfig: { vehicleLabel: 'Robot Vacuum', laneLength: 10, obstacleEmoji: '🪑' },
  },
  {
    id: 'home-voice-assistant',
    name: 'Smart Home Voice Assistant',
    category: 'home',
    gradeBand: 'junior',
    tagline: 'A device that listens for one phrase constantly, and does nothing else until it hears it.',
    overview: 'Voice-controlled smart speakers and hubs let people control lights, appliances, and information by speaking natural commands.',
    howItWorks: [
      "The device continuously listens only for a specific 'wake word', processed entirely on the device itself for privacy, without sending constant audio anywhere.",
      'Once the wake word is detected, the following speech is converted to text and sent to cloud servers, which figure out the intended command.',
      "The matched command is sent over the home WiFi network to the specific connected smart device, which executes it.",
    ],
    realExamples: ['Amazon Echo (Alexa) and Google Home/Nest smart speakers, sold globally including in India', "Indian-language voice assistant efforts building Hindi and regional-language voice interfaces", 'Smart home ecosystems used to control lights, fans, and locks in Indian homes'],
    curriculumTie: "Connects to the AI curriculum's natural language processing unit and the robotics curriculum's sensors/actuators coverage.",
    deepFacts: [
      "Wake-word detection specifically runs locally on the device using a small, efficient model -- only after it's triggered does audio get sent to more powerful cloud servers, a deliberate privacy design choice.",
      "Building voice assistants that work well across India's many languages and accents is a genuinely hard, actively researched problem.",
      "Natural language understanding has to handle enormous variation in how people phrase the same request, all mapping to the identical underlying action.",
    ],
    realWorldImpact: 'Voice assistants make technology more accessible to people who find typing or app navigation difficult, including elderly users, while becoming a genuine convenience for millions of households.',
    careersAndFutures: 'Natural language processing, speech recognition, and IoT device engineering are fast-growing fields, with real opportunity in building better Indian-language voice AI.',
    playgroundType: 'gesture-match',
    playgroundConfig: { commands: [{ label: '"Turn on the lights"', icon: '💡', actionLabel: 'Lights ON' }, { label: '"What\'s the weather?"', icon: '☀️', actionLabel: 'Weather Report' }, { label: '"Set a timer for 5 minutes"', icon: '⏱️', actionLabel: 'Timer Started' }] },
  },
  {
    id: 'home-robot-mower',
    name: 'Robotic Lawn Mower',
    category: 'home',
    gradeBand: 'middle',
    tagline: 'A mower that never needs supervision -- it knows exactly where your lawn ends.',
    overview: "Autonomous mowers cut grass on a schedule without human supervision, staying within a lawn's boundary and returning to charge on their own.",
    howItWorks: [
      "A thin wire is buried around the lawn's perimeter, or the boundary is set via GPS/app on newer models, creating an electronic boundary the mower never crosses.",
      'The mower moves in a semi-random or systematic pattern across the enclosed area, cutting small amounts of grass frequently rather than one long session.',
      "Rain sensors and tilt sensors let it pause or stop safely in bad weather or if it's picked up or tipped.",
    ],
    realExamples: ['Husqvarna Automower, one of the original robotic lawn mower brands', 'Worx Landroid and other GPS-boundary robotic mowers now replacing buried wire systems', 'Increasingly used on Indian estates and golf courses for large-area grass maintenance'],
    curriculumTie: "Connects to the robotics curriculum's boundary-detection and sensors unit, and pairs conceptually with the line-following robot idea in Tech Lab's DIY project prompts.",
    deepFacts: [
      'The buried-wire boundary system works similarly in principle to a line-following robot -- the mower detects the wire\'s signal and steers to stay near it, just used to define an area rather than a path.',
      'Frequent small cuts actually keep a lawn healthier, since grass clippings can be left to decompose and fertilise the soil naturally.',
      'Newer GPS/RTK positioning models are accurate to a few centimetres, letting them define a lawn boundary through an app without ever burying a wire.',
    ],
    realWorldImpact: 'Robotic mowers save significant time on a repetitive outdoor chore and, done well, can actually improve lawn health compared to traditional mowing.',
    careersAndFutures: 'Consumer robotics and precision-positioning (GPS/RTK) systems are the underlying skills behind this category of device.',
    playgroundType: 'obstacle-avoidance',
    playgroundConfig: { vehicleLabel: 'Robot Mower', laneLength: 10, obstacleEmoji: '🌳' },
  },

  // -- Disaster Response & Safety --------------------------------------------
  {
    id: 'disaster-firefighting-robot',
    name: 'Firefighting Robot',
    category: 'disaster-safety',
    gradeBand: 'senior',
    tagline: "A robot that walks into the fire so a firefighter doesn't have to.",
    overview: 'Heat-resistant robots equipped with cameras, heat sensors, and water cannons enter burning buildings or industrial fires too dangerous for firefighters to approach directly.',
    howItWorks: [
      "Thermal cameras let the robot and remote operators see through smoke and identify the hottest, most dangerous zones.",
      'Heat and gas sensors detect dangerous conditions and can trigger an automatic water-cannon response, or warn operators of specific risks.',
      "A remote human operator drives the robot and aims its water cannon from a safe distance, using the robot's camera feed.",
    ],
    realExamples: ['Thermite robots, used by fire departments including in major US cities for tunnel and industrial fires', 'South Korean and Japanese firefighting robots deployed for large industrial and chemical-plant fires', 'Robots used at the Notre-Dame Cathedral fire in Paris (2019)'],
    curriculumTie: "Connects to the robotics curriculum's sensors unit (thermal/heat sensing) and Class 9-10 Science's chapters on combustion and fire safety.",
    deepFacts: [
      'A Thermite-style firefighting robot was used at the 2019 Notre-Dame Cathedral fire specifically to get close enough to extinguish flames in areas too structurally unstable for human firefighters.',
      'These robots often need to drag their own fire hose and be resistant enough to extreme heat to operate inside conditions that would injure an unprotected human within seconds.',
      'Some firefighting robots are tracked, like a small tank, rather than wheeled, specifically so they can climb over rubble and debris a fire scene is often full of.',
    ],
    realWorldImpact: 'Firefighting robots let responders tackle the most dangerous parts of a fire without risking a human life directly in the most hazardous zone.',
    careersAndFutures: 'Emergency-response robotics is a specialized niche combining mechanical engineering with materials science.',
    playgroundType: 'sensor-threshold',
    playgroundConfig: { sensorLabel: 'Heat Sensor', sensorUnit: '°C', sensorMin: 20, sensorMax: 300, thresholdDefault: 150, actuatorLabel: 'Water Cannon', actuatorOnText: 'FIRING -- fire detected', actuatorOffText: 'Standby -- monitoring', higherTriggers: true },
  },
  {
    id: 'disaster-search-rescue-robot',
    name: 'Search-and-Rescue Robot',
    category: 'disaster-safety',
    gradeBand: 'senior',
    tagline: "Small enough to crawl through rubble a rescue dog can't reach.",
    overview: 'Compact, rugged robots navigate collapsed buildings or disaster rubble, searching for survivors in spaces too small or unstable for a human or dog to enter safely.',
    howItWorks: [
      'A small, often tracked or snake-like body lets the robot squeeze through gaps in rubble far too small or unstable for a person to enter.',
      'Cameras and microphones let a remote human operator see and hear for signs of survivors -- movement, sound, or calls for help.',
      "Some models carry thermal cameras to detect a survivor's body heat even in total darkness or thick dust.",
    ],
    realExamples: ['Robots deployed after the 2023 Turkey-Syria earthquake to search collapsed buildings', 'CRASAR robots used at the World Trade Center site in 2001', "India's NDRF exploring robotic search tools for building-collapse response"],
    curriculumTie: "Connects to the robotics curriculum's mobility/locomotion unit and Class 9-10 Science's disaster management chapter.",
    deepFacts: [
      'Search-and-rescue robots were first used in a real disaster response at the World Trade Center site in 2001, helping search rubble too unstable for rescue teams.',
      "Because disaster rubble is unpredictable and constantly shifting, these robots are often designed to be highly rugged and expendable, in the sense that losing one is an acceptable risk a human rescuer's life is not.",
      'Snake-like robots, with many small connected segments, can navigate through gaps and around corners no wheeled or even tracked robot could manage.',
    ],
    realWorldImpact: 'These robots can search dangerous, unstable rubble faster and more safely than sending in human rescue teams first.',
    careersAndFutures: "Disaster-response robotics is a specialized humanitarian engineering field, with growing relevance as India strengthens its NDRF robotics capability.",
    playgroundType: 'obstacle-avoidance',
    playgroundConfig: { vehicleLabel: 'Rescue Robot', laneLength: 10, obstacleEmoji: '🧱' },
  },
  {
    id: 'disaster-bomb-disposal-robot',
    name: 'Bomb-Disposal Robot',
    category: 'disaster-safety',
    gradeBand: 'senior',
    tagline: 'A remote-controlled robotic hand, so the person defusing a bomb is a hundred metres away.',
    overview: 'Remotely operated robots let bomb-disposal experts inspect, move, or disable suspicious devices from a safe distance.',
    howItWorks: [
      'A tracked robot base, similar to a small tank, lets it move over rough or uneven ground reliably.',
      'A multi-jointed robotic arm can lift, move, X-ray, or place a disruptor charge on a suspicious object, all controlled remotely.',
      'A live video feed lets the human operator, positioned safely far away, see exactly what the robot sees and control every movement precisely.',
    ],
    realExamples: ['The iRobot PackBot, widely used by military and police bomb squads globally', "India's DRDO building the indigenous Daksh bomb-disposal robot, used by the Indian Army", 'Remotec robots used by UK and US police bomb squads'],
    curriculumTie: "Connects to the robotics curriculum's teleoperation unit and Class 11-12 Physics's mechanics of levers and manipulators.",
    deepFacts: [
      "DRDO's Daksh robot, developed in India, can climb stairs, has a manipulator arm, and includes an X-ray system to look inside a suspicious package without a human ever approaching it.",
      'Bomb-disposal robots are deliberately over-engineered to be extremely rugged, since even the failure of the robot itself is a vastly preferable outcome to any risk to human life.',
      "Some models can be fitted with a 'disruptor' -- a controlled device that uses a precisely aimed water or projectile charge to safely disable a bomb's detonator.",
    ],
    realWorldImpact: 'Bomb-disposal robots directly remove human experts from the single most dangerous moment of their job.',
    careersAndFutures: 'Defence robotics engineering, a field DRDO actively recruits for in India, combines mechanical design, remote systems, and rigorous safety engineering.',
    playgroundType: 'pick-and-place',
    playgroundConfig: { itemLabel: 'Suspicious Package', itemColor: '#78716c', pickZoneLabel: 'Danger Zone', placeZoneLabel: 'Containment Vessel', scenario: 'Carefully lift and move the package into the containment vessel -- steady, precise control only.' },
  },

  // -- Transportation ---------------------------------------------------------
  {
    id: 'transportation-self-driving-car',
    name: 'Self-Driving Car',
    category: 'transportation',
    gradeBand: 'plusTwo',
    tagline: 'A car that "sees" its surroundings in a full 360°, all the time, without ever blinking.',
    overview: 'Autonomous vehicles combine multiple types of sensors with real-time decision-making software to drive without constant human control.',
    howItWorks: [
      'Multiple sensor types -- cameras, radar, and often lidar -- work together, each compensating for the others\' weaknesses.',
      "Software fuses all these sensor readings into a single, constantly updated 3D model of everything around the car.",
      "A decision-making system plans and continuously re-plans the car's path, speed, and steering, reacting many times per second.",
    ],
    realExamples: ['Waymo, operating driverless taxi services in several US cities', "Tesla's Autopilot and Full Self-Driving systems, camera-based rather than lidar-based", 'Indian research labs working on ADAS (advanced driver-assistance systems) as a stepping stone toward full autonomy'],
    curriculumTie: "Connects strongly to Class 11-12 Computer Science's algorithms (path planning, decision trees) and the AI curriculum's sensor-fusion topics.",
    deepFacts: [
      "Self-driving cars are classified by 'levels' of autonomy from 0 to 5 -- most commercially available cars today are only Level 2 or partial Level 3, still requiring an attentive human driver.",
      "Sensor fusion exists specifically because no single sensor type is reliable in every condition; heavy fog can blind cameras, while radar can't read a stop sign.",
      "India's dense, less-lane-disciplined traffic patterns are considered one of the hardest real-world environments for self-driving technology.",
    ],
    realWorldImpact: 'Autonomous vehicles have the potential to reduce accidents caused by human error, though widespread safe deployment in complex traffic remains a genuinely unsolved challenge.',
    careersAndFutures: 'Autonomous vehicle engineering is one of the most well-funded and competitive areas of robotics/AI globally.',
    playgroundType: 'obstacle-avoidance',
    playgroundConfig: { vehicleLabel: 'Self-Driving Car', laneLength: 10, obstacleEmoji: '🚧' },
  },
  {
    id: 'transportation-delivery-robot',
    name: 'Delivery Robot',
    category: 'transportation',
    gradeBand: 'senior',
    tagline: 'A small, wheeled robot that navigates a real sidewalk to bring your order to your door.',
    overview: 'Small autonomous or semi-autonomous robots navigate sidewalks or indoor corridors to deliver food, packages, or documents directly to a recipient.',
    howItWorks: [
      'Cameras and sensors help the robot detect the sidewalk edge, pedestrians, curbs, and obstacles as it navigates a pre-mapped route.',
      'GPS and pre-built maps let it know its overall route, while onboard sensors handle moment-to-moment obstacle avoidance.',
      "On arrival, the recipient is notified via app and unlocks the robot's storage compartment to retrieve their delivery.",
    ],
    realExamples: ['Starship Technologies delivery robots, used on university campuses and in cities across the US and Europe', 'Amazon Scout, a sidewalk delivery robot pilot program', 'Zomato and Swiggy piloting robot and drone delivery in limited campus/controlled settings in India'],
    curriculumTie: "Connects to the robotics curriculum's autonomous navigation unit, directly related to the delivery-robot idea already in Tech Lab's Class 11-12 project prompts.",
    deepFacts: [
      'Sidewalk delivery robots typically travel at a deliberately slow, pedestrian-safe walking pace, prioritizing safety around people over speed.',
      "Many delivery robot companies still use remote human 'supervisors' who can take over control if the robot encounters a genuinely confusing situation.",
      'Navigating a real, messy sidewalk has proven to be a much harder robotics problem than early designers expected.',
    ],
    realWorldImpact: 'Delivery robots offer a potentially lower-cost, contactless delivery option, particularly explored for last-mile delivery in dense campuses and urban areas.',
    careersAndFutures: 'Autonomous mobile robot (AMR) engineering is a specific, growing robotics specialty with direct application to logistics.',
    playgroundType: 'path-planning',
    playgroundConfig: { gridSize: [8, 6], startLabel: 'Restaurant', goalLabel: "Customer's Door", terrainLabel: 'Sidewalk', obstacleLabel: 'Parked Bike' },
  },
  {
    id: 'transportation-auto-parking',
    name: 'Automatic Parking Assist System',
    category: 'transportation',
    gradeBand: 'middle',
    tagline: 'The car that measures a gap, does the math, and steers itself in -- while you just watch.',
    overview: 'Automatic parking systems use distance sensors to measure an available parking gap and take over steering to park the car precisely.',
    howItWorks: [
      "Ultrasonic distance sensors around the car's bumpers continuously measure the gap between two parked cars as the vehicle drives slowly past.",
      'If the gap is calculated to be large enough, the system plots a precise steering path to fit the car into the space.',
      "The car's power steering executes that exact path automatically while the driver controls only the brake/accelerator.",
    ],
    realExamples: ['Self-parking systems in many modern cars from Toyota, Hyundai, and Tata, increasingly available in mid-range Indian car models', "Tesla's 'Summon' feature, letting a car autonomously navigate a parking lot", 'Ultrasonic reverse-parking sensors, now standard on most new cars sold in India'],
    curriculumTie: "Connects directly to CBSE's robotics/AI sensors unit and pairs conceptually with the smart parking-sensor project already in Tech Lab's Class 7-8 prompts.",
    deepFacts: [
      'Ultrasonic parking sensors work by sending out a high-frequency sound pulse and timing how long it takes to bounce back -- the same basic principle bats use for echolocation.',
      "Calculating whether a gap is 'big enough' isn't just about length -- the system also has to calculate a physically achievable steering path, since a car's turning radius matters.",
      'Reverse-parking sensors (which only warn the driver) and full auto-parking (which actually steers the car) use the same underlying sensor technology, at very different levels of control.',
    ],
    realWorldImpact: 'Automatic and assisted parking reduces minor collision damage from parking mistakes and makes tight urban parking spaces genuinely usable for less experienced drivers.',
    careersAndFutures: 'Automotive sensor systems and embedded control engineering are core skills behind this and most other modern car safety features.',
    playgroundType: 'sensor-threshold',
    playgroundConfig: { sensorLabel: 'Distance to Obstacle', sensorUnit: 'cm', sensorMin: 0, sensorMax: 100, thresholdDefault: 20, actuatorLabel: 'Parking Alert', actuatorOnText: 'STOP -- too close!', actuatorOffText: 'Clear -- reversing safely', higherTriggers: false },
  },

  // -- Swarm & Social Robots ----------------------------------------------------
  {
    id: 'swarm-social-swarm-robotics',
    name: 'Swarm Robotics',
    category: 'swarm-social',
    gradeBand: 'plusTwo',
    tagline: 'Hundreds of simple robots, no leader, following three simple rules -- and somehow acting as one.',
    overview: 'Swarm robotics uses many simple robots following basic local rules to achieve complex group behaviour -- inspired directly by how ants, bees, and birds coordinate in nature.',
    howItWorks: [
      'Each individual robot in a swarm is deliberately simple and follows only a few basic rules based on what its nearby neighbours are doing, not a global plan.',
      'Common rules include: separation (avoid crowding neighbours), alignment (move roughly the same direction as nearby robots), and cohesion (stay near the group\'s centre).',
      'Complex group behaviours -- like a drone light show forming shapes -- emerge from these simple local rules, without any single robot knowing the overall plan.',
    ],
    realExamples: ['Intel\'s drone light shows, using swarms of hundreds to over a thousand drones to form moving patterns in the sky', 'Kilobot swarm robots, developed at Harvard, studying swarm behaviour with over 1,000 simple robots at once', "Amazon's warehouse robot fleets, coordinating as a large swarm-like system"],
    curriculumTie: "Connects to the AI curriculum's multi-agent systems topic and Biology's coverage of social insects and collective animal behaviour.",
    deepFacts: [
      'This approach is directly inspired by nature -- no single ant plans a colony\'s foraging trails, and no single bird leads a flock\'s swooping turns; the group behaviour emerges from each individual reacting to its neighbours.',
      'Swarm systems are genuinely more resilient than one complex robot -- if a few robots in a swarm fail, the group can often still complete its task.',
      "Intel's record-breaking drone light shows have used well over 1,000 drones simultaneously, each just following simple positioning rules relative to its assigned spot.",
    ],
    realWorldImpact: 'Swarm robotics principles are increasingly used in warehouse logistics, agricultural drone fleets, and search-and-rescue coordination.',
    careersAndFutures: 'Multi-agent systems and swarm intelligence are active, fascinating research areas at the intersection of robotics, biology, and AI.',
    playgroundType: 'swarm-simulation',
    playgroundConfig: { agentLabel: 'Swarm Drone', agentEmoji: '🔷', defaultCount: 20, maxCount: 60, behaviorLabel: 'Flocking Cohesion' },
  },
  {
    id: 'swarm-social-humanoid-robot',
    name: 'Humanoid Robot',
    category: 'swarm-social',
    gradeBand: 'plusTwo',
    tagline: 'Built to move through a world designed for two legs and two hands -- ours.',
    overview: 'Human-shaped robots, walking on two legs and manipulating objects with hand-like grippers, are designed to operate in spaces and use tools built for humans.',
    howItWorks: [
      "Dozens of individual motors control each joint -- hips, knees, ankles, shoulders, elbows, wrists -- far more than a simple wheeled robot needs.",
      'Balance is maintained continuously by sensors constantly measuring the robot\'s tilt and adjusting joint positions many times per second to avoid falling.',
      'Computer vision and manipulation software let advanced humanoids recognize objects and plan how to grip and use them.',
    ],
    realExamples: ['Boston Dynamics\' Atlas, famous for running, jumping, and even doing backflips', "Tesla's Optimus humanoid robot, aimed at eventually working in factories and homes", "Honda's ASIMO, one of the earliest widely known walking humanoid robots"],
    curriculumTie: "Connects to the robotics curriculum's actuators/balance unit and Class 11-12 Physics's centre of mass and stability concepts.",
    deepFacts: [
      'Keeping a two-legged robot balanced is genuinely one of the hardest problems in all of robotics -- a human does it almost unconsciously, using millions of years of evolved reflexes.',
      'The main argument for humanoid robots is that human environments -- stairs, door handles, tools -- are already built for a human shape, so a humanoid robot can use them without redesign.',
      "Boston Dynamics' Atlas robot, first unveiled in 2013, has progressed from unstable early walking to running, jumping over gaps, and performing gymnastic-style backflips.",
    ],
    realWorldImpact: 'Humanoid robots are being developed as potential general-purpose labour in factories, warehouses, and eventually homes.',
    careersAndFutures: 'Humanoid robotics combines nearly every robotics discipline at once, making it one of the most technically demanding areas in the whole field.',
    playgroundType: 'balance-control',
    playgroundConfig: { subjectLabel: 'Humanoid Robot', disturbanceLabel: 'Push / Uneven Ground', targetLabel: 'Upright Balance' },
  },
  {
    id: 'swarm-social-robot-pet',
    name: 'Robotic Pet Companion',
    category: 'swarm-social',
    gradeBand: 'junior',
    tagline: 'A robot designed not to do a job, but to keep you company.',
    overview: 'Social robots designed to look and behave like pets respond to touch, voice, and their environment with lifelike movement, used for companionship and comfort.',
    howItWorks: [
      "Touch sensors across the robot's body detect petting, poking, or holding, and trigger different responsive behaviours.",
      "Microphones let it respond to voice and sound -- some models recognize their own name or simple commands.",
      "Small motors move the robot's head, limbs, or tail to create lifelike, expressive movement, often paired with simple sounds.",
    ],
    realExamples: ['Paro, a robotic therapeutic seal used in hospitals and elderly care facilities in Japan and worldwide', "Sony's Aibo robotic dog, one of the longest-running consumer robotic pet product lines", 'Robotic companion pets increasingly piloted in Indian elderly-care and dementia-care settings'],
    curriculumTie: "Connects to the AI curriculum's human-robot interaction topic and Biology's discussion of companionship and wellbeing.",
    deepFacts: [
      'Paro, shaped like a baby harp seal specifically because most people have no strong preconceptions about how a real seal should behave, has been shown in studies to measurably reduce stress and loneliness in elderly care settings.',
      'Robotic pets are deliberately designed to require far less responsibility than a real animal -- no feeding or vet visits -- while still offering some comfort of companionship.',
      "Sony's Aibo robotic dog uses onboard AI to develop what the company describes as a unique personality over time, based on how its owner interacts with it.",
    ],
    realWorldImpact: 'Robotic companions have shown real, measurable benefits for isolated elderly people and some patients with dementia.',
    careersAndFutures: 'Social robotics and human-robot interaction design is a genuinely interdisciplinary field, drawing on psychology and design as much as engineering.',
    playgroundType: 'gesture-match',
    playgroundConfig: { commands: [{ label: 'Gentle pet on the head', icon: '✋', actionLabel: 'Happy chirp + tail wag' }, { label: 'Loud noise nearby', icon: '📢', actionLabel: 'Startled, ears back' }, { label: 'Owner calls its name', icon: '🗣️', actionLabel: 'Turns and approaches' }] },
  },
];
