'use client';
import { useState } from 'react';
import CountAndMatch from './games/CountAndMatch';
import ShapeSafari from './games/ShapeSafari';
import TimesTableBlitz from './games/TimesTableBlitz';
import FractionFill from './games/FractionFill';
import PatternDetective from './games/PatternDetective';

// A small arcade of quick drill games for the early/junior grade bands
// (Classes 1-6) -- pure fun-and-practice, distinct from the guided
// Predict/Explore/Explain Experiments flow. Every question is procedurally
// generated by verified arithmetic (see mathGamesEngine.ts's header for why
// that's safe here, unlike curated fact content elsewhere in the app), so
// there's effectively unlimited replay value.
const GAMES = [
  { id: 'count', label: 'Count & Match', gradeHint: 'Class 1-2', render: () => <CountAndMatch /> },
  { id: 'shapes', label: 'Shape Safari', gradeHint: 'Class 1-2', render: () => <ShapeSafari /> },
  { id: 'times-table', label: 'Times Table Blitz', gradeHint: 'Class 3-4', render: () => <TimesTableBlitz /> },
  { id: 'fractions', label: 'Fraction Fill', gradeHint: 'Class 4-5', render: () => <FractionFill /> },
  { id: 'patterns', label: 'Pattern Detective', gradeHint: 'Class 3-4', render: () => <PatternDetective /> },
] as const;

export default function MathGamesArcade() {
  const [activeId, setActiveId] = useState<(typeof GAMES)[number]['id']>(GAMES[0].id);
  const active = GAMES.find((g) => g.id === activeId) || GAMES[0];

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-2">
        {GAMES.map((g) => (
          <button
            key={g.id}
            onClick={() => setActiveId(g.id)}
            className={`px-3.5 py-2.5 rounded-xl text-sm font-bold border-2 transition-all flex flex-col items-start ${
              activeId === g.id ? 'border-slate-900 bg-primary-600 text-white shadow-[3px_3px_0_var(--color-ink)]' : 'border-slate-900 dark:border-slate-700 bg-surface-light dark:bg-surface-dark hover:shadow-[3px_3px_0_var(--color-ink)]'
            }`}
          >
            {g.label}
            <span className={`text-[10px] font-medium ${activeId === g.id ? 'text-white/70' : 'text-slate-400'}`}>{g.gradeHint}</span>
          </button>
        ))}
      </div>
      {active.render()}
    </div>
  );
}
