// Runtime brand-color theming (CMS Phase 1). The app's whole color system
// is already CSS custom properties (--color-primary-50 through -900, see
// globals.css), which Tailwind v4 compiles utility classes like
// bg-primary-600 FROM -- meaning overriding those variables on :root at
// runtime genuinely re-themes every one of those utility classes across the
// entire site, no rebuild needed. An admin only picks one base hex color
// (the "600" shade, matching the convention every button/active-state
// already uses); the rest of the 50-900 ramp is generated by mixing that
// color toward white (lighter shades) or black (darker shades).
function hexToRgb(hex: string): [number, number, number] | null {
  const m = hex.trim().replace(/^#/, '').match(/^([0-9a-fA-F]{6})$/);
  if (!m) return null;
  const n = parseInt(m[1], 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function rgbToHex([r, g, b]: [number, number, number]): string {
  const clamp = (v: number) => Math.round(Math.max(0, Math.min(255, v)));
  return '#' + [r, g, b].map((v) => clamp(v).toString(16).padStart(2, '0')).join('');
}

function mix(base: [number, number, number], toward: [number, number, number], t: number): [number, number, number] {
  return [base[0] + (toward[0] - base[0]) * t, base[1] + (toward[1] - base[1]) * t, base[2] + (toward[2] - base[2]) * t];
}

const WHITE: [number, number, number] = [255, 255, 255];
const BLACK: [number, number, number] = [0, 0, 0];

// shade -> how far to mix toward white (lighter) or black (darker) from the
// admin's base color, which itself becomes shade 600 (the convention every
// existing bg-primary-600/text-primary-600 usage already assumes is "the"
// brand color).
const SHADE_RAMP: { shade: number; toward: 'white' | 'black'; t: number }[] = [
  { shade: 50, toward: 'white', t: 0.94 },
  { shade: 100, toward: 'white', t: 0.86 },
  { shade: 200, toward: 'white', t: 0.68 },
  { shade: 300, toward: 'white', t: 0.5 },
  { shade: 400, toward: 'white', t: 0.26 },
  { shade: 500, toward: 'white', t: 0.1 },
  { shade: 600, toward: 'white', t: 0 }, // the base color itself
  { shade: 700, toward: 'black', t: 0.18 },
  { shade: 800, toward: 'black', t: 0.34 },
  { shade: 900, toward: 'black', t: 0.5 },
];

export function applyBrandColor(hex: string): void {
  if (typeof document === 'undefined') return;
  const rgb = hexToRgb(hex);
  if (!rgb) return; // invalid/empty input -- leave the built-in default colors alone
  const root = document.documentElement;
  for (const { shade, toward, t } of SHADE_RAMP) {
    const mixed = t === 0 ? rgb : mix(rgb, toward === 'white' ? WHITE : BLACK, t);
    root.style.setProperty(`--color-primary-${shade}`, rgbToHex(mixed));
  }
}

export function resetBrandColor(): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  for (const { shade } of SHADE_RAMP) root.style.removeProperty(`--color-primary-${shade}`);
}
