import { api } from './api';

// Question-type keys shared with packages/ai's prompt-instruction system.
// Keep these in sync with apps/api/src/services/worksheetService.ts's AI_TYPE_TO_DB_TYPE map.
export interface QuestionTypeOption {
  key: string;
  label: string;
}

export const QUESTION_TYPE_OPTIONS: QuestionTypeOption[] = [
  { key: 'mcq', label: 'Multiple Choice' },
  { key: 'fill_in_the_blank', label: 'Fill in the Blanks' },
  { key: 'true_false', label: 'True / False' },
  { key: 'match', label: 'Match the Following' },
  { key: 'short_answer', label: 'Short Answer' },
  { key: 'long_answer', label: 'Long Answer' },
  { key: 'word_problem', label: 'Word Problems' },
  { key: 'diagram', label: 'Diagram Based' },
  { key: 'logical_reasoning', label: 'Logical Reasoning' },
];

const DB_TYPE_TO_SECTION_TITLE: Record<string, string> = {
  mcq: 'Multiple Choice Questions',
  fill_in_blank: 'Fill in the Blanks',
  true_false: 'True or False',
  match_following: 'Match the Following',
  short_answer: 'Short Answer Questions',
  long_answer: 'Long Answer Questions',
  word_problem: 'Word Problems',
  diagram_based: 'Diagram Based Questions',
  logical_reasoning: 'Logical Reasoning',
};

export interface WorksheetQuestionRow {
  id?: string;
  question_text: string;
  question_type: string;
  options: string[] | null;
  correct_answer: string;
  explanation: string | null;
  order_index: number;
}

export interface SavedQuestion {
  number?: number;
  question: string;
  type: string;
  options?: string[];
  answer: string;
  explanation?: string;
}

export interface SavedSection {
  sectionTitle: string;
  questions: SavedQuestion[];
}

// Groups raw worksheet_questions rows (as returned by GET /api/worksheets/:id) into
// print-friendly sections by question type, in the order questions appear.
export function groupQuestionsBySection(questions: WorksheetQuestionRow[]): SavedSection[] {
  const sections: SavedSection[] = [];
  const sectionByType = new Map<string, SavedSection>();

  for (const q of [...questions].sort((a, b) => a.order_index - b.order_index)) {
    let section = sectionByType.get(q.question_type);
    if (!section) {
      section = {
        sectionTitle: DB_TYPE_TO_SECTION_TITLE[q.question_type] || 'Questions',
        questions: [],
      };
      sectionByType.set(q.question_type, section);
      sections.push(section);
    }
    section.questions.push({
      number: q.order_index,
      question: q.question_text,
      type: q.question_type,
      options: q.options || undefined,
      answer: q.correct_answer,
      explanation: q.explanation || undefined,
    });
  }

  return sections;
}

export interface WorksheetDetail {
  id: string;
  title: string;
  difficulty: string;
  question_count: number;
  total_marks: number;
  time_limit_minutes: number | null;
  created_at: string;
  classes?: { name: string } | null;
  subjects?: { name: string } | null;
  chapters?: { title: string } | null;
  settings?: { board?: string; topics?: string[] } | null;
  worksheet_questions: WorksheetQuestionRow[];
}

// Fetches the full worksheet (with questions) from the API and groups it into
// print-friendly sections. Used when opening a "View & Print" modal from a
// worksheet history list, which only has summary fields until opened.
export async function fetchWorksheetDetail(id: string): Promise<{
  board: string;
  class: string;
  subject: string;
  chapter: string;
  topics: string[];
  sections: SavedSection[];
}> {
  const res = await api.get<{ success: boolean; data: WorksheetDetail }>(`/api/worksheets/${id}`);
  const row = res.data;
  return {
    board: row.settings?.board || 'CBSE',
    class: row.classes?.name || '',
    subject: row.subjects?.name || '',
    chapter: row.chapters?.title || '',
    topics: row.settings?.topics || [],
    sections: groupQuestionsBySection(row.worksheet_questions || []),
  };
}

// Fetches a signed URL for the real, server-rendered PDF (generated by
// apps/api's pdfService at worksheet-generation time) and opens it in a new
// tab. This is the clean, branded PDF -- distinct from the browser's
// print-to-PDF of the on-screen preview, which is fragile with app-shell CSS.
async function openSignedPdf(endpoint: string) {
  // Open the tab synchronously, in the same tick as the click, so the
  // browser's popup blocker treats it as user-initiated -- opening it only
  // after the signed-URL fetch resolves gets silently blocked.
  const tab = window.open('', '_blank', 'noopener,noreferrer');
  try {
    const res = await api.get<{ success: boolean; url: string }>(endpoint);
    if (tab) tab.location.href = res.url;
    else window.open(res.url, '_blank', 'noopener,noreferrer');
  } catch (err) {
    tab?.close();
    throw err;
  }
}

export const downloadWorksheetPdf = (id: string) => openSignedPdf(`/api/worksheets/${id}/pdf`);
export const downloadAnswerKeyPdf = (id: string) => openSignedPdf(`/api/worksheets/${id}/answer-key`);
